### ISSUE TITLE
/media files in subfolder not showing in notification 

### ISSUE THREAD

**Issue by andriej** [home-assistant/android#1059]
**Home Assistant Android version:** latest stable 2.5.0-full

**Android version:** 10.0

**Phone model:** Oneplus 6

**Home Assistant version:** 0.116.4 (latest)

**Last working Home Assistant release (if known):** n/a

**Description of problem:**
While trying to use new HA's /media folder to serve filess for my mobile phones, I've came across idea of putting camera snapshots in subfolder.
So I've created directory named 'snapshots' inside default's /media (Supervised Debian 10).

And while trying to make notifications working, I couldn't do that.
Unless I've done something like this in HA's configuration:
```  
homeassistant:
  media_dirs:
    local: /media
    snapshots: /media/snapshots  
```
After declaring 'snapshots' subfolder, notifications started to work and shows image hidden in subfolder of 'snapshots'.
So it seems like HA app is not able to somehow 'parse' directory unless it's declared.
In HA's frontend I was able to browse and see files without any problem with or without this declaration.

Code to test:
```yaml
message: test
title: test2
data:
  image: '/media/snapshots/taras_16_010852.jpg'
```
This image didn't show without 'snapshots' declaration and was working well with declaration in HA's config.

**Traceback (if applicable):**
no error in log of HA/ no debug in app

**Screenshot of problem:**
n/a, just notification with title 'test2' and message 'test' with no image and with image when subfolder declared.

**Additional information:**
I'm not sure if it's app or HA's core issue, so start here.
Please help debug and eventually I'll open an issue on core repo if it's not apps fault.
