### ISSUE TITLE
Notification actions stopped working when image also defined

### ISSUE THREAD

**Issue by quazzie** [home-assistant/android#1188]
```
service: notify.myself
data:
  message: Someone at the door
  data:
    image: "http://..../cameraimage.jpg"
    actions: 
      - action: "sayhi"
        title: "Say hi"
```

If I have an image, the image shows but no actions.
If I remove the image the actions show.

**Home Assistant Android version:**
3.0.1-full

**Android version:**
10 QKQ1.190828.002 (MIUI 12.0.2)

**Phone model:**
Pocophone f1

**Home Assistant version:**
0.117.6

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by JBassett** [comment]
I am unable to reproduce:
![Screenshot_20201112-074739.png](https://user-images.githubusercontent.com/1051414/98942069-7841e200-24bb-11eb-815a-ddb0002983e2.png)

**Comment by quazzie** [comment]
Hmm, what android version you got ?

**Comment by JBassett** [comment]
Android 11 with a Pixel 24

**Comment by quazzie** [comment]
```
title: Testing
message: Test
data:
  image: '/local/snapshots/entre_s.jpg'
  actions:
    - action: test
      title: Testing
```
![Screenshot_2020-11-12-14-43-50-501_com mi android globallauncher](https://user-images.githubusercontent.com/2979933/98948062-3f732e80-24f6-11eb-988e-42fce2ef504d.jpg)

```
title: Testing
message: Test
data:
  #image: '/local/snapshots/entre_s.jpg'
  actions:
    - action: test
      title: Testing
```
![Screenshot_2020-11-12-14-44-09-453_com mi android globallauncher](https://user-images.githubusercontent.com/2979933/98948068-426e1f00-24f6-11eb-912d-c99f8bcbdd8a.jpg)

**Comment by dshokouhi** [comment]
I can't reproduce this either:

```
message: test
data:
  image: "/local/mr_neato.jpg"
  actions:
    - action: test
      title: test
```

![image](https://user-images.githubusercontent.com/1634145/98960837-c1913200-24b9-11eb-9b77-b861ff90500a.png)

It might be that you need to start fresh from the app: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app
