### ISSUE TITLE
Actionable sticky/persistent notifications randomly fail to clear

### ISSUE THREAD

**Issue by ksheyman** [home-assistant/android#1223]
I have a number of automations set up for reminders, such as taking my vitamins each day. The idea is that the persistent notification will not go away until I confirm that I have completed the task. Once I press the action button, home assistant reacts to the event and sends a message to clear that notification. Seemingly at random, the notification fails to clear. When this happens, if I try to press the action button again a few times, I get a popup saying that the Home Assistant app has stopped responding. It isn't always the same notification- it does appear to be random. Once this happens the only way to clear the notification is to restart my phone.

Here is an example of my config:

```
  - alias: ask to take vitamins
    trigger:
      - platform: state
        entity_id: sensor.occupancy
    condition:
      condition: state
      entity_id: input_boolean.took_vitamins
      state: 'off'
    mode: single                        
    action:
      - service: notify.mobile_app_sm_g986u
        data:
          title: 'Reminder'
          message: 'Please take your vitamins.'      
          data:
            persistent: 'true'
            sticky: 'true'
            tag: vitamins        
            actions: 
              - action: "vitamins"
                title: "I have taken them."
```

And the automation to clear the notification:

```
  - alias: thank for taking vitamins
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: 'vitamins'        
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.took_vitamins    
      - service: notify.mobile_app_sm_g986u
        data:  
          message: clear_notification
          data:
            tag: vitamins  
```

I would estimate that it works properly 90% of the time, but since I have many of these types of notifications I experience the failure to clear probably once per day. Nothing appears in my HA logs.
