### ISSUE TITLE
Panels with http-auth fail to load

### ISSUE THREAD

**Issue by jhesketh** [home-assistant/android#1224]
**Home Assistant Android version:** 3.0.2-full

**Android version:** 10

**Phone model:** Nokia 7.1

**Home Assistant version:** 0.118.4

**Last working Home Assistant release (if known):** NA

**Description of problem:**

If I have a panel with basic http authentication credentials in the URL it fails to load (just a blank page is given). These panels work fine from the browser/desktop.

Example configuration.yaml:
```
panel_iframe:
  my_site:
    title: Some Site
    url: https://user:password@url.domain.com/
```
(Works fine when no user:password is required).

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
