### ISSUE TITLE
Chronometer Notification not working with template

### ISSUE THREAD

**Issue by nicogramm** [home-assistant/android#1227]
**Home Assistant Android version:** beta-527-84e6a24-full

**Android version:** 11

**Phone model:** Google Pixel 3a

**Home Assistant version:** 0.118.5

**Last working Home Assistant release (if known):**

**Description of problem:** When using a template to get a timestamp for the chronometer when option for a notification, it doesn't render the template, resulting in the chronometer not showing up in the notification.
When the same template is rendered beforehand using the template dev-tool and the timestamp is entered directly for the when option, so when no template is used, it works without any problems.

**Traceback (if applicable):** n/a

```

```

**Screenshot of problem:**

**Additional information:** The ISS example from the documentation doesn't work either.

**Comment by dshokouhi** [comment]
Can you please share the yaml that you tried?

**Comment by member68** [comment]
I'm running into the same issue. Here's my info and some yaml to reproduce.

**Home Assistant Android version:** 3.0.2-full

**Android version:** 8

**Phone model:** LG V30

**Home Assistant version:** 0.118.5

_This code needs a running timer called "timer.normalwasche"._

```yaml
message: >-
  "Wäsche fertig um {{ (as_timestamp(state_attr('timer.normalwasche', 'finishes_at'))) | timestamp_custom('%X') }}"
data:
  channel: alarm_stream
  tts: 0
  priority: high
  chronometer: true
  when: "{{ as_timestamp(state_attr('timer.normalwasche', 'finishes_at')) | int }}"
```

**Steps to reproduce:**

1. Template Editor with code from above:
![image](https://user-images.githubusercontent.com/321320/101346110-6409be80-3888-11eb-922a-0374ac9de968.png)

2. Calling the service with the template editor output on the right
![image](https://user-images.githubusercontent.com/321320/101346258-987d7a80-3888-11eb-9452-54e6c089a289.png)

3. Notification with chronometer is shown
![image](https://user-images.githubusercontent.com/321320/101346678-31ac9100-3889-11eb-8915-80fbbd864ed8.png)

4. Calling the service with the template editor input on the left
![image](https://user-images.githubusercontent.com/321320/101346313-a8955a00-3888-11eb-93e8-e4d509aba0cc.png)

5. Notfication without chronometer is shown
![image](https://user-images.githubusercontent.com/321320/101346685-36714500-3889-11eb-8914-ec54c94b9de1.png)
