### ISSUE TITLE
Last Notification Sensor doesn't trigger automation again when the same notification is displayed more than once

### ISSUE THREAD

**Issue by subism-dev** [home-assistant/android#1253]
**Home Assistant Android version:** 3.0.2-full

**Android version:** Android 11

**Phone model:** Pixel 4 XL

**Home Assistant version:** 2020.12.0

**Last working Home Assistant release (if known):**

**Description of problem:** 

I have a *_smart_* washing (laundry) machine... It's not so smart. It has an app with very limited functionality. Pretty much the only useful thing it does is send a notification to my phone once my washing cycle has completed.

I am using the Last Notification Sensor on the companion app, and have added my washing machines app to the allowed apps for the sensor.

I have also added an automation in Home Assistant that uses a state trigger to announce via TTS when the washing cycle is completed.

It works great, the first time... However, if I am having a day of doing laundry, I only ever get notified when the first load has completed. The completion of subsequent loads doesn't trigger the automation.

I believe that this is because the notification that my laundry app sends is always the same, and since it is the only allowed app, the state data never really changes?

I'm including an example of the state as seen in home assistant, it is always consistent, no matter how many times I receive the notification:

*State*
```
Your washing cycle has been completed
```

*State Attributes*
```
android.appInfo: ApplicationInfo{4ca67fb it.hoover.wizard}
android.bigText: Your washing cycle has been completed
android.infoText: null
android.largeIcon: null
android.progress: 0
android.progressIndeterminate: false
android.progressMax: 0
android.reduced.images: true
android.remoteInputHistory: null
android.showChronometer: false
android.showWhen: true
android.subText: null
android.template: android.app.Notification$BigTextStyle
android.text: Your washing cycle has been completed
android.title: null
package: it.hoover.wizard
friendly_name: Pixel 4 XL Last Notification
icon: mdi:bell-ring
```

I may be missing an obvious and pre-existing solution, so apologies if that's the case.

If not, maybe adding a state attribute to the last notification sensor with a timestamp of when the notification was received would be beneficial.

Thanks, great work on the app by the way, it's awesome sauce!

Additional:
As i was about to hit send on this, my Nest Hub suddenly announced that "Your washing cycle has been completed".

I had run 2 washing cycles this evening, after the first one completed, a notification came through to my phone, and the TTS was announced.

The second washing cycle finished 23 minutes ago, and the notification came through to my phone straight away, but no automation/tts was triggered.

I had just opened up the Home Assistant Companion app and navigated to the last notification sensor settings to check that there was no extra information I wanted to include and the TTS automation triggered.

Just to test further, I backed out to the main screen of the app, and then navigated to the last notification sensor settings again, but the TTS Automation ddn't trigger again  ¯\_(ツ)_/¯

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you check the logbook for the state changes and also share the automation you used?

**Comment by flexage** [comment]
Sure!

In the logbook there's just one entry for that period:

```
Pixel 4 XL Last Notification changed to Your washing cycle has been completed
3:12:36 - 12 hours ago
```

The simple automation I'm using is as follows:

```
alias: Announce that a washing cycle is complete
description: ''
trigger:
  - platform: state
    entity_id: sensor.pixel_4_xl_last_notification
condition:
  - condition: state
    entity_id: sensor.pixel_4_xl_last_notification
    state: it.hoover.wizard
    attribute: package
action:
  - service: media_player.volume_set
    data:
      volume_level: '0.9'
    entity_id: media_player.living_room_nest_hub
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_nest_hub
      message: '{{ states(''sensor.pixel_4_xl_last_notification'') }}'
  - delay: '00:00:10'
  - service: media_player.volume_set
    data:
      volume_level: '0.5'
    entity_id: media_player.living_room_nest_hub
mode: single
```

It's essentially just using the state as a trigger, that has a condition which checks that the notification is coming from my washing machine app (to limit the scope of this automation in case I decide to add more automations based on other notifications in the future.

It then turns up the volume on the Google Home Hub, Announces via TTS and turns the volume back down.

(Also, sorry I've switched to my actual GitHub account - OP was made using a secondary account by mistake)
