### ISSUE TITLE
Notifications: GIFs only rendering the first frame

### ISSUE THREAD

**Issue by SeraphimSerapis** [home-assistant/android#1270]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
11

**Phone model:**
Pixel 5

**Home Assistant version:**
2020.12.2

**Last working Home Assistant release (if known):**
-

**Description of problem:**
When using the mobile notification feature with a GIF instead of a PNG or JPEG, it seems like only a single frame of the received GIF is rendered.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![signal-2021-01-01-212035](https://user-images.githubusercontent.com/160543/103445646-5a049100-4c77-11eb-8d9f-2f5ae7b86cce.png)

**Additional information:**
Example code to trigger the push notificiation:

```yaml
message: "Test GIF"
data:
  image: "https://media1.tenor.com/images/aba522811b497086c5d35757d6cfb269/tenor.gif"
```

**Comment by dshokouhi** [comment]
android notifications do not support GIF https://stackoverflow.com/a/58482901 so this would not be a bug but maybe an enhancement request (if at all possible)

**Comment by SeraphimSerapis** [comment]
Got it. Thanks!

**Comment by dshokouhi** [comment]
they only take bitmap which is what the app provides

https://developer.android.com/reference/android/app/Notification.BigPictureStyle

**Comment by SeraphimSerapis** [comment]
Reopening for a potential feature request.

I know the Nest app shows a brief animation for camera notifications. Is that a custom implementation?

**Comment by dshokouhi** [comment]
yes those are all custom implementations and override the default android notifications, they need to be built from the ground up, even then I am not sure if a URL gif will work I believe the app has to create it and store it locally in order to display it instead of real time rendering like we do today

**Comment by dshokouhi** [comment]
Found something that might be usable however it has serious limitations such as the user will need to supply the list of image URLs to flip through so a GIF wont work here.  This might be how the other camera apps do it.

https://nishi-emedstore.medium.com/notification-with-image-slider-example-in-android-2758b6d43d38

**Comment by dshokouhi** [comment]
if you have updated to Android 12 it seems they now natively supported animated images. Curious to see if this just "works" now?

https://developer.android.com/about/versions/12/features#enriched_image_support_for_notifications

**Comment by SeraphimSerapis** [comment]
I gave this a try and it doesn't seem to just work automatically (that would've been too nice ;-)):

```
service: notify.notify_tim
data:
  message: Test GIF
  title: Test GIF
  data:
    image: "https://media1.tenor.com/images/aba522811b497086c5d35757d6cfb269/tenor.gif"
```

Same result as in the initial post.

**Comment by dshokouhi** [comment]
Thanks for running that quick test :) Seems now they want us to convert the animated picture to an `Icon` in order to support this

https://developer.android.com/reference/android/app/Notification.BigPictureStyle#bigPicture(android.graphics.drawable.Icon)

**Comment by jpelgrom** [comment]
Just putting the existing `Bitmap` in the `Icon` won't work, looks like this will require the app to temporarily download and store the image (because only `content://` and `file://` uri's are supported) and creating an `Icon` from that local `Uri`, which will then provide the system with the required `AnimatedImageDrawable`.

However, before all that `NotificationCompat` actually needs to catch up and support the new function with `Icon` as a parameter. Google issue for status: https://issuetracker.google.com/issues/215583339

**Comment by Minglarn** [comment]
Hi folks!
So if I understand this correct... Sending a GIF wont show all the frames, just the first one?
Because im trying to send GIF and only the first frame is shown. 
```
service: notify.mobile_app_sm_g998b
data:
  message: TESTING
  title: GIF TEST
  data:
    icon_url: /local/img/frigate/gif/1650374131.922721-o98gqz.mp4.gif
    image: /local/img/frigate/gif/1650374131.922721-o98gqz.mp4.gif
    tag: '919191'
```
