### ISSUE TITLE
Sensor next_alarm not triggering on LG G8S phone

### ISSUE THREAD

**Issue by Morphy99** [home-assistant/android#1382]
**Home Assistant Android version:** 2021.2.2-full

**Android version:** 10

**Phone model:** LG G8S ThinQ - LM-G810EAW

**Home Assistant version:** 2021.2.3

**Last working Home Assistant release (if known):** Possibly 2020.12 or 2021.1 but could be related to app version

**Description of problem:**

Next alarm sensor doesn't trigger for a LG G8 sensor but does for a Samsung S20. No errors visible in the log.

Example simple automation:
```
- alias: zzztest
  trigger:
  - platform: time
    at: sensor.lm_g810_next_alarm
  action:
  - service: light.turn_on
    entity_id: light.test_lights
```

State is reported as:
`2021-03-01T11:46:00.000Z`

State attributes:
```
Local Time: 'Mon Mar 01 11:46:00 GMT 2021'
Package: Unknown
Time in Milliseconds: 1614599160000
friendly_name: G8S Next Alarm
icon: 'mdi:alarm'
device_class: timestamp
```

The S20 has the same state timestamp format but the state attributes "Package" is not unknown so maybe this is the issue?:

```
Local Time: 'Sun Feb 28 12:21:00 GMT 2021'
Package: com.sec.android.app.clockpackage
Time in Milliseconds: 1614514860000
friendly_name: S20 Next Alarm
icon: 'mdi:alarm'
device_class: timestamp
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The next alarm sensor offers an allow list to get around this exact issue, an app setting an invalid time.  You will need to set an allow list for this to work properly.  Also some apps do not respect the Android API properly and will report invalid times.  Samsung in particular is known for this behavior.  Your option is to use an like the google clock app or sleep as android that make good use of the API.

Also duplicate of #1301 #1211 #1190

If the issue is regarding an automation not firing then that is not an app issue but an HA core issue, you will want to open a bug there if that is actually the case.

**Comment by Morphy99** [comment]
Thanks for the prompt reply! The time appears to be reported correctly by both though? It's the package attribute that is missing on the LG entity but I'm not sure if that would cause the automation not to fire. It's strange why the automation with the S20 works ok but with the LG not.

**Comment by dshokouhi** [comment]
if the automation is not firing then that is a HA core issue....all the app does is send over the date/time as a timestamp and HA core takes care of the rest.

**Comment by Morphy99** [comment]
Ok well I guess I need to do some more troubleshooting then as that was the only difference I saw. Thanks for the input.

**Comment by Morphy99** [comment]
I think what is happening is something similar to [this](https://community.home-assistant.io/t/how-to-use-next-alarm-sensor/221686/14) where the sensor is changing to the new date/time a split second before HA triggers. I'm wondering if there can be some sort of delay in the app factored in so this doesn't occur?

It would also explain why [this ](https://community.home-assistant.io/t/how-to-use-next-alarm-sensor/221686/70)guy couldn't get his working but you could.

I tried creating a sensor from the mobile app sensor to trigger two minutes before and this worked fine:

```
- platform: template
  sensors:
    minutes_next_alarm:
      friendly_name: "Minutes until Next Alarm"
      unit_of_measurement: "m"
      value_template: >-
        {% set dummy = states("sensor.time") %}
        {{((states('sensor.lm_g810_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int}}
      availability_template: "{{ not is_state('sensor.lm_g810_next_alarm','unavailable') }}"
      attribute_templates:
        time: "{{ state_attr('sensor.lm_g810_next_alarm','Local Time') }}"
```
