### ISSUE TITLE
"alarm_stream" on Pixel 4XL behave like a just regular notification

### ISSUE THREAD

**Issue by expend20** [home-assistant/android#1427]
**Home Assistant Android version:**

2021.3.1-full

**Android version:**

11, last update 5 of March

**Phone model:**

Pixel 4 XL - buggy / Pixel 3a XL - not buggy

**Home Assistant version:**

core-2021.3.1

**Last working Home Assistant release (if known):**

**Description of problem:**

Hello! First of all thank you for an amazing job you've done, I really enjoy HA and HA Android app everyday in my regular life.

But I've encountered a small issue, which might be a bug. I have two Pixels in my house hold: 3a XL and 4 XL. I leverage [critical notification feature](https://companion.home-assistant.io/docs/notifications/critical-notifications/) for my urgent notifications which supposed to even wake me at night. For example next script is used to **ring my 3a XL until I stop it**.

```
service: notify.mobile_app_pixel_3a_xl
data:
  title: "Wake up!"
  message: "The house is on fire and the cat's stuck in the dryer!"
  data:
    ttl: 0
    priority: high
    channel: alarm_stream
```

And it works perfectly fine for 3a XL. 
However for 4XL the same script is **only making regular notification in the status bar without making my phone ring**

```
service: notify.mobile_app_pixel_4_xl
data:
  title: "Wake up!"
  message: "The house is on fire and the cat's stuck in the dryer!"
  data:
    ttl: 0
    priority: high
    channel: alarm_stream
```

This is a real bummer to me. Is there anything I can do about it? 

Thanks in advance!
