### ISSUE TITLE
Issue navigating to entityId from clickAction

### ISSUE THREAD

**Issue by lwsrbrts** [home-assistant/android#1512]
**Home Assistant Android version:**
2021.4.1-full
**Android version:**
11
**Phone model:**
Google Pixel 4 XL
**Home Assistant version:**
core-2021.4.4
supervisor-2021.04.0
Home Assistant OS 5.13
**Last working Home Assistant release (if known):**

**Description of problem:**
Using the following notification YAML:

```yaml
service: notify.mobile_app_pixel_4_xl
data:
  title: 'INFO: Hot water boosted'
  message: The hot water has been boosted due to high humidity in the main bathroom.
  data:
    clickAction: 'entityId:sensor.bathroom_humidity'
    color: '#008000'
    sticky: 'true'
    group: Information
```

Yields the expected notification. Tapping the notification should start the Home Assistant Companion App and show the `'entityId:sensor.bathroom_humidity'` entity as per the [documentation](https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-click-action). Instead, the application starts and *begins* to show the entity but immediately the display/page changes to the default lovelace view as set in the user profile.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Hopefully this animated gif will work as expected:
![screenrecording](https://www.eastgateit.co.uk/tmp/screengrab.gif)
If not, please see: https://www.eastgateit.co.uk/tmp/screengrab.gif

**Additional information:**
