### ISSUE TITLE
Notifications doesn't wake phone up

### ISSUE THREAD

**Issue by andriej** [home-assistant/android#153]
As title says - notifications does not wake screen/phone, they show up after interaction with phone.
HTML5 push does that instantly or after a short while.

**Comment by dshokouhi** [comment]
Did you make sure to turn off battery optimizations for the app?  When we tested this earlier the notifications were definitely waking up the phone. Only time it didn't wake up the phone was when we restarted the phone and didn't open the app.

**Comment by andriej** [comment]
I did it for a test now, will check. For HTML5 there's no way to turn off optimization.
If it's needed for notifications it would be nice to add 'startup procedure' suggesting doing so. :-)

**Comment by pergolafabio** [comment]
First observation, I have disabled battery optimalization , so this morning, when doorbell rang, the message came in, when my phone was in deep sleep… So that’s good…
But only 3 minutes later… So there is a delay though…

I am also using pushover for a notify system, those are always instant… There is a priority setting there… Is such thing also coming?

**Comment by ndarilek** [comment]
Agreed that the battery optimization check might be useful in the onboarding activity. Having an issue with connection loss/stale state, and just tried disabling optimization as a possible fix. It's one of those things I know about, but I don't think about it unless actively reminded by, say, an onboarding step. :)

**Comment by allanpersson** [comment]
@ndarilek I have an open issue with what I think is important to warn/prompt about here https://github.com/home-assistant/home-assistant-android/issues/119

**Comment by scottismyname** [comment]
This is off topic, but I'm a bit confused on how to use notifications in the app.  Can someone explain or PM me? Thanks!

**Comment by allanpersson** [comment]
@scottismyname you can pm me and I'll be happy to help you 🙏

**Comment by scottismyname** [comment]
sorry again for the off topic comment.  I don't see a way to PM, nor do I see an email.  @allanpersson my email is skaforey@gmail.com if you wouldn't mind.  I will delete this message shortly.  Sorry, not sure what else to do!

**Comment by pergolafabio** [comment]
After a few days testing, my phone doesn't receive notification in deep sleep, while battery optimalization is disabled...

Pushover however is working...
I had same issues with html5

**Comment by allanpersson** [comment]
> sorry again for the off topic comment. I don't see a way to PM, nor do I see an email. @allanpersson my email is  if you wouldn't mind. I will delete this message shortly. Sorry, not sure what else to do!

Mail sent 🙏

**Comment by robbiet480** [comment]
Is this still an issue? If so, can you set TTL to `0` and priority to `high` in your notifications and see if that changes anything? For example:

```yaml
title: 'Title Text'
message: 'Body Text'
data:
  ttl: 0
  priority: 'high'
```

**Comment by dshokouhi** [comment]
So I have personally tried setting both `ttl` and `priority` but in all cases after not using my phone for 5-10 minutes the notification would not show up until the screen turns on.   The moment the screen turns on all notifications that I sent from HA show up at once.

**Comment by pergolafabio** [comment]
still not working for me either, tested below script, maybe its the image? but what i noticed, the message didnt come, i had to wake up phone, and even i had to open the "home assistant" app , the the push message arrived

```
aa_test:
  alias: Doorbell notification
  sequence:
  - service: !secret notify_ha_fabio
    data:
      title: "Alert"
      message: "Someone at the door"
      data:
        # actions:
          # - action: "close_garage" # The key you are sending for the event
            # title: "Close Garage Door" # The button title 
        image: "https://i.pinimg.com/originals/0f/7b/fa/0f7bfa4e6775b5977694a6036fc85b48.png"  
        priority: high
        ttl: 0        
  
```
