### ISSUE TITLE
binary_sensor high_accuracy_mode on/off

### ISSUE THREAD

**Issue by rgruebel** [home-assistant/android#1567]
**Is your feature request related to a problem? Please describe.**
I want to create a tap_action in lovelace to turn the high accuracy mode on or off (with a notification command) depending on the current state.

**Describe the solution you'd like**
A new binary_sensor.<device_name>_high_accuracy_mode

**Comment by Erelen-Laiquendi** [comment]
Binary sensor or attribute "high accuracy mode" to current location sensor, please!

@rgruebel, now you can create template switch:

```
switch:
  - platform: template
    switches:
      myphone_high_accuracy_mode:
        friendly_name: MyPhone High Accuracy
        # value_template: "{{ is_state_attr('device_tracker.myphone', 'high_accuracy_mode', 'on') }}"
        turn_on:
          - service: notify.mobile_app_myphome
            data:
              message: "command_high_accuracy_mode"
              title: "turn_on"
              data:
                priority: high
                ttl: 0
        turn_off:
          - service: notify.mobile_app_myphome
            data:
              message: "command_high_accuracy_mode"
              title: "turn_off"
              data:
                priority: high
                ttl: 0
```
And call `switch.toggle` from lovelace.

But this is optimistic switch: without real mode feedback (but with this issue it will be possible to use commented line).
