### ISSUE TITLE
Allow HA to change connected bluetooth device

### ISSUE THREAD

**Issue by newhinton** [home-assistant/android#1590]
**Is your feature request related to a problem? Please describe.**

I would like to change the connected bluetooth device when triggering an automation. This would allow to connect to a device that was previously offline

**Describe the solution you'd like**

Home Assistant should be able to run a service on a given device that triggers the change of the connected bluetooth device

**Describe alternatives you've considered, if any**

**Additional context**

Related/Similar to #436

**Comment by newhinton** [comment]
This is still not resolved. If a human wants to close this plrase do so, otherwise i'd like to keep it open

**Comment by jsuelwald** [comment]
I've seen this issue because i was also searching for a way to control which bluetooth devices my smartphone is connected to using Home Assistant.

**Comment by KamilKot95** [comment]
+1

**Comment by julianlawson** [comment]
+1

**Comment by markaggar** [comment]
Surprised this isn't possible already. I landed on this page after searching for how to do it!

**Comment by markaggar** [comment]
I figured out a way to achieve what I wanted, using Bixby Routines (on Samsung) which might work on tasker. Essentially, I created a routine that disconnects the specific Bluetooth devices that is triggered by a notification from HA. The notification has a tag which is cleared immediately by another notification.

E.g.

```
alias: Disconnect earbuds
metadata: {}
data:
  data:
    ttl: 0
    tag: disconnect_buds
  message: disconnect earbuds
action: notify.mark

alias: Disconnect earbuds
metadata: {}
data:
  data:
    ttl: 0
    tag: disconnect_buds
  message: clear_notification
action: notify.mark

```
