### ISSUE TITLE
Login attempt or request with invalid authentication (External URL)

### ISSUE THREAD

**Issue by cm86** [home-assistant/android#1600]
**Home Assistant Android version:**
2021.6.2-full
**Android version:**
11
**Phone model:**
Samsung Galaxy A50
**Home Assistant version:**
2021.6.6
**Last working Home Assistant release (if known):**

**Description of problem:**
I can't login in my Home Assistant by using the external URL within the HomeAssistant Android App.
I'm getting the following error in the log.
`Login attempt or request with invalid authentication from ip-xxx-xxx-xxx-xxx.web.vodafone.de (xxx.xxx.xxx.xxx). (HomeAssistant/Android 2021.6.2-694)
Login attempt or request with invalid authentication from ip-xxx-xxx-xxx-xxx.web.vodafone.de (xxx.xxx.xxx.xxx). (Mozilla/5.0 (Linux; Android 11; SM-A505FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36)`

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

[Logfile](https://pastebin.com/pj3trSbP)

**Screenshot of problem:**
![Screenshot_20210630-091235_Home Assistant](https://user-images.githubusercontent.com/14919688/123919446-39e32f80-d985-11eb-9dfa-a900ff78aa2d.jpg)

**Additional information:**
`configuration.yaml`
```
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/24
    - 172.18.0.0/24
#   ip_ban_enabled: false
#   login_attempts_threshold: 5

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.0.0.0/24
```
