### ISSUE TITLE
Power/Devices menu fan control uses deprecated fan speed service and attributes.

### ISSUE THREAD

**Issue by ruifung** [home-assistant/android#1604]
**Home Assistant Android version:**
2021.6.2-full
**Android version:**
11
**Phone model:**
Samsung Galaxy S20 FE 5G
**Home Assistant version:**
core-2021.6.6
**Last working Home Assistant release (if known):**
The version prior to the introduction of percentage speed / preset modes.
**Description of problem:**
Fan shows as 0 speed in the devices menu.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/1073945/124368875-3eb32680-dc98-11eb-9291-30c7e9b5fdcf.png)
![image](https://user-images.githubusercontent.com/1073945/124368889-6dc99800-dc98-11eb-9410-994ec27d10e3.png)

**Additional information:**

Fan configuration, if relevant.
```
unique_id: panasonicFMU44R_rf_room_wall_fan
name: RF Room Wall Fan
command_topic: rfhome/panasonicFMU44R/rf_room_wall_fan/speed/command
oscillation_command_topic: rfhome/panasonicFMU44R/rf_room_wall_fan/oscillate/command
oscillation_state_topic: rfhome/panasonicFMU44R/rf_room_wall_fan/oscillate/state
state_topic: rfhome/panasonicFMU44R/rf_room_wall_fan/state
percentage_command_topic: rfhome/panasonicFMU44R/rf_room_wall_fan/speed/command
percentage_state_topic: rfhome/panasonicFMU44R/rf_room_wall_fan/speed/state
payload_oscillation_off: 'off'
payload_oscillation_on: 'on'
payload_on: 'on'
payload_off: 'off'
speed_range_min: 1
speed_range_max: 3
availability:
  - topic: appdaemon_server-pi-3/status
    payload_available: value_not_in_use_do_not_send
  - topic: rfhome/panasonicFMU44R/rf_room_wall_fan/status
device:
  identifiers: panasonicFMU44R_rf_room_wall_fan
  manufacturer: Panasonic
  name: RF Room Wall Fan
  sw_version: rf_custom_panasonicFMU44R
platform: mqtt
```
