### ISSUE TITLE
Alarm_stream notifications remain silent

### ISSUE THREAD

**Issue by BigDoom** [home-assistant/android#1611]
**Home Assistant Android version:**
2021.6.2-full

**Android version:**
11

**Phone model:**
Galaxy S21 Ultra 5G

**Home Assistant version:**
Core: 2021.6.6
Supervisor: 2021.06.8
Host: HA OS 6.1

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
Ongoing problems with alarm_stream notifications not making an audible sound. Several fixes have been made as reported in #1159 and #1167, but still no succes. 

As per documentation this should work, which is not the case. It creates a channel in Android where I can set the sound and to bypass Do No Disturb, but when the phone is on vibrate or silent mode the notification also remain silent or vibration only. My thought was that using the alarm_stream this would override the silent/vibrate modes and gives an audible sound always.

```
- alias: 'NOTIFY - DOORBELL ringing'
    trigger:
      - platform: state
        entity_id: switch.doorbell
        to: 'on'
    action:
      - service: notify.mobile_app
        data:
          title: "Wake up!"
          message: "The house is on fire and the cat's stuck in the dryer!"
          data:
            ttl: 0
            priority: high
            channel: alarm_stream
```

In the meantime this still works as a workaround, but I would like to implement the method above which is more cleaner when it works.
```
- alias: 'NOTIFY - DOORBELL ringing'
    trigger:
      - platform: state
        entity_id: switch.doorbell
        to: 'on'
    variables:
      ringer_mode: "{{ states('sensor.phone_ringermode') }}"
    action:
      - service: notify.mobile_app
        data:
          message: "command_ringer_mode"
          title: "normal"
          data:
            ttl: 0
            priority: high
      - service: notify.mobile_app
        data:
          message: "command_volume_level"
          title: 50
          data:
            ttl: 0
            priority: high
            channel: notification_stream
      - service: notify.mobile_app
        data:
          title: "Some title"
          message: "Some message"
          data:
            ttl: 0
            priority: high
            channel: Doorbell 
            tag: doorbell-ringing
      - delay: '00:00:03'
      - service: notify.mobile_app
        data:
          message: "command_ringer_mode"
          title: "{{ ringer_mode }}"
          data:
            ttl: 0
            priority: high
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
