### ISSUE TITLE
alarm_stream notifications silent

### ISSUE THREAD

**Issue by JohannCR** [home-assistant/android#1650]
**Home Assistant Android version:**
2021.6.2

**Android version:**
Pie 9 PPX29.159-24

**Phone model:**
Moto Z2 Force (XT1789-06)

**Home Assistant version:**
2021.7.4

**Last working Home Assistant release (if known):**

**Description of problem:**
alarm_stream makes no sound
Here is my notification config. TTS works but not alarm_stream/alarm_stream_max. I've tested with and without command_dnd and ringer_mode, doesn't change anything.
Notification goes through, it vibrates, but no sound is emitted.

```
action:
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_dnd
      title: 'off'
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_ringer_mode
      title: normal
  - service: notify.mobile_app_moto_z_2
    data:
      title: "WORKING notification"
      message: TTS
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
  - service: notify.mobile_app_moto_z_2
    data:
      message: NOT WORKING notification
      title: too bad
      data:
        channel: alarm_stream_max
        importance: high
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
07-27 15:12:37.389 32211 32662 D MessagingService: From: 331041709873
07-27 15:12:37.389 32211 32662 D MessagingService: Message data payload: {title=off, message=command_dnd}
07-27 15:12:37.394 32211 32662 D MessagingService: Processing device command
07-27 15:12:37.627 32211 32662 D MessagingService: From: 331041709873
07-27 15:12:37.627 32211 32662 D MessagingService: Message data payload: {title=normal, message=command_ringer_mode}
07-27 15:12:37.627 32211 32662 D MessagingService: Processing device command
07-27 15:12:37.632 32211 32662 I AudioManager: setRingerMode() = 2
07-27 15:12:37.639 32211 32211 D SensorReceiver: Sensor audio_sensor corresponding to received event android.media.RINGER_MODE_CHANGED is disabled, skipping sensors update
07-27 15:12:38.118 32211 32662 D MessagingService: From: 331041709873
07-27 15:12:38.118 32211 32662 D MessagingService: Message data payload: {title=WORKING notification, channel=alarm_stream, message=TTS}
07-27 15:12:38.118 32211 32662 D MessagingService: Sending notification title to TTS
07-27 15:12:38.126 32211 32662 W mpanion.androi: Unknown chunk type '200'.
07-27 15:12:38.126 32211 32662 W mpanion.androi: Unknown chunk type '200'.
07-27 15:12:38.141 32211 32211 I TextToSpeech: Connected to ComponentInfo{com.google.android.tts/com.google.android.apps.speech.tts.googletts.service.GoogleTTSService}
07-27 15:12:38.141 32211 32662 I TextToSpeech: Sucessfully bound to com.google.android.tts
07-27 15:12:38.152 32211 32668 I TextToSpeech: Set up connection to ComponentInfo{com.google.android.tts/com.google.android.apps.speech.tts.googletts.service.GoogleTTSService}
07-27 15:12:38.153 32211 32211 D MessagingService: speaking notification
07-27 15:12:38.510 32211 32662 D MessagingService: From: 331041709873
07-27 15:12:38.510 32211 32662 D MessagingService: Message data payload: {title=too bad, channel=alarm_stream_max, message=NOT WORKING notification, importance=high}
07-27 15:12:38.512 32211 32211 D MessagingService: Creating notification with following data: {title=too bad, channel=alarm_stream_max, message=NOT WORKING notification, importance=high}
07-27 15:12:38.526 32211 32211 D MessagingService: Show notification with tag "null" and id "-401046672"
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
duplicate of #1465 

I see you had attempted to use the workaround.  Please note that when you change DND and/or ringer mode you should not be using the alarm stream parameter.  Just send a normal notification, the workaround is to change DND, send the normal notification and then switch back.

**Comment by JohannCR** [comment]
@dshokouhi Thanks but nope it does not work any better changer ringer mode and not using the alarm stream... Still no sound.

**Comment by dshokouhi** [comment]
@JohannCR send a normal notification after changing the DND state

```
action:
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_dnd
      title: 'off'
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_ringer_mode
      title: normal
  - service: notify.mobile_app_moto_z_2
    data:
      message: test
```

Also keep in mind that the first time you send DND or ringer mode command the system will prompt you to grant special permissions to the app. Without you granting that permission we cannot change DND state which will result in the error you see.

https://companion.home-assistant.io/docs/notifications/notification-commands#do-not-disturb

you may also want to check volume level if its still silent.  You basically have to control your device and take it out of the DND state.

**Comment by JohannCR** [comment]
1°) That's exactly what I just tried ^^
2°) I did give the rights on the first try, no problem here.
3°) For volume level isn't that what "command_ringer_mode" is for ? In any case I put all sound levels to max for the test even if the goal is for it to work when I'm on vibrate with no notification sound.

Unless I missed something, something's amiss here, isn't it ? ;-)
Thanks for your help

**Comment by dshokouhi** [comment]
> For volume level isn't that what "command_ringer_mode" is for ?

changing ringer mode does not have an impact on the audio level of the chosen stream.

Check that your device is actually changing DND and ringer state...also doulbe check app permissions to make sure its all granted proeprly

**Comment by dshokouhi** [comment]
samsung is known for changing android features to the point where android documentation does not suffice....there is not much we can do when a manufacturer decides to go beyond what google has intended.  So nothing is amiss here with the app.

**Comment by JohannCR** [comment]
DND is actually changed, I use it in another automation.
Plus the notification is forwarded to my watch so the phone is successfully out of DND, it just makes no sound.
Rights have been double checked.

> samsung is known for changing android features to the point where android documentation does not suffice....there is not much we can do when a manufacturer decides to go beyond what google has intended. So nothing is amiss here with the app.

Not a samsung phone, but I guess it's the same difference... I'll check on a different phone too.
It's too bad

**Comment by dshokouhi** [comment]
so your device doesnt make a sound at all for any notification? that would be silently different than stating alarm stream is silent.

**Comment by JohannCR** [comment]
No, the device stays silent when waking from DND mode. Sorry if I wasn't clear.
In normal state everything works well, it's only when trying to have a notification sound when the phone is in DND that nothing works (except TTS). 
So you're right it's not the alarm_stream that is at fault... Is it the wake-up from DND being somewhat incomplete ? Hum I'm going to try to tinker with dnd settings...

**Comment by JohannCR** [comment]
Damn ! It's the moto gestures ! I deactivated the DND activated by turning the phone over, and when I put it in dnd manually, the notification makes a sound, it works... Damn the gesture was so useful how come it's different ?

**Comment by JohannCR** [comment]
Alright it was a little more complicated than just deactivating the moto gestures. Had to try a lot of parameters and after a lot of trial and error I got it to work reliably.
Here is my (minimal) working config (it breaks if I remove any of it) for those having similar problems.

1°) Do not use DND with moto gestures. Does not work. Use the drop down android menu to put in DND.
2°) I don't know why but my watch also made things complicated : I would receive the notification on the watch and have no sound from the phone. So had to deactivate bluetooth in order for the phone to ring the notification...
3°) Also ringer_mode to normal because I'm always on vibrate only.
4°) The 1 second delay also seems necessary for the phone to process I guess.
5°) &ref_0 seems to define an action that be referred to (and duplicated) using *ref_0.

```
action:
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_dnd
      title: 'off'
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_bluetooth
      title: turn_off
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_ringer_mode
      title: normal
  - &ref_0
    delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.mobile_app_moto_z_2
    data:
      message: test message
      title: WORKS !
      data:
        ttl: 0
        priority: high
  - *ref_0
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_ringer_mode
      title: vibrate
  - service: notify.mobile_app_moto_z_2
    data:
      message: command_bluetooth
      title: turn_on
```
