### ISSUE TITLE
Weird spacing in 4th row in minimal companion version.

### ISSUE THREAD

**Issue by HAuser2019** [home-assistant/android#1656]
**Home Assistant Android version:**
2021.6.2-minimal

**Android version:**
8.1 without GMT

**Phone model:**
TW1523AS-B1P

**Home Assistant version:**
Home Assistant 2021.7.4

**Last working Home Assistant release (if known):**
?

**Description of problem:**
Weird spacing in 4th row in **minimal** companion version.

**Screenshot of problem:**
![1](https://user-images.githubusercontent.com/76201374/127694536-651979cf-f001-4e31-b68d-86a39e826442.JPG)

**Additional information:**
Tried modifing the code, made new code, and wiggle things arround. But the issue persists.
The "problem" doesn't appear in the full version, iOS nor the webbrowser.

Tried changing the content in the colmns, but then other "strange" anomalies appear:
In the "full" or iOS/website version it's oke.
![2](https://user-images.githubusercontent.com/76201374/127694851-81e4e9dc-af57-40cb-b6b1-181bc95703b1.JPG)
In the limited version things happen:
![3](https://user-images.githubusercontent.com/76201374/127694862-77dcada5-8816-488f-8b9c-c244eece31f0.JPG)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
This is my lovelace code:
```
  - background: url("/local/BasaltGreyOrigineel.jpg") fixed
    icon: mdi:silverware-variant
    path: keuken
    theme: light
    title: Keuken
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: /local/vaatwasser_uit.png
                elements:
                  - type: image
                    entity: sensor.dishwasher
                    tap_action:
                      action: call-service
                      service: switch.toggle
                      service_data:
                        entity_id: switch.vaatwasser_power
                    style:
                      top: 50%
                      left: 50%
                      width: 100%
                    state_image:
                      Standby: /local/vaatwasser_uit.png
                      Power-on: /local/vaatwasser_aan.png
                      Auto1: /local/vaatwasser_duration.png
                      Auto2: /local/vaatwasser_duration.png
                      Auto3: /local/vaatwasser_duration.png
                      Autohalfload: /local/vaatwasser_duration.png
                      Eco50: /local/vaatwasser_duration.png
                      Expresssparkle65: /local/vaatwasser_duration.png
                      Glas40: /local/vaatwasser_duration.png
                      Glasscare: /local/vaatwasser_duration.png
                      Intensive45: /local/vaatwasser_duration.png
                      Intensive70: /local/vaatwasser_duration.png
                      Intensivepower: /local/vaatwasser_duration.png
                      Kort60: /local/vaatwasser_duration.png
                      Machinecare: /local/vaatwasser_duration.png
                      Dailymagic: /local/vaatwasser_duration.png
                      Maximumcleaning: /local/vaatwasser_duration.png
                      Silent: /local/vaatwasser_duration.png
                      Normal45: /local/vaatwasser_duration.png
                      Normal65: /local/vaatwasser_duration.png
                      Quick45: /local/vaatwasser_duration.png
                      Quick65: /local/vaatwasser_duration.png
                      Steamfresh: /local/vaatwasser_duration.png
                      Super60: /local/vaatwasser_duration.png
                      Finished: /local/vaatwasser drogen.png
                      unknown: /local/vaatwasser_uit.png
                  - type: state-badge
                    entity: switch.vaatwasser_power
                    state_color: true
                    tap_action:
                      action: toggle
                    style:
                      top: 16%
                      left: 2%
                      color: white
                      transform: scale(0.9)
                      filter: drop-shadow(1px 1px 1px black)
                  - type: state-icon
                    entity: binary_sensor.vaatwasser_door
                    prefix: ' '
                    style:
                      top: 5.5%
                      left: 40%
                      font-size: 115%
                      font-weight: 375
                      max-width: 1px
                  - type: state-label
                    entity: sensor.dishwasher
                    prefix: ' '
                    style:
                      top: 6.5%
                      color: white
                      left: 60%
                      font-size: 115%
                      font-weight: 375
                      max-width: 1px
                  - type: state-label
                    entity: input_select.select_dishwasher_program
                    suffix: ' geselecteerd'
                    state_color: true
                    tap_action:
                      action: more-info
                    style:
                      top: 85%
                      left: 34%
                      color: white
                      font-size: 110%
                      font-weight: 700
                  - type: state-label
                    entity: sensor.vaatwasser_program_progress
                    suffix: ' progress'
                    style:
                      top: 85%
                      left: 63%
                      font-size: 110%
                      font-weight: 700
                      max-width: 1px
                      color: white
                  - type: state-label
                    entity: sensor.vaatwasser_operation_state
                    suffix: ''
                    style:
                      top: 93%
                      left: 69%
                      font-size: 100%
                      font-weight: 800
                      max-width: 1px
                      color: white
          - type: horizontal-stack
            cards:
              - type: history-graph
                entities:
                  - entity: sensor.dishwasher
                    name: status
                hours_to_show: 16
                refresh_interval: 0
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: /local/0-210x121tile_white.png
                elements:
                  - entity: script.1577452698973
                    icon: mdi:weather-sunny
                    service: script.turn_on
                    service_data:
                      entity_id: script.1577452698973
                    style:
                      left: 40%
                      top: 32%
                      color: SteelBlue
                      transform: scale(1.75)
                    tap_action:
                      action: toggle
                    title: test
                    type: icon
              - type: picture-elements
                image: /local/0-210x121tile_white.png
                elements:
                  - entity: script.1577452726977
                    icon: mdi:silverware-variant
                    service: script.turn_on
                    service_data:
                      entity_id: script.1577452726977
                    style:
                      left: 40%
                      top: 32%
                      color: SteelBlue
                      transform: scale(1.75)
                    tap_action:
                      action: toggle
                    title: test
                    type: icon
              - type: picture-elements
                image: /local/0-210x121tile_white.png
                elements:
                  - entity: script.1577453114285
                    icon: mdi:weather-night
                    service: script.turn_on
                    service_data:
                      entity_id: script.1577453114285
                    style:
                      left: 40%
                      top: 32%
                      color: SteelBlue
                      transform: scale(1.75)
                    tap_action:
                      action: toggle
                    title: test
                    type: icon
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: /local/KeukenAvond_v4.png
                elements:
                  - type: conditional
                    conditions:
                      - entity: sun.sun
                        state: above_horizon
                      - entity: sun.sun
                        state_not: below_horizon
                    elements:
                      - type: image
                        entity: sun.sun
                        image: /local/KeukenDag_v4.png
                        style:
                          top: 50%
                          left: 50%
                          width: 100%
                  - type: service-button
                    title: Uit
                    service: homeassistant.turn_off
                    style:
                      border: 5px solid SteelBlue
                      border-radius: 1%
                      filter: brightness(100%)
                      left: 90.5%
                      top: 12.5%
                      width: 14%
                    service_data:
                      entity_id: light.keuken
                  - type: state-icon
                    entity: light.bol_keuken
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.bol_keuken
                    style:
                      filter: drop-shadow(0px 0px 10px white)
                      left: 20%
                      top: 50%
                      transform: scale(2.0)
                  - type: state-icon
                    entity: light.hue_lightstrip_keuken
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.hue_lightstrip_keuken
                    style:
                      filter: drop-shadow(0px 0px 10px black)
                      left: 55%
                      top: 3%
                      transform: scale(2.0)
                  - type: state-icon
                    entity: light.keuken_vloer
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.keuken_vloer
                    style:
                      filter: drop-shadow(0px 0px 10px black)
                      left: 34%
                      top: 19%
                      transform: scale(2.0)
                  - type: state-icon
                    entity: light.keukentafel
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.keukentafel
                    style:
                      filter: drop-shadow(0px 0px 5px white)
                      left: 75%
                      top: 55%
                      transform: scale(2.0)
                  - type: state-icon
                    entity: light.keuken_links
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.keuken_links
                    style:
                      filter: drop-shadow(0px 0px 10px white)
                      left: 0%
                      top: 77%
                      transform: scale(2.0)
                  - type: state-icon
                    entity: light.keuken_rechts
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.keuken_rechts
                    style:
                      filter: drop-shadow(0px 0px 10px white)
                      left: 0%
                      top: 50%
                      transform: scale(2.0)
                  - type: state-icon
                    entity: light.kookeiland
                    hold_action:
                      action: call-service
                      service: light.turn_on
                      service_data:
                        brightness_pct: 100
                        entity_id: light.keuken_eiland
                    style:
                      filter: drop-shadow(0px 0px 10px white)
                      left: 34%
                      top: 55%
                      transform: scale(2.0)
                  - type: state-label
                    entity: sensor.woonkamersensor_temperature
                    style:
                      top: 35%
                      left: 58%
                      color: white
                      font-size: 1.5rem
                      filter: drop-shadow(1px 1px 2px black)
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: /local/0-210x121tile_white.png
                elements:
                  - type: state-label
                    suffix: mp
                    entity: sensor.current_phase_l1
                    style:
                      top: 30%
                      left: 50%
                      color: black
                      font-size: 150%
                      font-weight: 400
                  - type: service-button
                    entity: null
                    title: L1
                    style:
                      top: 47%
                      left: 35%
                      color: white
                      transform: scale(2.0)
                    service: person.reload
              - type: picture-elements
                image: /local/0-210x121tile_white.png
                elements:
                  - type: state-label
                    suffix: mp
                    entity: sensor.current_phase_l2
                    style:
                      top: 30%
                      left: 50%
                      color: black
                      font-size: 150%
                      font-weight: 400
                  - type: service-button
                    entity: null
                    title: L2
                    style:
                      top: 47%
                      left: 35%
                      color: white
                      transform: scale(2.0)
                    service: person.reload
              - type: picture-elements
                image: /local/0-210x121tile_white.png
                elements:
                  - type: state-label
                    suffix: mp
                    entity: sensor.current_phase_l3
                    style:
                      top: 30%
                      left: 50%
                      color: black
                      font-size: 150%
                      font-weight: 400
                  - type: service-button
                    entity: null
                    title: L3
                    style:
                      top: 47%
                      left: 35%
                      color: white
                      transform: scale(2.0)
                    service: person.reload
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: sensor.afvalwijzer_pmd
                image: /local/pmd.png
                show_name: false
                show_state: true
                aspect_ratio: 100%
              - aspect_ratio: 100%
                entity: sensor.afvalwijzer_gft
                image: /local/gft.png
                show_name: false
                show_state: true
                type: picture-entity
              - aspect_ratio: 100%
                entity: sensor.afvalwijzer_papier
                image: /local/papier.png
                show_name: false
                show_state: true
                type: picture-entity
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: /local/koffie_uit.png
                elements:
                  - type: image
                    entity: sensor.koffiemachine
                    tap_action:
                      action: call-service
                      service: switch.toggle
                      service_data:
                        entity_id: switch.espresso_volautomaat_power
                    style:
                      top: 50%
                      left: 50%
                      width: 100%
                    state_image:
                      Standby: /local/koffie_uit.png
                      Power-on: /local/koffie_aan.png
                      Americano: /local/koffie_duration.png
                      Caffelatte: /local/koffie_duration.png
                      Cappuccino: /local/koffie_duration.png
                      Coffee: /local/koffie_duration.png
                      Cortado: /local/koffie_duration.png
                      Espresso: /local/koffie_duration.png
                      Espressodoppio: /local/koffie_duration.png
                      Espressomacchiato: /local/koffie_duration.png
                      Flatwhite: /local/koffie_duration.png
                      Galao: /local/koffie_duration.png
                      Lattemacchiato: /local/koffie_duration.png
                      Milkfroth: /local/koffie_duration.png
                      Ristretto: /local/koffie_duration.png
                      Warmmilk: /local/koffie_duration.png
                      Ready: /local/koffie_klaar.png
                      Finished: /local/koffie_klaar.png
                      unknown: /local/koffie_uit.png
                  - type: state-badge
                    entity: switch.espresso_volautomaat_power
                    state_color: true
                    tap_action:
                      action: toggle
                    style:
                      top: 16%
                      left: 2%
                      color: white
                      transform: scale(0.9)
                      filter: drop-shadow(0px 1px 1px black)
                  - type: state-label
                    entity: sensor.koffiemachine
                    prefix: ' '
                    style:
                      top: 6.5%
                      color: white
                      left: 60%
                      font-size: 115%
                      font-weight: 375
                      max-width: 1px
                  - type: state-label
                    entity: input_select.select_coffee
                    suffix: ' geselecteerd'
                    state_color: true
                    tap_action:
                      action: more-info
                    style:
                      top: 85%
                      left: 35%
                      color: white
                      font-size: 110%
                      font-weight: 700
                  - type: state-label
                    entity: sensor.espresso_volautomaat_program_progress
                    suffix: ' progress'
                    style:
                      top: 85%
                      left: 68%
                      font-size: 110%
                      font-weight: 700
                      max-width: 1px
                      color: white
                  - type: state-label
                    entity: sensor.espresso_volautomaat_operation_state
                    suffix: ''
                    style:
                      top: 93%
                      left: 75%
                      font-size: 100%
                      font-weight: 800
                      max-width: 1px
                      color: white
          - type: horizontal-stack
            cards:
              - type: picture
                image: /local/actueelweer.png
                tap_action:
                  action: none
                hold_action:
                  action: none
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                state_color: true
                entities:
                  - entity: sensor.weer
                  - type: divider
                  - entity: sensor.waarschuwing
                    name: Waarschuwingen
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.buienradar_pressure
                detail: 2
                name: Baro
                hours_to_show: 24
                graph: line
              - type: sensor
                entity: sensor.buienradar_humidity
                graph: line
                name: Vocht
                hours_to_show: 24
              - type: sensor
                entity: sensor.buienradar_rain_last_24h
                name: Regen 24u
                hours_to_show: 24
                detail: 2
          - type: horizontal-stack
            cards:
              - type: conditional
                conditions:
                  - entity: sun.sun
                    state: below_horizon
                  - entity: sun.sun
                    state_not: above_horizon
                card:
                  type: sensor
                  name: Avond
                  entity: sensor.buienradar_temperature
                  graph: line
                  hours_to_show: 24
              - type: conditional
                conditions:
                  - entity: sun.sun
                    state: above_horizon
                  - entity: sun.sun
                    state_not: below_horizon
                card:
                  type: sensor
                  name: Dag
                  entity: sensor.buienradar_ground_temperature
                  graph: line
                  hours_to_show: 24
              - type: sensor
                entity: sensor.buienradar_wind_force
                graph: line
                name: Wind
                hours_to_show: 24
              - type: sensor
                entity: sensor.buienradar_wind_direction
                hours_to_show: 1
                detail: 1
                name: Richting
          - type: horizontal-stack
            cards:
              - type: history-graph
                entities:
                  - entity: sensor.buienradar_barometer_2
                hours_to_show: 24
                refresh_interval: 0
              - type: history-graph
                entities:
                  - entity: sensor.buienradar_wind_direction
                hours_to_show: 1
                refresh_interval: 0
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: /local/oven_uit.png
                elements:
                  - type: image
                    entity: sensor.oven
                    tap_action:
                      action: call-service
                      service: switch.toggle
                      service_data:
                        entity_id: switch.oven_power
                    style:
                      top: 50%
                      left: 50%
                      width: 100%
                    state_image:
                      Standby: /local/oven_uit.png
                      Power-on: /local/oven_aan.png
                      Preheat: /local/oven_preheat.png
                      Microwave: /local/oven_duration.png
                      4Dhotair: /local/oven_duration.png
                      Pizza: /local/oven_duration.png
                      Toptobottom: /local/oven_duration.png
                      Finished: /local/oven_duration.png
                      unknown: /local/oven_uit.png
                  - type: state-badge
                    entity: switch.oven_power
                    state_color: true
                    tap_action:
                      action: toggle
                    style:
                      top: 16%
                      left: 2%
                      color: white
                      transform: scale(0.9)
                      filter: drop-shadow(0px 1px 1px black)
                  - type: state-icon
                    entity: binary_sensor.oven_door
                    prefix: ' '
                    style:
                      top: 5.5%
                      left: 40%
                      font-size: 115%
                      font-weight: 375
                      max-width: 1px
                  - type: state-icon
                    entity: switch.oven_program_preheating
                    state_color: true
                    tap_action:
                      action: toggle
                    style:
                      top: '-4%'
                      left: 30%
                      transform: scale(0.9)
                  - type: state-label
                    entity: sensor.oven
                    prefix: ' '
                    style:
                      top: 6.5%
                      color: white
                      left: 60%
                      font-size: 115%
                      font-weight: 375
                      max-width: 1px
                  - type: state-label
                    entity: input_select.select_oven_program
                    suffix: ' geselecteerd'
                    state_color: true
                    tap_action:
                      action: more-info
                    style:
                      top: 84%
                      color: white
                      left: 33%
                      font-size: 110%
                      font-weight: 800
                  - type: state-label
                    entity: sensor.oven_program_progress
                    suffix: ' progress'
                    style:
                      top: 84%
                      left: 63%
                      font-size: 100%
                      font-weight: 800
                      max-width: 1px
                      color: white
                  - type: state-label
                    entity: sensor.oven_duration
                    suffix: ' remaining'
                    style:
                      top: 93%
                      left: 63%
                      font-size: 100%
                      font-weight: 800
                      max-width: 1px
                      color: white
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: sun.sun
                image: >-
                  https://cdn.knmi.nl/knmi/map/current/weather/warning/waarschuwing_land_0_new.gif
                show_state: false
                show_name: true
                name: Waarschuwingen
                tap_action:
                  action: url
                  url_path: >-
                    https://cdn.knmi.nl/knmi/map/current/weather/warning/waarschuwing_land_0_new.gif
              - type: picture
                image: https://cdn.knmi.nl/knmi/map/general/weather-map.gif
                tap_action:
                  action: url
                  url_path: https://cdn.knmi.nl/knmi/map/general/weather-map.gif
                hold_action:
                  action: none
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: sensor.buienradar_symbol
                image: >-
                  https://cdn.knmi.nl/knmi/map/page/weer/waarschuwingen_verwachtingen/zonkracht/zonkracht_dag0.gif
                show_state: true
                show_name: false
                tap_action:
                  action: url
                  url_path: >-
                    https://cdn.knmi.nl/knmi/map/page/weer/waarschuwingen_verwachtingen/zonkracht/zonkracht_dag0.gif
                name: Zonkracht
              - type: picture-entity
                entity: sun.sun
                image: >-
                  https://weerdata.weerslag.nl/image/1.0/?size=ani-8-Onweer-550x550&type=Freecontent&v=43528683"  
                  width="550" height="550
                tap_action:
                  action: url
                  url_path: >-
                    https://weerdata.weerslag.nl/image/1.0/?size=ani-8-Onweer-550x550&type=Freecontent&v=43528683"
                    width="550" height="550
                hold_action:
                  action: none
                show_state: false
                show_name: false
                aspect_ratio: '0.93'
          - type: horizontal-stack
            cards:
              - type: picture
                image: >-
                  https://weerdata.weerslag.nl/image/1.0/?size=ani-8-RadarSATEU-1000x717&type=Freecontent&v=27007686"    
                  width="1000" height="717" 
                tap_action:
                  action: url
                  url_path: >-
                    https://weerdata.weerslag.nl/image/1.0/?size=ani-8-RadarSATEU-1000x717&type=Freecontent&v=27007686"    
                    width="1000" height="717" 
                hold_action:
                  action: none
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture
                image: /local/vooruitzichten.png
                tap_action:
                  action: none
                hold_action:
                  action: none
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                state_color: false
                entities:
                  - entity: sensor.buienradar_symbol_1d
                    name: Morgen
                  - entity: sensor.langetermijn
                    name: ' '
          - type: horizontal-stack
            cards:
              - type: weather-forecast
                entity: weather.buienradar
                show_forecast: true
          - type: horizontal-stack
            cards:
              - type: glance
                title: Zonkans, wind en regen
                entities:
                  - entity: sensor.buienradar_sunchance_1d
                    name: Morgen
                  - entity: sensor.buienradar_sunchance_2d
                    name: 2d
                  - entity: sensor.buienradar_sunchance_3d
                    name: 3d
                  - entity: sensor.buienradar_sunchance_4d
                    name: 4d
                  - entity: sensor.buienradar_sunchance_5d
                    name: 5d
                show_name: true
                show_icon: false
                show_state: true
                state_color: false
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  - entity: sensor.buienradar_wind_force_1d
                  - entity: sensor.buienradar_wind_force_2d
                  - entity: sensor.buienradar_wind_force_3d
                  - entity: sensor.buienradar_wind_force_4d
                  - entity: sensor.buienradar_wind_force_5d
                  - entity: sensor.buienradar_wind_direction_1d
                  - entity: sensor.buienradar_wind_direction_2d
                  - entity: sensor.buienradar_wind_direction_3d
                  - entity: sensor.buienradar_wind_direction_4d
                  - entity: sensor.buienradar_wind_direction_5d
                  - entity: sensor.buienradar_rain_1d
                  - entity: sensor.buienradar_rain_2d
                  - entity: sensor.buienradar_rain_3d
                  - entity: sensor.buienradar_rain_4d
                  - entity: sensor.buienradar_rain_5d
                  - entity: sensor.buienradar_rainchance_1d
                  - entity: sensor.buienradar_rainchance_2d
                  - entity: sensor.buienradar_rainchance_3d
                  - entity: sensor.buienradar_rainchance_4d
                  - entity: sensor.buienradar_rainchance_5d
                show_icon: false
                show_name: false
                show_state: true
                state_color: false
```
