### ISSUE TITLE
Notifications strip out line breaks

### ISSUE THREAD

**Issue by matejdro** [home-assistant/android#1705]
**Home Assistant Android version:** 2021.9.0-full

**Android version:** 11

**Phone model:** OnePlus 7 Pro with Lineage OS

**Home Assistant version:** 2021.9.2

**Last working Home Assistant release (if known):** /

**Description of problem:**

Attempting to send multi line notification:

```yaml
service: notify.mobile_app_my_phone
data: 
  message: | 
    A line
    
    Another line
```

Will result in all line breaks being truncated on device.

If I just replace the service with `join` (with identical messages), line breaks work, so something seems to be up with mobile app (either on the server or on the phone).

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/507922/132698164-f0f92ad1-f6eb-4ebc-8b81-0e7903debc87.png)
