### ISSUE TITLE
Conflict between `alert_once` and `group` options for notifications

### ISSUE THREAD

**Issue by gazpachoking** [home-assistant/android#1754]
**Home Assistant Android version:** 2021.9.0

**Android version:** 11

**Phone model:** Pixel 5

**Home Assistant version:** 2021.10.0

**Description of problem:** The `alert_once` option for notifications does not work properly if a `group` is also specified.

**Additional information:**

Easily repeatable using developer tools to call the service:
```yaml
service: notify.mobile_app_pixel_5
data:
  message: aoeu {{range(1,99)|random}}
  data:
    # group: "aoeu"
    tag: blah
    alert_once: true
```
When uncommenting the `group` line, a sound will be played every time the notification is sent. When it's commented out, `alert_once` works properly and only plays a sound if the notification isn't already visible.
