### ISSUE TITLE
Chronometer notification with channel importance doesn't show time

### ISSUE THREAD

**Issue by Kisty** [home-assistant/android#2233]
**Home Assistant Android version:** 
beta-2000-2e0700f7-full
**Android version:**
9.0
**Phone model:**
OnePlus 3T
**Home Assistant version:**
2021.12.10
**Last working Home Assistant release (if known):**

**Description of problem:**
When I try and create a chronometer notification with high importance, it doesn't show the time remaining. Without `persistent: true` it's fine.

```yaml
service: notify.mobile_app_oneplus_a3003
data:
  title: Pomodoro
  message: Work at it!
  data:
    chronometer: true
    persistent: true
    when: '{{ as_timestamp(state_attr(''timer.pomodoro_main'', ''finishes_at'')) }}'
    tag: "pomodoro-current-timer"
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220203-104847](https://user-images.githubusercontent.com/3243752/152328729-05b6678b-9d02-4f65-9080-6914e8dd3629.jpg)
Notice no timer text to right of title

**Additional information:**
