### ISSUE TITLE
Set update interval with command_high_accuracy_mode or dedicated notification command

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#2328]
**Is your feature request related to a problem? Please describe.**
I  would like to be able to set the update interval while activating it with a notification.
Different activities and different contexts mean I don't always need the same precision.

General ideas:
- Increase incrementally the update interval as I am reaching a specific point/person.
- Use specific update intervals based on zones.
- Use specific update intervals based on detected activity in HA.

**Describe the solution you'd like**
I would like a way to set the update interval ([SETTING_HIGH_ACCURACY_MODE_UPDATE_INTERVAL](https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L49)) using a notification command, either with an additional and optional parameter of `command_high_accuracy_mode/turn_on`, or with a dedicated command if that's not possible.

```
automation:
  - alias: Turn on high accuracy mode with specified update interval
    trigger:
      ...
    action:
      - service: notify.mobile_app_<your_device_id_here>
        data:
          message: "command_high_accuracy_mode"
          title: "turn_on"
          data:
            update_interval: 60
```

I saw the code of the HighAccuracyLocationService is already [taking the interval as a parameter to start it](https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt#L43).

**Describe alternatives you've considered, if any**
Looping request_location_update commands in automation at the wanted rate based on the identified context.
Con: it relies heavily on notifications that may or may not arrive (and even more on a regular basis). ~~It counts against the rate limiting.~~

Using the expanded zones auto activation. Somehow related but not really answering my need. Limited to a specific use case.

**Additional context**
The default / random background updates are not reliable and precise enough. I think having the ability to even use update interval with "long" periods such as 15 mns and be able to remotely decrease them as low as 1 second could be really useful.
