### ISSUE TITLE
Stopping High Accuracy mode prevents following background location updates

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#2382]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
12

**Phone model:**
Galaxy S20+

**Home Assistant version:**
2022.3.5

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
I use an automation that starts High Accuracy as soon as I leave home to track movement in my city. If I leave the city (person state changes to `not_home`), I send the command to stop High Accuracy. It **stops but the location reporting will be completely frozen for hours**. Even if I use other apps that will enable and use location tracking, the app will not use this information to update the sensor. It happens with Android Auto / Waze running or not running in the car.

If I enable and disable the High Accuracy when the person is at destination, it will start working again (the background location reporting will work again). It happens each time we leave the house by car. Same behavior with 2 cars / 2 phones.

It looks like a conflict while an app is reporting location on a regular basis but stopping High Accuracy in this context would completely stop the service to update the sensor.

***Related Action***
````
conditions:
  - condition: trigger
    id: morgane_disable
  - condition: state
    entity_id: binary_sensor.telephone_morgane_high_accuracy_mode
    state: 'on'
sequence:
  - service: notify.mobile_app_telephone_morgane
    data:
      message: command_high_accuracy_mode
      data:
        ttl: 0
        priority: high
      title: turn_off
````

***Result***
```
Executed: 19 March 2022, 09:23:49
Result:
params:
  domain: notify
  service: mobile_app_telephone_morgane
  service_data:
    message: command_high_accuracy_mode
    data:
      ttl: 0
      priority: high
    title: turn_off
  target: {}
running_script: false
limit: 10
```

**Other information**
* Update frequency of sensors: 15 mns
* High Precision options:
  * No BT config
  * No specific zone config
  * Trigger zone (not used): 300 m
  * Update interval: 30 seconds
  * Minimal precision: 200 m

Ping #2102 since it could be somehow related.

I don't have the logs to share yet but I will try to get them when this happens.
