### ISSUE TITLE
Wear OS: Tile icon incorrect for template lock

### ISSUE THREAD

**Issue by Vitani** [home-assistant/android#2403]
**Home Assistant Android version:**
beta-2186-e29dc0b6-full

**Home Assistant Wear OS version:**
beta-2186-e29dc0b6

**Android version:**
12

**Phone model:**
Google Pixel 6

**Watch model:**
Mobvoi TicWatch Pro 3 Ultra GPS

**Home Assistant version:**
2022.3.7

**Last working Home Assistant release (if known):**
unknown

**Description of problem:**
Tile MDI icon for template lock is `cellphone` instead of `lock`

lock yaml -
```
lock:
  - platform: template
    name: Cabin Door
    value_template: "{{ is_state('switch.cabin_door_lock', 'on') }}"
    lock:
      service: switch.turn_on
      target:
        entity_id: switch.cabin_door_lock
    unlock:
      service: switch.turn_off
      target:
        entity_id: switch.cabin_door_lock
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
N/A

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/5907401/160118721-53e66727-5b92-4674-ab90-f2d79dde69bc.png)
![image](https://user-images.githubusercontent.com/5907401/160118942-b0a1fbed-cd88-4811-b5fb-1065d0d4c520.png)

**Additional information:**
I also have a Tuya light experiencing the same thing, so may not be limited to locks. _Perhaps_ related to the lock (and light) not having an icon specified in the entity config and using the default HA one(s)
