### ISSUE TITLE
Bluetooth sensor not showing correct lists

### ISSUE THREAD

**Issue by TheFes** [home-assistant/android#2474]
**Home Assistant Android version:**
beta-2234-6c64b31f

**Android version:**
Android 12

**Phone model:**
Pixel 5

**Home Assistant version:**
2022.4.7

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
Bluetooth Connection sensor uses strings which look like a list, but are not, it would be nice if these were actually real lists

Current state in dev-tools > state
```yaml
connected_not_paired_devices: '[14:8F:21:FD:CE:BC]'
connected_paired_devices: '[E8:07:BF:13:99:AB]'
paired_devices: >-
  [00:7C:2D:12:42:A0, FA:2C:A7:D6:EB:41, 7C:B2:7D:3B:CD:4B, E0:67:81:01:F7:D3,
  C8:55:AF:52:29:20, 62:3B:4D:94:AE:8F, D6:DA:5C:AE:66:B3, E8:07:BF:13:99:AB,
  88:B4:36:44:B7:0B, 74:E5:F9:64:FA:8B, ED:22:91:7C:BE:DF, 04:4E:AF:C6:00:32,
  60:AB:D2:3C:85:66]
unit_of_measurement: connection(s)
icon: mdi:bluetooth
friendly_name: Pixel 5 Bluetooth Connection
```

I would expect:
```yaml
connected_not_paired_devices: 
  - 14:8F:21:FD:CE:BC
connected_paired_devices: 
  - E8:07:BF:13:99:AB
paired_devices:
  - 00:7C:2D:12:42:A0
  - FA:2C:A7:D6:EB:41
  - 7C:B2:7D:3B:CD:4B
  - E0:67:81:01:F7:D3
  - C8:55:AF:52:29:20
  - 62:3B:4D:94:AE:8F
  - D6:DA:5C:AE:66:B3
  - E8:07:BF:13:99:AB
  - 88:B4:36:44:B7:0B
  - 74:E5:F9:64:FA:8B
  - ED:22:91:7C:BE:DF
  - 04:4E:AF:C6:00:32
  - 60:AB:D2:3C:85:66
unit_of_measurement: connection(s)
icon: mdi:bluetooth
friendly_name: Pixel 5 Bluetooth Connection
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/28803438/165247374-dcefe40f-0112-44b3-b6f1-850125ff1791.png)

**Additional information:**
