### ISSUE TITLE
ringing phone crash the app

### ISSUE THREAD

**Issue by fensoft** [home-assistant/android#2480]
**Home Assistant Android version: **
2022.3.0-full

**Android version: **
11

**Phone model: **
google pixel 3

**Home Assistant version: **
2022.4.6

**Description of problem:**
When running this call:
```
service: notify.mobile_app_<phone>
service_data:
  title: Finding Phone
  message: Ringing phone
  data:
    ttl: 0
    importance: high
    priority: high
    tag: Find
    channel: alarm_stream
```

It works on another phone but instantly crash the app on this one.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

Sent yesterday through android app
