### ISSUE TITLE
Is it posible to navigate from push notification to any other app menu items instead of just 'lovelace'/'dashboard' pages?

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [home-assistant/android#2489]
**Is your feature request related to a problem? Please describe.**
Push notification works fine for me, and I can navigate all of my 'lovelace'/'dashboard' pages problemless. But is it possible to navigate to any othe menu items instead of 'lovelace'/'dashoboards' pages? I send myself push notification when HACS has any updates. From the HA webapp itself, from 'lovelace'/'dashboard' cards I can simply navigate to `"/hacs"`, which definetely works, but from the Android app I can not reach that page directly from my notification.

My service call for that:
```
service: notify.{device/entity}
data:
  message: HACS update(s) available
  title: Home Assistant
  data:
    tag: ha
    actions:
      - action: "URI"
        title: "Upgrade"
        uri: "/hacs"
```

Is it a limitation? Do I miss any requirement? Is it possible maybe in the future?

Lot of thanks in advance for your efforts.

**Describe the solution you'd like**
The question itself answers the solution.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
I just tested the following 2 examples using both types of actions and I am able to navigate to `/hacs` every time.

```
service: notify.mobile_app_dannys_pixel_6_pro
data:
  message: test
  data:
    clickAction: /hacs
```

```
service: notify.mobile_app_dannys_pixel_6_pro
data:
  message: test
  data:
    actions:
    - action: URI
      title: test
      uri: /hacs
```

as long as you send a relative URL instead of a full URL that includes the domain name it should work.  You may need to try the start fresh steps if it is not working for you: https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app
