### ISSUE TITLE
Android next alarm sensor not triggering automations or Node Red time nodes at alarm time

### ISSUE THREAD

**Issue by strikeir13** [home-assistant/android#2616]
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
12, security update June 5, 2022
**Phone model:**
Pixel 6
**Home Assistant version:**
2022.6.6
**Last working Home Assistant release (if known):**
2022.6.x (it was working earlier in June)
Last working Android app version: any stable version prior to 2022.6.0-full, I updated on June 9, 2022
**Description of problem:**
The Next Alarm sensor is not triggering automations or sending any output from a Node Red time node. I have nothing selected in the Android app Next Alarm sensor Allow List. When setting a new alarm, I **can** see the correct local time value reflected in both the Developer Tools and on the Node Red time node. However, at the set time, neither the HA native automation nor the Node Red time node trigger any subsequent actions.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

**Screenshot of problem:**
Developer Tools:
![image](https://user-images.githubusercontent.com/688283/174080777-467fa81c-6618-4325-811c-0d92cb0cf038.png)
Node Red time node configured for sensor.pixel_6_next_alarm (flow directly from Node Red cookbook example)
![image](https://user-images.githubusercontent.com/688283/174080882-7e5688d2-bf25-4e2b-83f5-dc257b3212d3.png)
**Additional information:**
In the event it may be time zone related, I'm using times for US Central Time (CST) and Daylight Savings Time (DST) is currently active in my location.

**Comment by dshokouhi** [comment]
Skip node red and try a basic automation, if it still fails share the yaml and any error in the logs please.

**Comment by strikeir13** [comment]
Here's the YAML for my test automation:
```
- id: '1655385085563'
  alias: Android alarm test
  description: ''
  trigger:
  - platform: time
    at: sensor.pixel_6_next_alarm
  condition: []
  action:
  - device_id: c2afa01328e3e50d470c19dc582a8cc8
    domain: mobile_app
    type: notify
    message: The alarm went off
  mode: single
```
[homeassistant_companion_log_5-16-2022_10-14-8.txt](https://github.com/home-assistant/android/files/8920184/homeassistant_companion_log_5-16-2022_10-14-8.txt)
Attached are the logs. I trimmed the log from the point where the next alarm is first registered to roughly 1 minute after the alarm went off. At no point did the automation fire and I did not receive a notification on my phone. When testing the automation actions manually via the automation menu, the action does run and I do receive a notification on my phone.
