### ISSUE TITLE
Increase frame rate of generated notification GIFs when using video option

### ISSUE THREAD

**Issue by Rogue136198** [home-assistant/android#2655]
**Is your feature request related to a problem? Please describe.**

Currently when sending a notification to an Android device with the video atribute the framerate of the generated GIF is too low for it to be useful

**Describe the solution you'd like**

I'd like to see an option to set the FPS of the GIF being generated from the specified MP4 file. I see this as a good option as the default without fps specified can be maintained as to not create a breaking change

**Describe alternatives you've considered, if any**

I would consider any option that increases the usability of the video option in notifications. Even just increasing the default FPS would be fine by me

**Additional context**

For clarity I would expect the syntax to look something like this:

```
service: notify.notify
data:
  message: Message
  title: Title
  data:
    video: /api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
    fps: 30 <-- 
```
