### ISSUE TITLE
Android application causing IP ban on http component

### ISSUE THREAD

**Issue by molnarti** [home-assistant/android#2782]
**Home Assistant Android version:**
Home Assistant/beta-2534-90a9a27e-2534

**Android version:**
12

**Phone model:**
Redmi Note 7

**Home Assistant version:**
2022.8.2

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

- i login into the HA Mobile Companion app in my home network, and everything is working fine
- however when i move away from my home network (either on mobile data or connecting to some other Wifi APs) my app refuses to connect and i HA shows a persistent notification on IP ban.
- the same happens on my wife’s phone
- the ban is never caused by an incorrect login attempt where i would be entering my password into the app. The app is just trying to communicate with HA, should have a valid auth token but for some reason the HA server decides to ban it.

The problem started to appear approx. a month ago, previously there was no problem with the IP bans

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:82
Integration: HTTP (documentation, issues)
First occurred: August 8, 2022 at 17:08:51 (10 occurrences)
Last logged: 18:39:48

Login attempt or request with invalid authentication from 217.73.26.211 (217.73.26.211). Requested URL: '/auth/token'. (Home Assistant/beta-2534-90a9a27e-2534 (Android 12; Redmi Note 7))
Banned IP 217.73.26.211 for too many login attempts
Login attempt or request with invalid authentication from 85-237-234-47.dynamic.orange.sk (85.237.234.47). Requested URL: '/auth/token'. (Home Assistant/beta-2584-22df320f-2584 (Android 12; Redmi Note 7))
Login attempt or request with invalid authentication from 85-237-234-90.dynamic.orange.sk (85.237.234.90). Requested URL: '/auth/token'. (Home Assistant/beta-2584-22df320f-2584 (Android 12; Redmi Note 7))
```
for reference i am attaching my config.yaml section as well:

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.50.10
    - 172.18.0.0/24
  cors_allowed_origins:
    - https://homeassistant.****.***
    - https://192.168.50.10
    - http://192.168.50.10
  ip_ban_enabled: true
  login_attempts_threshold: 5
```
**Screenshot of problem:**

**Additional information:**
