### ISSUE TITLE
Huawei/EMUI: No sound when using alarm_stream_max

### ISSUE THREAD

**Issue by fensoft** [home-assistant/android#2788]
**Home Assistant Android version:**
2022.6.0-full

**Android version:**
12 / EMUI 12

**Phone model:**
Huawei Mate 20 Pro

**Home Assistant version:**
2022.8.2

**Last working Home Assistant release (if known):**
None

**Description of problem:**
No sound when using alarm_stream_max with TTS or media when phone is set to silent

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
None

**Comment by dshokouhi** [comment]
Does it work when you use `alarm_stream` for TTS? Some devices may just not support this. 

Also can you please share the logs so we can see the command coming in?

**Comment by fensoft** [comment]
```
service: notify.mobile_app_lya_l29
data:
  title: Finding Phone
  message: Ringing phone
  data:
    ttl: 0
    importance: high
    priority: high
    tag: Find
    channel: alarm_stream
```

This one works on both huawei and google pixel 3 but with a very low sound.
If I try with alarm_stream_max, i have the notification without sound.

Here is the log:
```
--------- beginning of main
08-12 15:42:05.752  6361  6361 E mpanion.androi: LoadAppImageStartupCache enabled : 1
08-12 15:42:05.754  6361  6361 E mpanion.androi: Not starting debugger since process cannot load the jdwp agent.
08-12 15:42:05.780  6361  6380 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
08-12 15:42:05.849  6361  6393 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@41e209f
08-12 15:42:51.393  6361  6361 E WebviewActivity: onReceivedHttpError: android.webkit.WebResourceResponse@566eda5
08-12 15:43:02.074  6361  6361 E HwViewGroupImpl: parse speed value length error
08-12 15:43:04.761  6361  6361 E mpanion.androi: Invalid ID 0x00000000.
```

**Comment by dshokouhi** [comment]
These logs do not show the notification coming in

**Comment by fensoft** [comment]
```
service: notify.mobile_app_lya_l29
data:
  message: "command_volume_level"
  title: 20
  data:
    channel: "notification_stream"
```

then

```
service: notify.mobile_app_lya_l29
data:
  title: Finding Phone
  message: Ringing phone
  data:
    ttl: 0
    importance: high
    priority: high
    tag: Find
    channel: alarm_stream
```

works ! but now i need to restore the initial state of the volume :)
