### ISSUE TITLE
command_activity doesn't work with 2022.08-full

### ISSUE THREAD

**Issue by jmgiaever** [home-assistant/android#2823]
**Home Assistant Android version:**
2022.08-full

**Android version:**
12

**Phone model:**
Google Pixel 6 Pro

**Home Assistant version:**
2022.8.6

**Last working Home Assistant release (if known):**
2022.6-full, I think 

**Description of problem:**
Seems like `command_activity` doesn't work anymore. I receive them as normal notifications now. 

E.g this doesn't work anymore

```
service: notify.mobile_app_...
data:
  message: command_activity
  title: "SMS:123456789?body=Predifined message here"
  data: 
    tag: "android.intent.action.SENDTO"
```

It just shows a notification. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Don't have any right now. 
```

**Screenshot of problem:**
![Screenshot_20220826-162506.png](https://user-images.githubusercontent.com/7188121/186926282-a864f5b3-a4aa-477d-8eaf-42ef731c8d86.png)

**Additional information:**
It worked flawlessly until my phone updated today.
