### ISSUE TITLE
Not playing the correct notification sound for alarm_stream

### ISSUE THREAD

**Issue by rschuiling** [home-assistant/android#2893]
**Home Assistant Android version: 20228.0-full.**

**Android version: 13**

**Phone model: Pixel 5a**

**Home Assistant version: 2022.9.4**

**Last working Home Assistant release (if known): 2022.8.x I believe but I'm not 100% sure**

**Description of problem: Sending a notification through alarm_stream does not sound the configured loud sound for that channel, but only plays the general notification sound as configured for the Home Assistant app.**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs): n/a**

**Screenshot of problem: n/a**

**Additional information:**
```
    - service: notify.mobile_app_pixel_5a
      data:
        title: "Here I am!"
        message: "Did you find me already?"
        data:
          ttl: 0
          priority: high
          media_stream: alarm_stream
```
