### ISSUE TITLE
Beacon Transmitter / Monitor - Ability to advertise and get additional attributes such as the name

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#2932]
**Is your feature request related to a problem? Please describe.**
It's possible to set a name on BlueCharm beacons. This name is retrieved by the HA Core Integration.
This information is retrieved from the `service_info.name` in the [HA Integration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/ibeacon/coordinator.py#L62).

**Describe the solution you'd like**
Would it be possible to set and broadcast this information using the mobile app? It would be more user friendly.

I am not sure about the requirements for this parameter. In Bluecharm documentation, its says "16 or less ASCII characters", but on the mobile application itself, it says "17 or less ASCII characters"

**Describe alternatives you've considered, if any**
Just use UUID / Major / Minor as the unique identifier. Rename the device and the sensors in HA, but this applies only to HA, no to other beacon scanners that could benefit from name reading.

**Additional context**
Would it be relevant to also request the retrieval of this information using the Beacon Monitor? At this stage, I don't have any idea about how this information should be retrieved. I think we are hitting the limits of the current implementation of the Beacon Monitor. I agree with the new consensus about the ID format, but how can we get additional attributes with this format in the app?

```
a92ee200-5501-11e4-916c-0800200c9a66_12555_14421: 9.94
a92ee200-5501-11e4-916c-0800200c9a66_11475_24820: 11.43
```

Today it's about the "name" but tomorrow, users could also request TLM attributes to get battery level, temperature, ADV count, time since the beacon is up... Maybe I am pushing too far for TLM since it's another protocol. Still, I think it's relevant for the name. We could also break down each part as an attribute. May I suggest to format the beacons as a list of UUID_Major_Minor with attributes?

![image](https://user-images.githubusercontent.com/6184289/193002196-06db71bd-041b-4857-8bd1-bc2560c09452.png)
(Screenshot of the KBeacon app that retrieves information from a Bluecharm beacon)

```
icon: mdi:bluetooth
friendly_name: Téléphone Julien Beacon Monitor
beacons:
- 13370000-4368-6172-6d42-6561636f6e74_1000_1001
  distance: 0
  name: Julien
  uuid: 13370000-4368-6172-6d42-6561636f6e74
  major: 1000
  minor:  1001
- 13370000-4368-6172-6d42-6561636f6e74_1000_1002
  distance: 2.4
  name: Dog
  uuid: 13370000-4368-6172-6d42-6561636f6e74
  major: 1000
  minor:  1002
```

Since we are still breaking things right now, maybe we can also change the format for something more future proof.

I could split the issues for the Beacon Monitor and Transmitter.

**Comment by dshokouhi** [comment]
Let's try not to mention too many things in the same request or parts of the request will get lost. This one has a lot going on mentioning multiple sensors and attributes and settings.

**Comment by dshokouhi** [comment]
For this request lets stick to the `name` attribute for both BLE transmitter and Beacon Monitor. Everything else needs to be separated into its own request.

> I am not sure about the requirements for this parameter. In Bluecharm documentation, its says "16 or less ASCII characters", but on the mobile application itself, it says "17 or less ASCII characters"

Most applications probably take as much as they can consume so we probably don't need to worry about this until we get a bug report if it breaks something.


> I think we are hitting the limits of the current implementation of the Beacon Monitor. I agree with the new consensus about the ID format, but how can we get additional attributes with this format in the app?

`beacon_id_<attribute>` would be a suitable format so we can do `beacon_id_name: <name>` so it can be predictable.



> Today it's about the "name" but tomorrow, users could also request TLM attributes to get battery level, temperature, ADV count, time since the beacon is up... Maybe I am pushing too far for TLM since it's another protocol.

definitely a separate request for this.

**Comment by Mincka** [comment]
If I understand correctly, your idea if to keep the current attribute format with the distance as a "default value", so we avoid breaking changes, and add new attributes like this (I add the general context so we can be sure about the attribute format):

```
icon: mdi:bluetooth
friendly_name: Téléphone Julien Beacon Monitor
13370000-4368-6172-6d42-6561636f6e74_1000_1001: 0
13370000-4368-6172-6d42-6561636f6e74_1000_1001_name: Julien
```

**Comment by dshokouhi** [comment]
> If I understand correctly, your idea is to keep the current attribute format with the distance as a "default value", so we avoid breaking changes, and add new attributes like this (I add the general context so we can be sure about the attribute format):

actually would probably also update existing attribute to include `distance` this way its predictable and understandable to anyone who sees it

at least thats my original thought

**Comment by Mincka** [comment]
Indeed, in this case it would be best to clearly state the associated attribute for the beacon.

I still like the idea of having a list of beacons grouped by their ID. It feels less messy.

```
beacons:
- 13370000-4368-6172-6d42-6561636f6e74_1000_1001
  distance: 2.4
  name: Julien
- 13370000-4368-6172-6d42-6561636f6e74_1000_1002
  distance: 0
  name: Dog
```

I saw this kind of grouping for other attributes in a few sensors, for instance, `weather`.
```
forecast: 
- datetime: '2022-09-29T18:00:00+00:00'
  condition: rainy
  temperature: 9.5
- datetime: '2022-09-29T19:00:00+00:00'
  condition: partlycloudy
  temperature: 8.6
```

However, I understand there is the problem of the breaking change, and it's less intuitive to get to the point in the automations.
`{{ state_attr('sensor.telephone_julien_beacon_monitor', 'beacons')['13370000-4368-6172-6d42-6561636f6e74_1000_1001']["name"] }}`
vs
`{{ state_attr('sensor.telephone_julien_beacon_monitor', '13370000-4368-6172-6d42-6561636f6e74_1000_1001_name') }}`
