### ISSUE TITLE
State switch card not visible from app(?) 

### ISSUE THREAD

**Issue by AlessandroTischer** [home-assistant/android#3036]
**Home Assistant Android version:** 2022.10.2

**Android version:** 12L

**Phone model:** Xiaomi mi 9T (custom rom) 

**Home Assistant version:** 2022.11.1

**Last working Home Assistant release (if known):** 2022.10.5

**Description of problem:** I have a couple of state-switch cards that change their content based on the user. Even logging in with the same user (Alessandro), those cards are visible from chrome, but not from app. Before the 2022.11.0 update, everything was fine. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

From app:
![Screenshot_20221103-214803_Home Assistant.png](https://user-images.githubusercontent.com/23379317/199831781-7883a784-de3d-44f5-b73f-f52699342147.png)

From browser:
![Screenshot_20221103-214800_Chrome.png](https://user-images.githubusercontent.com/23379317/199831857-b76ac855-35b8-449a-9d42-591444c908e2.png)

**Additional information:**
```

views:
  - theme: Mushroom
    icon: mdi:home
    badges: []
    cards:
      - type: custom:state-switch
        theme: mashrooms
        default: default
        entity: user
        states:
          Famiglia:
            type: weather-forecast
            entity: weather.openweathermap
            show_current: true
            show_forecast: true
            theme: Mushroom
          default:
            type: custom:weather-card
            entity: weather.openweathermap
            current: true
            details: false
            forecast: true
            number_of_forecasts: '5'
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: ''
            secondary: Accessi
            icon: mdi:lock
            layout: vertical
            icon_color: grey
            double_tap_action:
              action: none
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/accessi
            hold_action:
              action: none
          - type: custom:mushroom-template-card
            primary: Riscaldamento
            secondary: ''
            icon: mdi:heating-coil
            layout: vertical
            icon_color: red
            hold_action:
              action: none
            double_tap_action:
              action: none
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/riscaldamento
          - type: custom:mushroom-template-card
            primary: Condizionatori
            secondary: ''
            icon: mdi:air-conditioner
            layout: vertical
            icon_color: blue
            fill_container: true
            badge_icon: ''
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/condizionatori
            hold_action:
              action: none
            double_tap_action:
              action: none
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: Videocamere
            secondary: ''
            icon: mdi:cctv
            layout: vertical
            icon_color: purple
            fill_container: true
            badge_icon: ''
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/videocamere
            hold_action:
              action: none
            double_tap_action:
              action: none
          - type: custom:mushroom-template-card
            primary: Termometri
            secondary: ''
            icon: mdi:food-turkey
            layout: vertical
            icon_color: orange
            hold_action:
              action: none
            double_tap_action:
              action: none
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/termometri
          - type: custom:mushroom-template-card
            primary: Giardino
            secondary: ''
            icon: mdi:flower
            layout: vertical
            icon_color: green
            double_tap_action:
              action: none
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/giardino
            hold_action:
              action: none
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: Lista della Spesa
            secondary: ''
            icon: mdi:cart-check
            layout: vertical
            icon_color: teal
            hold_action:
              action: call-service
              service: shopping_list.bring_sync
              data: {}
              target: {}
            double_tap_action:
              action: none
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/lista-della-spesa
            multiline_secondary: false
          - type: custom:mushroom-template-card
            primary: Aspirapolvere
            secondary: ''
            icon: mdi:robot-vacuum
            layout: vertical
            icon_color: brown
            fill_container: true
            badge_icon: ''
            tap_action:
              action: navigate
              navigation_path: /lovelace-mobile/aspirapolvere
            hold_action:
              action: none
            double_tap_action:
              action: none
          - type: custom:mushroom-template-card
            primary: Consumi
            secondary: ''
            icon: mdi:speedometer
            layout: vertical
            icon_color: yellow
            double_tap_action:
              action: none
            tap_action:
              action: navigate
              navigation_path: /energy
            hold_action:
              action: navigate
              navigation_path: /lovelace-mobile/consumi
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: CentroAnch'io
            secondary: ''
            icon: mdi:briefcase
            layout: vertical
            icon_color: none
            fill_container: true
            badge_icon: ''
            tap_action:
              action: navigate
              navigation_path: /lovelace-centroanchio
            hold_action:
              action: none
            double_tap_action:
              action: none
          - type: custom:mushroom-template-card
            primary: Predaia
            secondary: ''
            icon: mdi:image-filter-hdr
            layout: vertical
            icon_color: none
            fill_container: true
            badge_icon: ''
            tap_action:
              action: navigate
              navigation_path: /lovelace-predaia
            hold_action:
              action: none
            double_tap_action:
              action: none
          - type: custom:state-switch
            theme: mashrooms
            entity: user
            states:
              Alessandro:
                type: custom:mushroom-template-card
                primary: Privato
                secondary: ''
                icon: mdi:shield-account
                layout: vertical
                icon_color: none
                fill_container: true
                badge_icon: ''
                tap_action:
                  action: navigate
                  navigation_path: /lovelace-mobile/privato
                hold_action:
                  action: none
                double_tap_action:
                  action: none
              default:
                type: markdown content:> Altro Utente

title: Casa


```
