### ISSUE TITLE
NFC tag scanned event doesn’t provide a valid device_id on android

### ISSUE THREAD

**Issue by heligan** [home-assistant/android#3063]
**Home Assistant Android version:**
2022.10.2-full

**Android version:**
12

**Phone model:**
OnePlus 8T

**Home Assistant version:**
2022.10.5

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

`device_id` in the `tag_triggered` event only has first 16 chars while the actual `device_id`s in HA are 32 chars.

Check details in my questions:
https://community.home-assistant.io/t/nfc-tag-scanned-event-doesnt-provide-a-valid-device-id-on-android/487338

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

To reproduce this, I have an automation like this

```
alias: Test nfc tag
trigger:
  - platform: event
    event_type: tag_scanned
    event_data:
      tag_id: <actual tag id>
action:
  - service: input_text.set_value
    data:
      value: |
        {{ trigger.event.data.device_id }}
    target:
      entity_id: input_text.used_by
```

the `device_id` is stored in this `input_text.used_by` helper. I can only see the first 16 chars of the device id.

I wanted to pass this `input_text.used_by` to some other automation scripts that use `device_id` but since this is trimmed, those would tell me my `device_id` is invalid.

**Comment by dshokouhi** [comment]
can you do me a favor and also post the event text you receive? I don't think the app itself is firing this event, rather we are just notifying HA core that we have scanned a tag and we pass along its ID.

https://github.com/home-assistant/android/blob/8ce64f5ed6a004101edb94681458682d832a71ed/app/src/main/java/io/homeassistant/companion/android/nfc/NfcViewModel.kt#L105-L107

**Comment by heligan** [comment]
Hi Daniel,

Thanks for checking.

The text I got from the tag_triggered event looks like this:

```
{'tag_id': 'a2ee967a-cd00-4fca-b52f-b7afaf47c274', 'device_id': '2f....'}
```

this is part of the `trigger.event.data`. Not sure where this `device_id` is set in the app code though. Is this what you are looking for?

I tried `trigger.event` but it might have an incomplete `__rep__`, it shows something similar

```
<Event tag_scanned[L]: tag_id=a2ee967a-cd00-4fca-b52f-b7afaf47c274, device_id=2f....>
```

Are you suggesting HA core fill the `device_id` in by itself? Perhaps I am looking at the wrong place

https://github.com/home-assistant/core/blob/dev/homeassistant/components/tag/trigger.py

**Comment by heligan** [comment]
So looks like a HA core issue?

```
2022-11-14 11:40:08.618 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from ... for type scan_tag: {'tag_id': 'a2ee967a-cd00-4fca-b52f-b7afaf47c274'}
```

indeed, no `device_id` is passed

**Comment by dshokouhi** [comment]
Yup not sure from where though because the `mobile_app` integration is sending whats stored in the config entry

https://github.com/home-assistant/core/blob/dev/homeassistant/components/mobile_app/webhook.py#L687

**Comment by heligan** [comment]
I decided to have a try using the templating magic but really frustrated with the finding. The first trial seems to be showing something in the Developer Tool -> template page

```
{%- for e in expand(states.device_tracker) -%}
   {%- set did = device_id(e.entity_id) -%}
   {{ did if did is match('2f...') else '' }}
{% endfor %}
```

I hard coded the first 16-chars and this renders the full `device_id` on the right hand side of the page. So I copied this into an automation rule

```
trigger:
  - platform: tag
    tag_id: a2ee967a-cd00-4fca-b52f-b7afaf47c274
variables:
  actual_device_id: |-
    {%- for e in expand(states.device_tracker) -%}
      {%- set did = device_id(e.entity_id) -%}
      {{ did if did is match(trigger.event.data.device_id) else '' }}
    {% endfor %}
action:
  - service: input_text.set_value
    data:
      value: |
        {{ actual_device_id }}
    target:
      entity_id: input_text.washing_machine_used_by
  - device_id: |
      {{ actual_device_id }}
    domain: mobile_app
    type: notify
    message: verified ok
mode: single
```

I was hoping this `actual_device_id` would just work like it should in the template page but from the trace, I can see it's just an empty string. Weird enough I tried a few things, e.g. setting it to `trigger.event.data.device_id`, I got the 16-char version back, setting it to just `did` without `if else`, I got all devices ids back (including the matched one).

Is this thing so fragile and hard to work with?

**Comment by heligan** [comment]
OK, now I have a better idea. It seems the id from `trigger.event.data.device_id` is not the actual device id (of the mobile phone). It's some other id, like webhook id. Unfortunately in my case both start with `2f...` and look very similar. So that means the mobile_app webhook didn't do the translation correctly (it should get the `device_id` instead of `webhook_id` and set it into the event data).

**Comment by heligan** [comment]
So I made a last resort after quite some weird failures

from the `webhook_id` to `device_id`, one can leverage a variable defined like this
```
trigger:
  - platform: tag
    tag_id: a2ee967a-cd00-4fca-b52f-b7afaf47c274
    variables:
      actual_device_id: >
        {%- set v = trigger.event.data.device_id -%}
        {%- set all_device_ids = states.device_tracker|map(attribute="entity_id")|map("device_id") -%}
        {%- for device_id in all_device_ids -%}
          {%- set webhook_id = device_attr(device_id, 'identifiers')|first|last|string -%}
          {{ device_id if v == webhook_id else '' }}
        {%- endfor -%}
      device_name: >
        mobile_app_{{ device_attr(actual_device_id, 'name')|slugify }}
```

This `actual_device_id` has the thing I was looking for. I was thinking to put it in something like

```
action:
  - device_id: "{{ actual_device_id }}"
    domain: mobile_app
    type: notify
    message: Notification text
```

But it doesn't work (reporting an error saying "cannot get webhook id from device id", but if I put the actual device id there, this action just works, so perhaps `device_id` doesn't support templating?). But if one use the `device_name` variable

```
            - service: "notify.{{ device_name }}"
              data:
                message: Test message.
```

It just works.
