### ISSUE TITLE
Allow clickAction to be used as a regular action to send back events

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#3134]
**Is your feature request related to a problem? Please describe.**
I would like `clickAction` to behave as an independent action. More precisely, I would like to be able to send back an event to HA on notification click. In this case, the notification would not open anything, just send back an event and disappear. It would allow `clickAction` to be used as a "default" action or a workaround to use up to 4 actions using the same notification (`clickAction` and the 3 other actions). 

**Describe the solution you'd like**
Inspired from `entityId:<entity_ID>`, interpret `event:` as a special `clickAction`, like `event:<event_identifier>`.

```
service: notify.mobile_app_<your_device_id_here>
data:
  title: "Motion Detected in Backyard"
  message: "Someone might be in the backyard."
  data:
    # Taping the notification send back the event, in this case, the same event as the first action button
    clickAction: "event:ALARM"
    actions:
      - action: "ALARM"
        title: "Sound Alarm" 
      - action: "URI" 
        title: "Open Url"
        uri: "https://google.com"
```

It would also open the possibility to do other things like "Dead man's switch", or request one or multiple people to trigger an automation quickly, just by tapping it.

A more global approach would be to be able to log an event for all the clickAction, this could be useful when dealing with notifications sent to multiple devices. As seen in this [question](https://community.home-assistant.io/t/automation-using-clickaction-as-a-trigger/413323).

**Describe alternatives you've considered, if any**
Using things like `Notification Cleared` is not possible since it is not sent when a notification is clicked, only swiped away or cleared in batch. I could use `persistent` and `sticky` to prevent the notification to be closed and force the user to select one of the actions to be able to dismiss the notification. I also tried to avoid opening anything by opening the launcher with `clickAction: app://com.sec.android.app.launcher` but it opens the info page of the app... Another possibility would be to open a URL for the webhook, but that's [not yet possible](https://github.com/home-assistant/core/pull/56446), or using a proxy server to change the GET as a HEAD or POST, but still, it would open the browser to an empty page.

**Additional context**
The creation of this issue was suggested by Daniel [here](https://community.home-assistant.io/t/notification-actions/359113/7).
