### ISSUE TITLE
Android Actionable Notification Button not created

### ISSUE THREAD

**Issue by HobboRobin** [home-assistant/android#3147]
**Home Assistant Android version:**

2022.11.0-full

**Android version:**

13

**Phone model:**

Samsung Galaxy S22 Ultra 5g

**Home Assistant version:**

2022.12.0
Supervisor 2022.11.2

**Last working Home Assistant release (if known):**

Not known exactly (Last tested around 1year ago with different phone too

**Description of problem:**

I try to get the Actionable Notification working on my phone and also on the other phones in my family. I am normaly using nodeRed for the Notify system but i tried it also with the YAML Service to send the Code manually. I get the Notification (See the Example) But there are no buttons showing up. I think i just missed something but i dont find it. I looked also at the other Forums and on the Manuel but i dont find the solution there.
I just copy here now the Basic Message to not overload Github :D
I tried this also so nothing is showing with a button.

service: notify.mobile_app_app_handy_robin
data:
  title: Robin Wohnzimmer
  message: Heizung wurde auf Solltemperatur (XY) gesetzt.
  data:
    data:
      group: Heizung
      channel: Heizung
      data:
        actions:
          - action: ROBIN_WOHNZIMMER_HEIZUNG
            title: Manuell
          - action: AUTOMATIK
            title: Automatik

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
You've added a lot of `data:` lines which aren't necessary, it should only be one like this:

```yaml
service: notify.mobile_app_app_handy_robin
data:
  title: Robin Wohnzimmer
  message: Heizung wurde auf Solltemperatur (XY) gesetzt.
  data:
    group: Heizung
    channel: Heizung
    actions:
      - action: ROBIN_WOHNZIMMER_HEIZUNG
        title: Manuell
      - action: AUTOMATIK
        title: Automatik
```

([the docs include a basic example](https://companion.home-assistant.io/docs/notifications/actionable-notifications#building-actionable-notifications))
