### ISSUE TITLE
Replied Persistent Notification Not Cleared

### ISSUE THREAD

**Issue by amosyuen** [home-assistant/android#3150]
**Home Assistant Android version:** 2022.11.0-full

**Android version:** 13

**Phone model:** Pixel 6

**Home Assistant version:** 2022.12.4

**Last working Home Assistant release (if known):**

**Description of problem:** Can not clear a persistent notification that has been replied. After replying there is a spinning loading symbol seemingly indefinitely. Then When I call clear_notification that symbol disappears and the reply shows inline. Calling clear_notification a second time does not do anything.

Call to create notification:
```yaml
service: notify.mobile_app_amos_phone
data:
  message: Alarm
  data:
    tag: alarm
    persistent: true
    sticky: true
    actions:
      - action: REPLY
        title: Disarm with Pin
```

Call to clear notification:
```yaml
service: notify.mobile_app_amos_phone
data:
  message: clear_notification
  data:
    tag: alarm
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
12-13 23:10:31.934 32095 32111 E BLASTBufferQueue: [VRI[SettingsActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
12-13 23:10:36.687 32095 32420 W FirebaseMessaging: Unable to log event: analytics library is missing
12-13 23:10:36.687 32095 32420 D FCMService: From: 331041709873
12-13 23:10:36.689 32095 32095 D MessagingService: Creating notification with following data: {sticky=true, tag=alarm, persistent=true, message=Alarm, action_1_title=Disarm with Pin, action_1_key=REPLY}
12-13 23:10:36.693 32095 32095 D MessagingService: Show notification with tag "alarm" and id "92895825"

...

12-13 23:10:51.274 32095 32129 E BLASTBufferQueue: [VRI[WebViewActivity]#3](f:0,a:4) Faking releaseBufferCallback from transactionCompleteCallback
12-13 23:10:51.280 32095 32125 D NotifManagerCompat: Cancel notification with tag "null" and id "-1"
12-13 23:10:51.281 32095 32125 D NotifManagerCompat: Check if the notification is in a group...
12-13 23:10:51.281 32095 32125 D NotifManagerCompat: Notification is not in a group. Cancel notification...
12-13 23:10:51.292 32095 32129 E BLASTBufferQueue: [VRI[WebViewActivity]#3](f:0,a:4) Faking releaseBufferCallback from transactionCompleteCallback
```

**Screenshot of problem:**

After submitting reply
![image](https://user-images.githubusercontent.com/422794/207530012-6dc97e34-b13e-41b1-93fb-80c031ed34ec.png)

After sending clear_notification
![image](https://user-images.githubusercontent.com/422794/207530034-971e2602-edd9-4991-8a5a-1053c93492ee.png)

**Additional information:**

If I have not replied to the notification, clearing works correctly.

Also if I send a new notification with the same tag it is replaced correctly.
