### ISSUE TITLE
Automation/actions/change preset/preset_mode not displayed

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [home-assistant/android#3175]
Considering the companion app version 2022.11.0-full and the following code:

```
alias: Resume heating when J's door is closed
description: ""
trigger:
  - type: not_opened
    platform: device
    device_id: ...
    entity_id: binary_sensor.j_s_door_door
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - device_id: ...
    domain: climate
    entity_id: climate.j_s_radiator
    type: set_preset_mode
    preset_mode: Used
mode: single
```
The preset is not displayed in the UI:

![Screenshot_20221225-224500](https://user-images.githubusercontent.com/5151122/209482870-9b26e683-cfb5-45b1-bf9f-c26add7b049e.png)

There is no data loss in case it is then saved from the UI editor.
