### ISSUE TITLE
Display notification on top of other notifications

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/android#3208]
**Is your feature request related to a problem? Please describe.**

I'm trying to create a notification like _Doorbell is ringing_. I'm currently using:

```yaml
clickAction: /lovelace/video-porteiro
group: video-porteiro-chamando
tag: video-porteiro-chamando
channel: Video Porteiro
importance: high
priority: high
ttl: 0
vibrationPattern: 1000, 100, 1000, 100, 1000, 100
persistent: true
timeout: 120
visibility: public
image: /api/camera_proxy/camera.video_porteiro
actions:
  - action: URI
    title: Atender
    uri: /lovelace/default_view?call=888
  - action: IGNORE
    title: Ignorar
```

But this causes the notification to be displayed on the middle of my other notifications of other apps like WhatsApp and Telegram.

**Describe the solution you'd like**

Some way to make the notification be displayed on the top of the list. Maybe some sort of _Call_ flagging can be used for the purpose?

**Describe alternatives you've considered, if any**

I did not find any.

**Additional context**

None.
