### ISSUE TITLE
Wear OS notification_icon not working

### ISSUE THREAD

**Issue by seanmccabe** [home-assistant/android#3323]
**Home Assistant Android app version(s):**
Unknown - no option in Wear OS app to show version. - Perhaps add as text at bottom of the settings page.

**Android version(s):**
Wear OS 3.5

**Device model(s):**
Galaxy Watch 5

**Home Assistant version:**
2023.1.7

**Last working Home Assistant release (if known):**
Unknown

**Description of problem, include YAML if issue is related to notifications:**
Adding the _notification_icon_ option as per the [docs ](https://companion.home-assistant.io/docs/wear-os/#notifications) does not work.
The service fires, but there is no change in notification icon on the watch, still shows the Home Assistant icon.

**Comment by dshokouhi** [comment]
Please share the YAML that you used. On my end it is working

```
service: notify.mobile_app_dannys_pixel_watch
data:
  message: test
  data:
    ttl: 0
    priority: high
    notification_icon: "mdi:fire"
```

![image](https://user-images.githubusercontent.com/1634145/217714163-34a0f9bd-9267-4dd0-b4ba-7f8641770a60.png)

**Comment by seanmccabe** [comment]
```
service: notify.mobile_app_galaxy_watch5_alvh
data:
  title: "Phone Disconnected"
  message: "Phone has been disconnected"
  data:
    notification_icon: "mdi:fire"
    tag: "notification"
```

![20230209_190556](https://user-images.githubusercontent.com/12243212/217731879-8e49c8c2-8b42-43b9-add0-660065c7076d.jpg)

**Comment by seanmccabe** [comment]
If I also use the exact example from the docs but change it to my device, same.

```
service: notify.mobile_app_galaxy_watch5_alvh
data:
  message: "Notification message"
  title: "Notification title"
  data:
   notification_icon: "mdi:fire"
   tag: "notification"
```
