### ISSUE TITLE
vertical slider-button-card inside App not working properly

### ISSUE THREAD

**Issue by Datensammler** [home-assistant/android#3326]
**Home Assistant Android app version(s):**
2023.1.1-full

**Android version(s):**
9 (for S8) respectively 12 (for M21)

**Device model(s):**
Samsung Galaxy M21
Samsung Galaxy S8

**Home Assistant version:**
Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0
 
**Last working Home Assistant release (if known):**
unknown, but there were setups in the past where the virtical slider worked properly

**Description of problem, include YAML if issue is related to notifications:**
The issue is with the [**slider-button-card V1.10.10**](https://github.com/custom-cards/slider-button-card/releases) when the slider is configured as vertical from top to bottom or bottom to top.

Tapping onto the slider and moving directly up or down lets the slider jump to its former position. Wiping first to the side after tapping and subsequently up or down the slider is working properly. This issue appers only within the app and not inside any browser on the same device.

![2023-02-09_20h50_42](https://user-images.githubusercontent.com/114442038/217935285-d4be01c2-1ab4-4f33-a542-af36af40380b.jpg)

some YAML code:
```
type: custom:slider-button-card
entity: light.test_birne
slider:
  direction: top-bottom
  background: solid
  use_state_color: true
show_name: true
show_state: true
compact: false
action_button:
  mode: toggle
  icon: mdi:power
  show: false
  show_spinner: false
  tap_action:
    action: toggle
name: Terrasse

```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
