### ISSUE TITLE
Actionable Notifications on Android do not follow the "no action taken" URL

### ISSUE THREAD

**Issue by mhlas7** [home-assistant/android#3422]
**Home Assistant Android app version(s):**
2023.1.1-full
**Android version(s):**
13
Security update: March 5
Google Play update: Feb 1
**Device model(s):**
Google Pixel 5
**Home Assistant version:**
2023.3.4
**Last working Home Assistant release (if known):**
Unknown
**Description of problem, include YAML if issue is related to notifications:**
I have an actionable notification which I want to direct me to a lovelace page when clicked. The action URI button works as expected and opens the specified page when clicked. However when I tap on the main part of the notification, it brings me to my default dashboard instead of the URL I have specified under the data field. I have the exact same syntax sending a notification to an iOS device and this syntax opens the correct lovelace page when clicked. This feature is barely mentioned in the documentation and I am wondering if this is a bug or a deprecated feature (See: [Actionable Notifications: Migrating from Categories](https://companion.home-assistant.io/docs/notifications/actionable-notifications/#migrating-from-categories) and look under the #replacement comment in the code).

Is this simply an Android bug? Should the documentation be updated?

Here is my notification action:
```
service: notify.mobile_app_pixel_5
data:
  title: Todays Mail and Packages
  message: "Here is today's mail"
  data:
    url: /lovelace/mail
    actions:
      - action: URI
        title: Mail
        uri: /lovelace/mail
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
