### ISSUE TITLE
Edge Swipe Not Working

### ISSUE THREAD

**Issue by breakthestatic** [home-assistant/android#3460]
**Home Assistant Android app version(s):**
2023.3.0-full

**Android version(s):**
Android 13 (OneUI 5.1)

**Device model(s):**
Samsung Galaxy S20

**Home Assistant version:**
2023.4

**Last working Home Assistant release (if known):**
2023.3

**Description of problem, include YAML if issue is related to notifications:**
Not very familiar with the background reasoning, but it appears that control of the sidebar needs to be moved over to the companion apps (see https://github.com/home-assistant/iOS/pull/2328 for the iOS-specific work). I looked around the issues and PRs but didn't see any work slated to re-add the gesture on Android.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
What happens in Chrome for Android? Do you see the same issue there?

**Comment by cdonovan** [comment]
Chrome on Android has its own edge swipe gesture which navigates back in history. Perhaps that's related to the original reason for the removal?

**Comment by breakthestatic** [comment]
Chrome on Android has its own edge swipe gesture which navigates back in history. Perhaps that's related to the original reason for the removal?

**Comment by breakthestatic** [comment]
> Isn't that just the default Android back gesture? (available in any app)

No, there's two separate (but potentially competing) gestures.

I use dedicated navigation buttons (separate back, home & recents), but Chrome *specifically* has its own left edge swipe that navigates back a page in the browser history, **not** backwards through the OS app history.

As noted above, there is **also** the OS-level gesture navigation, which repalces the 3 dedicated buttons with a single bar (similar to iOS). In that paradigm, edge swipes perform an OS-controlled navigation even backwards through the app history (there's also some current work in Android to make the back behavior more intelligent using so AI stuff (https://www.androidpolice.com/android-14-gesture-navigation-predictive-back-excited/, but I think that is a bit tangential).

When I was experimenting with the gesture navigation in the past, even though edge swipe was controlled by the OS, you could still trigger the hamburger expansion by holding the left edge for a moment before actually swiping.

**Comment by jpelgrom** [comment]
Relabeling this as a feature request because removal from the frontend was intentional.

Adding a gesture to the app could restore some of the functionality, but it won't exactly match the old behavior because of the split between frontend and app. Also related: #2180 (which is 10x harder because of the drawer's complexity).

**Comment by pergolafabio** [comment]
Is this feature coming back? I can't go to the menu anymore on companion app, cause I have kiosk mode Running (no title bar)
Thnx

**Comment by Claudio1L** [comment]
Huge limitation for kiosk mode

**Comment by sanderlv** [comment]
I instantly noticed this. Now I cannot get my menu back easily in app.

**Comment by danni-storm** [comment]
@jpelgrom This is a critical feature that all but one of my devices relied on and family members are getting frustrated with. Was this removal planned? I can rework my frontend but I didn't see anything on the breaking changes for 2023.4. If it was I would have waited to update. I can always roll back but I won't have time to do that for at least a couple of weeks - work is insane.

**Comment by jpelgrom** [comment]
I don't know if it was planned or simply merged because it was ready, I don't work on the frontend. Agree it would have been nice if it was listed in the breaking changes. The related change has taken 1.5 years with long periods of inactivity; home-assistant/frontend#10335.

**Comment by scstraus** [comment]
I'm having this issue on iOS too. I don't like the cluttered navigation bar so I got rid of the icons a-la kiosk mode with card-mod themes, but used swipe to access the sidebar on mobile. This feature really needs to come back.

**Comment by Royrdan** [comment]
I managed to get the sidebar to show via browser_mod.javascript service call.
Just add this to a button or an element on your frontend and when clicked it will show the sidebar.
There may be a more elegant way of doing this but it works.

```
tap_action:
      action: call-service
      service: browser_mod.javascript
      service_data:
        code: "document.querySelector('body > home-assistant').shadowRoot.querySelector('home-assistant-main').dispatchEvent(new CustomEvent('hass-toggle-menu', {detail: {open: true}}))"
```

**Comment by panhans** [comment]
Nope, updated to current HA version, cleared app cache and start the app. It still doesn't work.

**Comment by Claudio1L** [comment]
I’m sorry, I’m verifying on IOS, not android. Sorry about that.
On iOS seems solved

**Comment by N1029676** [comment]
This is a frustrating change considering the button to open the sidebar is the furthest position from where my thumb is.

**Comment by Drealine** [comment]
Same problem here using Android APP.

**Comment by xelemorf** [comment]
I can live without the swipe feature missing, but the back button on the top does not work at all. 
Basically there is no native way to get back to the sidebar, essentially losing functionality.

**Comment by xelemorf** [comment]
I was missing some of the basics on how to reproduce this solution, so after figuring out the missing steps posting this for other newbies like me here is a script for reference; once script is created just add it to dashboard:

```
alias: HA Show Sidebar
sequence:
  - service: browser_mod.javascript
    data:
      code: >-
        document.querySelector('body >
        home-assistant').shadowRoot.querySelector('home-assistant-main').dispatchEvent(new
        CustomEvent('hass-toggle-menu', {detail: {open: true}}));
mode: single
icon: phu:playback-button
```
