### ISSUE TITLE
Problem with video in notify

### ISSUE THREAD

**Issue by Henrik1986** [home-assistant/android#3470]
I want to attach a video in a message. I use this code to create a video when the front door opens and the alarm is on.

```
  - service: camera.record
    target:
      entity_id: "camera.grovkok"
    data:
      filename: '/media/cctv_grovkok/video.mp4'
      duration: 30
```
That works perfect and I get a video when I trigger it. Then I use this code to send the video to my android phone. I have a delay so the video will stored.

```
  - delay:
      seconds: 59
  - service: notify.mobile_app_pixel_6_pro
    data:
      message: Någon kom in
      data:
        url: "/lovelace/camera"
        priority: high
        video: '/media/local/cctv_grovkok/video.mp4'
```

I get the message but no video. The logg shows this.

```
04-10 18:22:55.647 10826 10826 D MessagingService: Found 0 frames for video notification
04-10 18:22:55.650 10826 10826 D MessagingService: Show notification with tag "null" and id "1811561647"
```

If I [convert the video on the internet](https://video-converter.com/) and put I back in the same folder and trigger the automation I get the video in the message. I converted the file from mp4 to mp4. Logg show this. 

```
04-10 18:47:57.030 10826 10826 D MessagingService: Found 19 frames for video notification
04-10 18:47:57.064 10826 10826 D MessagingService: Show notification with tag "null" and id "1812946270"
```

**Comment by dshokouhi** [comment]
Please do not delete the issue template, all requested information is required to help you out. Please restore the template and fill out all requested data.

**Comment by Henrik1986** [comment]
Done!

**Comment by dshokouhi** [comment]
Thanks are you by chance able to attach example videos of one working and the other that is not? That will be helpful in troubleshooting the issue.

**Comment by javiromero** [comment]
Experiencing the same issue described in the ticket: video file generated using `camera.record` service and pushed using `notify` service. Both from Reolink cameras (different models though)

Sharing two video files in case it helps debugging the problem
1st https://user-images.githubusercontent.com/385944/232748877-688d0188-418c-4e3c-b7c4-6328677ef4bb.mp4

2nd https://user-images.githubusercontent.com/385944/232748884-bdc430cd-aec6-4b72-8841-095b954a61db.mp4

**Comment by willhaggan** [comment]
is it something top do with the frame rate? I have came across the same problem from a tapo camera recording

**Comment by Ceralor** [comment]
Chiming in that I'm having the same issue. Likewise, zero frames in the app log. FFProbe shows:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '\\homeassistant.local\media\front_door\clip.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso6iso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:00:16.60, start: 0.000000, bitrate: 1007 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360, 1004 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

**Comment by jpelgrom** [comment]
Testing with the bugged recording that was provided, logs suggest metadata is missing or cannot be parsed by Android. One item specifically reads:

```
2023-05-16 19:58:09.003  1287-2613  MPEG4Extractor          media.extractor                      E  No width or height, assuming worst case 1080p
```

Video duration as extracted is 0ms, which is why it isn't adding any video frames to the notification. When I edit the code to hardcode a >0 duration, it is able to extract the first frame, but not any later frames.

The only major difference in your output appears to be that `compatible_brands` includes `iso6`.

If Android's metadata retriever returns that it is unable to get the duration, the app will use a 'backup duration' of 7 seconds and try to get at least a few frames. Would that be reasonable to use if the duration is 0 as well? (to display one frame instead of nothing)

**Comment by Henrik1986** [comment]
Some progress? @dshokouhi

**Comment by dshokouhi** [comment]
> Some progress? @dshokouhi 

Please don't tag people asking for updates

**Comment by ReX1983** [comment]
Is this still an issue? Found the same problem with the Reolink Doorbell (the video is recorded but it is not displayed in the notification).

**Comment by zagielek** [comment]
I've just notice the same issue with my TP Link tapo camera. I'm unable to send the video in notification. I'm able to send an snapshot without issues ( using path image: '/local/snapshots/testsnapshot.jpg' )
When I download the /config/www/snapshots/testvideo.mp4 from home assistant to my PC, I can play it without issues. 

Tapo C320WS f/w: 1.1.6

Home Assistant: 
- Core: 2023.12.3
- Supervisor: 2023.11.6
- Operating System: 11.2

HACS: 1.33.0
Tapo: Cameras Control: 5.4.12


```
- alias: test_video_notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.test6
      to: "on"
  action:
    - service: camera.record
      data:
        entity_id: camera.tpcam_hd_stream
        filename: "/config/www/snapshots/testvideo.mp4"
        duration: 5
        #lookback: 3
    - service: notify.mobile_app_1
      data:
        message: "Test message"
        data:
          video: /local/snapshots/testvideo.mp4
          notification_icon: mdi:bell-alert
          sticky: 'true'
    - service: input_boolean.turn_off
      entity_id: input_boolean.test6
```
      
      
```
$ ffprobe testvideo.mp4 
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'testvideo.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso6iso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:05.38, start: 0.000000, bitrate: 213 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc), 2560x1440, 210 kb/s, 15.05 fps, 20 tbr, 90k tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

**Comment by creeve4** [comment]
I am also experiencing this issue.

Home Assistant Android app version(s):
2023.12.4-full

Android version(s):
11

Device model(s):
Pixel 4a

Home Assistant version:
Home Assistant 2023.12.4


I am using the Reolink Video Doorbell Wifi to record the video.
I am not seeing anything in the companion app logs. If I re-encode the original video with ffmpeg and then send it, it works correctly.


Below is my automation:
```
alias: Doorbell Motion Video
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbell_person
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
action:
  - service: camera.record
    target:
      device_id: []
      area_id: []
      entity_id: camera.doorbell_fluent
    data:
      filename: /config/www/tmp/video.mp4
      lookback: 3
      duration: 7
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.mobile_app_chris
    data:
      message: Front door {{ now().strftime('%-I:%M %p') }}
      title: Motion Detected
      data:
        channel: Doorbell
        importance: max
        group: Doorbell
        video: /local/tmp/video.mp4
        ttl: 0
        priority: high
        clickAction: noAction
mode: single
```

**Comment by deezid** [comment]
Same here, no video shown in messages on Android. The converted video via ffmpeg sends perfectly fine though... Weird.

**Comment by m90att** [comment]
Same here

**Comment by xandervanerven** [comment]
After some time and experimentation, I successfully created a working automation to generate an animated GIF (video notification) from an MP4 video and display it on an Android Pixel phone using the Home Assistant app

See this integration info:
https://www.home-assistant.io/integrations/ffmpeg/
Note: This integration supports all FFmpeg versions since 3.0.0. If you run the Home Assistant Operating System or use the Home Assistant Container, this is already pre-installed for you. In all other cases, make sure you have FFmpeg installed on your system.

Add the folowing to your configuration.yaml :

```
#Activate FFmpeg integration in Home Assistant
ffmpeg:

#Convert Reolink Doorbell mp4 recording to pixel compatible mp4, we will use this in an automation
shell_command:
  convert_video: "ffmpeg -y -i /media/reolink/person.mp4 -c:v libx264 -preset ultrafast -tune zerolatency /media/reolink/converted_person.mp4"
```


After adding this, save the configuration file and restart Home Assistant

Create an automation like this

1. Person Detection Trigger:
The automation starts when the doorbell detects a person.
2. Snapshot Capture:
It takes a quick snapshot from the doorbell camera (snapshot is fast).
3. First Notification:
Sends a notification to your phone with the snapshot (fast picture preview) + buttons to open the Reolink app (live view) or Synology app (playback).
4. Video Recording and Conversion:
Then, it records a short video clip and converts it to a format compatible with Android Pixel devices.
5. Second Notification:
Once the video is ready, it sends a second notification with the converted video, replacing the initial snapshot (replaced because it uses the same notification tag).

```
description: "Reolink doorbell frontdoor video notification"
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.reolink_doorbell_person
    to: "on"
conditions: []
actions:
  - action: camera.snapshot
    metadata: {}
    data: {}
    target:
      entity_id: camera.reolink_doorbell
  - action: notify.mobile_app_pixel_8_pro
    data:
      title: Frontdoor
      message: Person detected frontdoor
      data:
        image: /media/local/reolink/person.jpg
        tag: person
        notification_icon: mdi:cctv
        clickAction: app://com.mcu.reolink
        actions:
          - action: URI
            title: Playback
            uri: app://com.synology.DScam
          - action: URI
            title: Live
            uri: app://com.mcu.reolink
    enabled: true
  - action: camera.record
    metadata: {}
    data:
      lookback: 5
      filename: /media/reolink/person.mp4
      duration: 10
    target:
      entity_id: camera.reolink_doorbell
  - action: shell_command.convert_video
    data: {}
  - action: notify.mobile_app_pixel_8_pro
    data:
      title: Frontdoor
      message: Person detected frontdoor
      data:
        video: /media/local/reolink/converted_person.mp4
        tag: person
        notification_icon: mdi:cctv
        clickAction: app://com.mcu.reolink
        actions:
          - action: URI
            title: Playback
            uri: app://com.synology.DScam
          - action: URI
            title: Live
            uri: app://com.mcu.reolink

**Comment by alec-pinson** [comment]
thanks @xandervanerven this helped me get mine working too!

I use the below ffmpeg command which speeds up the video which is nicer for notifications i think
```
ffmpeg -y -itsscale 0.3 -i /media/reolink/person.mp4 -c copy /media/reolink/converted_person.mp4
```

I actually download the clip from frigate and then convert...

`/config/download_and_convert_video.sh`
```bash
#!/bin/bash

if [[ -z "$1" ]]; then
  echo "Usage: $0 <download_url>"
  exit 1
fi

# download file + overwrite
wget "$1" -O /media/"$(basename "$1")"

# convert file to working format + speed up
ffmpeg -y -itsscale 0.3 -i "/media/$(basename "$1")" -c copy "/media/converted-$(basename "$1")"
```

home assistant `configuration.yaml`
```yaml
shell_command:
  download_and_convert_video: bash /download_and_convert_video.sh "{{download_url}}"
```

automation
```yaml
  - action: shell_command.download_and_convert_video
    metadata: {}
    data:
      download_url: "{{video}}"
```

where `video` in my case is
```
https://frigate.mydomain/api/events/{{id}}/clip.mp4
```
