### ISSUE TITLE
A way to differentiate multiple REPLY actions

### ISSUE THREAD

**Issue by karwosts** [home-assistant/android#3503]
**Is your feature request related to a problem? Please describe.**
It is possible to send an actionable notification with multiple `REPLY` actions, that allow a custom text reply. When the `mobile_app_notification_action` response comes back, it cannot be differentiated which one was pressed.

**Describe the solution you'd like**
Some kind of metadata field that can be included under the action key that is populated in the response.

**Describe alternatives you've considered, if any**
If extra metadata cannot be added, maybe create more `REPLY` actions that do the same thing, like `REPLY_1`, `REPLY_2`, ,... `REPLY_9`, so that the button that was pressed can be differentiated by their action name. 

**Additional context**

**Comment by jpelgrom** [comment]
> Or simply including the title of the actioned "action" in the response would probably work right?

That's actually relatively easy to add without breaking the current syntax. @karwosts, would that solve your issue?

<details><summary>Example notification sent</summary>

```yaml
action: notify.mobile_app_pixel_7a_dev
data:
  data:
    actions:
      - action: REPLY
        title: Reply 1
      - action: REPLY
        title: Reply 2
  message: UP test 2
```

</details>

<details><summary>Example event data with `reply_text_for` key</summary>

```yaml
event_type: mobile_app_notification_action
data:
  action_2_title: Reply 2
  webhook_id: ...
  message: UP test 2
  action_1_title: Reply 1
  action_1_key: REPLY
  action_2_key: REPLY
  server_id: "9"
  reply_text_for: Reply 2
  reply_text: For which one is this reply?
  action: REPLY
  ...
origin: REMOTE
time_fired: "2024-10-16T20:41:49.072704+00:00"
context:
  ...
```

</details>
