### ISSUE TITLE
Add TextInput Field for Actionable Notifications

### ISSUE THREAD

**Issue by droans** [home-assistant/android#362]
**Home Assistant Android version:** 1.60

**Android version:** 10

**Phone model:** OP 6T

**Home Assistant version:** 0.105.2

**Last working Home Assistant release (if known):** n/a

**Description of problem:**

Allow the use of TextInput fields on a notification similar to actionable notifications in the iOS companion app.

https://companion.home-assistant.io/en/notifications/actionable#actions-parameters

**Comment by mbrammer** [comment]
@droans Did you find another solution as a workaround?

@balloob @JBassett @robbiet480 Would be nice if we could open this again and save it somehow as a feature-request instead of just closing it.

**Comment by droans** [comment]
> @droans Did you find another solution as a workaround?
> 
> @balloob @JBassett @robbiet480 Would be nice if we could open this again and save it somehow as a feature-request instead of just closing it.

It was implemented about a year or so after I posted this FR.

```
service: notify.mobile_app_XXXX
data:
  ....
  data:
    actions:
      - action: REPLY
        title: Reply Button Title
```
