### ISSUE TITLE
Why won't sticky notification stay

### ISSUE THREAD

**Issue by dnestico** [home-assistant/android#3655]
**Home Assistant Android app version(s):**

**Android version(s):**
Android 14 Beta 3

**Device model(s):**
Pixel 7 Pro

**Home Assistant version:**
2023.7

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I am trying to set up a sticky/persistent notification that cannot be cleared by swiping it unless you click it to open the app, aka a sticky notification, for some reason the notification will not stay sticky and can still be swiped away.

YAML:

```
alias: Sticky camera notifications off notification
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.cam_notifications_off
    from: "0"
    to: null
condition: []
action:
  - service: notify.mobile_app_pixel_7_pro
    data:
      title: Camera notifications turned off
      message: >-
        Camera notifications have been turned off, tap notification to open
        camera page
      data:
        channel: Cameras Off
        notification_icon: mdi:cctv-off
        color: blue
        clickAction: /homekit-infused/cameras/
        sticky: true
        persistent: true
        tag: cctv
mode: single
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
https://photos.app.goo.gl/aN6N3Srzd3pQKkaN9 

**Additional information:**

**Comment by dshokouhi** [comment]
I am unable to reproduce. Using the below service call makes a notification that cannot be dismissed by swiping away or even selecting it.

```yaml
service: notify.mobile_app_dannys_pixel_7_pro
data:
  message: test1
  data:
    persistent: true
    tag: test1
    sticky: true
```

can you check notification history in app to see if the data shows up correctly?
