### ISSUE TITLE
car_ui triggers two notifications (one empty) when using `group` parameter

### ISSUE THREAD

**Issue by syphernl** [home-assistant/android#3667]
**Home Assistant Android app version(s):** [2023.7.5](https://github.com/home-assistant/android/releases/tag/2023.7.5)

**Android version(s):** 13

**Device model(s):** OnePlus 11

**Home Assistant version:** 2023.7.2

**Last working Home Assistant release (if known):** -

**Description of problem, include YAML if issue is related to notifications:**

When sending notifications with `car_ui: true` the message gets sent to the AA Display. 
After showing the message, a new empty popup shows up (and triggers the same notification sound).

```yaml
service: notify.iq_notify
data:
  title: 🔓 Alarm
  message: Alarm Turned Off ({{changed_by}})
  data:
    tag: alarm-disarmed
    mode: just_arrived
    notification_icon: mdi:shield-lock-open
    channel: Security - Alarm Status
    ttl: 0
    priority: high
    importance: high
    group: Security Alarm
    car_ui: true
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
> mode: just_arrived

Just a FYI this does nothing for the Android app. Not even documented on the site.

What car/device is this issue occurring on?

**Comment by syphernl** [comment]
> > mode: just_arrived
> 
> Just a FYI this does nothing for the Android app. Not even documented on the site.
> 
> What car/device is this issue occurring on?

This is an argument for the `iq_notify` service. On my phone I never had any duplicated / empty content messages.

Car is a Mazda 2 with Mzd Connect.

**Comment by dshokouhi** [comment]
ok can you try without the `group` parameter? It looks like the car may not support that properly. Testing without `group` does not show a duplicate and empty notification on my end.

**Comment by syphernl** [comment]
> ok can you try without the `group` parameter? It looks like the car may not support that properly. Testing without `group` does not show a duplicate and empty notification on my end.

Certainly, I will give it a go! Where you able to reproduce this issue with setting the `group` parameter?

**Comment by dshokouhi** [comment]
Yes I am able to reproduce.

```yaml
      message: Testing car UI notification
      data:
        ttl: 0
        priority: high
        channel: car
        car_ui: true
        group: test
        notification_icon: mdi:car
```

excuse the dust lol

![image](https://github.com/home-assistant/android/assets/1634145/4c49f834-46f8-4b2e-95c8-8946a7e82348)
