### ISSUE TITLE
Not getting replaced notification on Android

### ISSUE THREAD

**Issue by dnestico** [home-assistant/android#3775]
**Home Assistant Android app version(s):**
2023.8.1-full

**Android version(s):**
Android 14
Security update: July 5th, 2023

**Device model(s):**
Pixel 7 Pro

**Home Assistant version:**
2023.8.0

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I am testing a new updated notification that silently replaces itself after the door is unlocked or locked with the operator who did the action, this appears to be working on IOS but on Android I am only getting the first notification and not the replaced notification.

**Automation 1:** 
Ill just share the door-unlocked version cuz the door-locked version is the same just obviously different for the state.

```
alias: Notify notification - Door UNLOCKED (2)
description: ""
trigger:
  - platform: state
    entity_id:
      - lock.front_door
    from: locked
    to: unlocked
condition: []
action:
  - service: notify.all_notify_devices
    data:
      message: 🔓 • {{ now().strftime('%I:%M %p') }}
      title: Front Door Unlocked
      data:
        channel: Front Door
        tag: door_status
        importance: high
        priority: high
        ttl: 0
        notification_icon: mdi:lock-open-variant
        icon_url: /local/unlocked.png
        icon: mdi:lock-open-variant
        entity_id: camera.porch
        actions:
          - action: LOCK_DOOR
            title: Lock Door
            icon: sfsymbols:lock.fill
  - service: ll_notify.success
    data:
      message: Door Unlocked
      wait: 5
  - wait_for_trigger:
      - platform: event
        event_type: "mobile_app_notification_action "
        event_data:
          action: LOCK_DOOR
    continue_on_timeout: false
    timeout: "00:01:00"
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.front_door
mode: single
```

**Automation 2:**
Supposed to silently replace it, working on IOS but not on Android

```
alias: Front Door status changed by
description: ""
trigger:
  - platform: state
    entity_id: lock.front_door
    attribute: changed_by
condition: []
action:
  - service: notify.all_notify_devices
    data:
      message: >
        Front Door {{ states('lock.front_door') }} by {{
        state_attr('lock.front_door', 'changed_by') }}
      title: Front Door • {{ now().strftime('%I:%M %p') }}
      data:
        tag: door_status
        channel: Front Door Status
        ttl: 0
        priority: low
        importance: low
        notification_icon: mdi:door
        icon: mdi:door
        entity_id: camera.porch
        push:
          sound: none
mode: single
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Looks like you are using a different `channel` name in both automations so not technically the same notification. Also second notification has `priority: low` change that to `priority: high` so it can be delivered timely.

**Comment by dnestico** [comment]
Oh, I did this intentionally so it would silently update it without making a 2nd noise, guess that wasn't needed then? Thanks will try this out.

**Comment by jpelgrom** [comment]
To prevent sound when replacing you should set [alert once] (https://companion.home-assistant.io/docs/notifications/notifications-basic#alert-once) on your notification.

**Comment by dnestico** [comment]
I put this in the replaced notification but I will look at this too, thanks. 

```
    push:
      sound: none
```

**Comment by dshokouhi** [comment]
> Oh, I did this intentionally so it would silently update it without making a 2nd noise

so you want

https://companion.home-assistant.io/docs/notifications/notifications-basic/#alert-once

**Comment by jpelgrom** [comment]
> I put this in the 2nd/replaced notification but I will look at this too, thanks.
> 
> Do I just add this to the replaced notification or even the original? @jpelgrom
> 
> ```
>     push:
>       sound: none
> ```

No need to ping me.

You'd set `alert_once: true` on the second notification for Android devices. `push: sound: none` [only applies to iOS](https://companion.home-assistant.io/docs/notifications/notifications-basic/#iosmacos-specific).

**Comment by dshokouhi** [comment]
one other thing about `alert_once` its a channel specific setting so you may need to create a new channel to use it on

**Comment by dnestico** [comment]
Ok but I thought I needed to make the channel the same for it to be able to replace the original notification?

I guess thats why I set the priority of the notification to "low" so that way the 2nd notification makes no sound. https://developer.android.com/develop/ui/views/notifications/channels#importance

**Comment by dshokouhi** [comment]
yes use the same channel name and use alert_once option as well with it.  No need to worry about setting the importance for that.

**Comment by dnestico** [comment]
Ok this is what I have with your guy's information for the replaced notification, I will see soon if it works.

```
service: notify.all_notify_devices
data:
  message: >
    Front Door {{ states('lock.front_door') }} by {{
    state_attr('lock.front_door', 'changed_by') }}
  title: Front Door • {{ now().strftime('%I:%M %p') }}
  data:
    tag: door_status
    alert_once: true
    channel: Front Door
    ttl: 0
    # priority: high
    # importance: high
    notification_icon: mdi:door
    icon: mdi:door
    entity_id: camera.porch
    push:
      sound: none
```
