### ISSUE TITLE
"Alert" integration not generating sounds when the phone screen is off

### ISSUE THREAD

**Issue by jackb007** [home-assistant/android#3809]
The "Alert" integration sends recurrent notifications at fixed time intervals when it's triggered until the condition that triggered it is resolved or until the alert is acknowledged by the user, whichever happens first. This integration uses the "General" channel for the sending of notifications. The "General" channel will generate sound alerts by default.

When the "General" channel is used to send a single nofitication -- within an automation, for example -- everything works as expected. However, when the "General" channel is used by the "Alert" integration, notification sounds will only be generated if the phone screen is on or if the screen has been off for less than a minute. This could cause a user to miss critical alerts, as he would naturally expect the notifications generated by the "Alert" integration to generate a sound, even if the screen is off.

When the phone screen is off and the "Alert" integration starts sending notifications, these notifications are received by the phone as messages, which will start accumulating, but a sound will only be produced when the phone screen is unlocked. Until then, the phone will remain silent. Please don't mark this as anything else than a bug, This IS a bug, and it could be critical for someone using this integration.

Using Home Assistant 2023.8.3, Supervisor 2023.08.1, Supervisor 2023.08.1, Android 13, and latest version of the HA Companion App.

**Comment by dshokouhi** [comment]
Why is the template removed again here?

Please share the alert integration configuration. I want to see what data you are sending to it. Need to see how you set it up and the automation usage.

**Comment by jackb007** [comment]
"configuration.yaml" file:
```
...
automation: !include automations.yaml
alert: !include alerts.yaml
...
```
"automations.yaml" file:
```
...
action:
  - service: notify.mobile_app_galaxy_xcover
    data:
      title: ALARM
      message: The house alarm has been triggered
      data:
        ttl: 0
        enabled: true
        priority: high
        channel: "General"
...
```
The automation above is working perfectly fine.
"alerts.yaml" file:
```
sample_alert:
  name: STUFF IS HAPPENING!!
  done_message: Stuff happened
  entity_id: input_boolean.button
  state: "on"
  repeat: 0.25           # notifications sent every quarter of a minute (15 seconds)
  can_acknowledge: true
  skip_first: false
  notifiers:
    - mobile_app_galaxy_xcover
    - persistent_notification
```
Additional information: this started happening yesterday, after performing the following updates:
1. Home Assistant operating system upgraded to 10.5
2. Samsung One UI version updated to 5.1

**Comment by jpelgrom** [comment]
If you want the alert to behave the same as a normal notification, you need to pass the same `data`. In your alert configuration, you're not adding any data.

The issue you're describing sounds like the device is sleeping after a minute and waiting to process notifications. For normal notifications you use `ttl: 0` and `priority: high` which Android will use to get around this, add the same to your alert data :)

**Comment by jackb007** [comment]
I had already tried passing the same data as in the automation example:
```
sample_alert:
  name: STUFF IS HAPPENING!!
  done_message: Stuff happened
  entity_id: input_boolean.button
  state: "on"
  repeat: 1
  can_acknowledge: true
  skip_first: false
  notifiers:
    - mobile_app_galaxy_xcover
    - persistent_notification
  data:
    data:
      ttl: 0
      enabled: true
      priority: high
```
The code above results in the exact same behaviour. But even if this wasn't the case, any average user would assume the example provided in the documentation (which doesn't include any data) would generate audible notifications even after the screen has gone black, just like most SMS or email applications do.

**Comment by jpelgrom** [comment]
That's one `data` too much, try:

```yaml
sample_alert:
  name: STUFF IS HAPPENING!!
  done_message: Stuff happened
  entity_id: input_boolean.button
  state: "on"
  repeat: 1
  can_acknowledge: true
  skip_first: false
  notifiers:
    - mobile_app_galaxy_xcover
    - persistent_notification
  data:
    ttl: 0
    enabled: true
    priority: high
```

> any average user would assume the example provided in the documentation (which doesn't include any data) would generate audible notifications even after the screen has gone black, just like most SMS or email applications do.

The integration and notifiers are generic, what you're experiencing is Android specific behavior. Feel free to open a pull request to add to the documentation if you feel this is necessary, there is an edit button at the bottom of the page.

**Comment by jackb007** [comment]
That fixed it. You may want to suggest the addition of the "data" lines to the documentation. I suggested an extremely-reasonalbe change a couple of days ago and it was denied. So not a bug but insufficient documentation.

Thanks a lot.

**Comment by dshokouhi** [comment]
> You may want to suggest the addition of the "data" lines to the documentation.

Its already there

https://www.home-assistant.io/integrations/alert/

`For notifiers that require other parameters (such as twilio_sms which requires you specify a target parameter when sending the notification), you can use the group notification to wrap them for an alert. Simply create a group notification type with a single notification member (such as twilio_sms) specifying the required parameters other than message provided by the alert integration:`

**Comment by jackb007** [comment]
If you modify the very first example to make it look like this:
```
...
  notifiers:
    - mobile_app_galaxy_xcover
    - persistent_notification
  data:
    ttl: 0
    priority: high
    enabled: true
...
```
I can guarantee you a lot of people will be spared a lot of trouble, and possibly even worse. The last four lines ensure that the notification will generate a sound  when the phone screen is off, which would be the expected default behaviour. I even tested the alert with the phone screen turned on and everything seemed to work fine. It was only by some kind of fluke that I decided to test it while the screen was off. I can guarantee you only a tiny fraction of users will read that full page of documentation. Even after being directed by you to the relevant paragraph, I struggle to understand it. Most of us just copy-paste the first example, modify it to our needs, test it, and then move on.
