### ISSUE TITLE
notify.mobile_app_  and  command_webview

### ISSUE THREAD

**Issue by smithbill17** [home-assistant/android#3822]
**Home Assistant Android app version(s):**
Companion App 2023.8.3-full

**Android version(s):**
Android 5.1

**Device model(s):**
Tesco Hudl 2

**Home Assistant version:**
Home Assistant OS 2023.8.4  (on rpi4b)

**Last working Home Assistant release (if known):**
N/A

**Description of problem, include YAML if issue is related to notifications:**

I use an old Hudl2 tablet (Android 5.1 'Lollipop') as a 'wall mounted' dashboard. It has the Companion App installed and it works fine.

I created an Automation in my Home Assistant v2023.8.4 with an action to use the notify.mobile_app_<your_device_id_here> service to send a 'command_webview' to the Hudl2 tablet, thus:

```
action:
  - service: notify.mobile_app_hudl2
    data:
      message: command_screen_on
  - service: notify.mobile_app_hudl2
    data:
      message: command_webview
      data:
        command: http://192.168.68.131:8123/dashboard-cameras/upstairs
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: notify.mobile_app_hudl2
    data:
      message: command_webview
      data:
        command: http://192.168.68.131:8123/dashboard-cameras/avtech
```

It works fine BUT:

the FIRST command_webview will launch the Companion App on the Hudl2 tablet and display the correct dashboard ("dashboard-cameras/upstairs" in the above extract). There's then a 15sec delay as per my action code.

the SECOND command_webview will again bring the Companion App to the foreground on the Hudl2 tablet, but it will NOT open the desired 2nd dashboard ("dashboard-cameras/avtech").

If I manually force-close the Companion App on the Hudl2 & then manually run the SECOND command_webview, it will open the correct dashboard ("avtech") but subsequent command_webviews don't change from that displayed dashboard.

Reading the documentation, it says:

"If you want to just open the Companion app to any page or even the homepage you will want to send message: command_webview."

which 'implies' that you can only "open" the Companion App to a given dashboard, and that subsequent command_webviews make no changes as the Companion App is already open (all it does is wakes the tablet screen with the Companion App in the foreground showing the last selected dashboard).

Is it possible for the notify 'command_webview" to actually open the chosen dashboard even if the Companion App is already open?

(all I was trying to achieve is a remotely triggered 'carousel' of dashboards on my wall mounted tablet)

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
I have also tried using 'relative' paths as @dshokouhi suggested I should, but that still doesn't work.

If I put
`command: "/dashboard-cameras/avtech"`
it still doesn't work

If I put
`command: "/lovelace/0?homescreen=1"`
or even
`command: "/lovelace/settings"`
exactly as per the documentation example, it still remains stubbornly stuck on whatever dashboard the Companion App was launched on.

(and double-quotes around the command make no difference either)

**Comment by dshokouhi** [comment]
@smithbill17  I am unable to reproduce on my Pixel 7 Pro.  I can successfully switch between all tabs using examples like below. We have seen in the past when a device does not respect our Intent Flags to launch a new task and that is out of our control when that is the case. Do you have another android device to test with to see if the device is indeed the issue?

```
service: notify.mobile_app_dannys_pixel_7_pro
data:
  message: command_webview
  data:
    command: /lovelace/ollies
```
```
service: notify.mobile_app_dannys_pixel_7_pro
data:
  message: command_webview
  data:
    command: /lovelace/settings
```
