### ISSUE TITLE
Storage permissions for notifications (for images, icons & sounds)

### ISSUE THREAD

**Issue by cholek3** [home-assistant/android#383]
Would it be possible to allow app access to android device storage, so we could use it to display images and icons in notifications, as well as play custom notification sounds from local storage, please?

Simple example of a config to play custom notification sound and display local image and icon

```
title: "Home Assistant"
message: "Front PIR activated"
data:
  color: 'blue'
  push: 
    sound: '"/storage/emulated/0/Media/Push-notifications/Sounds/motion-detected_front.mp3' #or *.wav
  image: "/storage/emulated/0/Media/Push-notifications/Images/motion-detected-red.jpg" #or *.png
  icon: "/storage/emulated/0/Media/Push-notifications/Icons/motion-detected-red.png"
```
