### ISSUE TITLE
music_stream not adjustable with HA running in background

### ISSUE THREAD

**Issue by titiviking** [home-assistant/android#3840]
**Home Assistant Android app version(s):**
2023.8.4-full
**Android version(s):**
13
**Device model(s):**
Oneplus Pro 8
**Home Assistant version:**
2023.8.4
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Unable to set the volume level using command_volume_level for music_stream when app runs in the background.
When HA is opened in foreground on the device, then the service completes successfully and the level is adjusted
 ```
service: notify.titi
data:
  message: command_volume_level
  data:
    media_stream: music_stream
    command: 3
```
Other streams don't show same behaviour.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
