### ISSUE TITLE
Timer Sensor / Entity

### ISSUE THREAD

**Issue by RoepLuke** [home-assistant/android#3854]
**Is your feature request related to a problem? Please describe.**
I want to be able to set a regular Android Timer (using any / the default Timer App of my Android Phone) from within Home Assistant. This is currently somewhat possible using the following intents sent via a Notification / the notify entity that the Companion App provides:
```
service: notify.mobile_app_DEVICENAME
data:
  message: command_activity
  data:
    intent_action: android.intent.action.SET_TIMER
    intent_extras: android.intent.extra.alarm.LENGTH:{{ time_calculated_seconds}},android.intent.extra.alarm.SKIP_UI:true,android.intent.extra.alarm.MESSAGE:{{ message }}
```

**Describe the solution you'd like**
A "full integration" like a timer.DEVICENAME that can easily be controlled would be nice. 

This has a few Problems / Questions, for example:
- Timers in Android usually have Names (not required). How can a Timer entity provide an input for a Name? To read the Name an Attribute would suffice.
- The App/Integration could provide a way to create any number of Timers (like it does for Widgets / QuickAction-Tiles) that need to be created/configured before they can be used. Or maybe the App/Integration could provide a Service to create new Timers (optionally with Names) and that Service could then respond with the entity id.

**Describe alternatives you've considered, if any**
Only providing the one currently active and/or next to end Timer as a Sensor Entity. One could then at least determine if setting the Timer was successfull and / or create an Automation that creates/starts an equally long Timer in HA.

**Additional context**
- Also a Timer entity can be displayed in the Dashboard using the Timer Bar Card (HACS).
- A Sensor providing the currently active Timer with its remaining Time would (i think) be either a heavy load to keep updated or way out of date.
- The App could possibly react to the above described intent to update the Sensor when a Timer is set but after that the Timer could only listen for a 'Timer ended'-Intent (if that even exists). That would give your Timer only two states 'Running' and 'Ended'/unknown.
- The Timer app reacting to the SET_TIMER intent is chosen by Android or by specifying a intent_platform, so that wouldnt neccessarily be a thing one would need to care about. 
- I dont know if or how it is possible to read all currently running Timers or if this would require to listen for all SET_TIMER intents and keeping track of them.
