### ISSUE TITLE
Energy cards don't display data when viewed from the Android companion app

### ISSUE THREAD

**Issue by chuanguyen** [home-assistant/android#3913]
**Home Assistant Android app version(s):**
2023-9.2-full

**Android version(s):** 
Android 13

**Device model(s):** 
Pixel 6

**Home Assistant version:** 
Home Assistant 2023.9.3

**Last working Home Assistant release (if known):** 
Unsure since I only encountered this on the recent version

**Description of problem, include YAML if issue is related to notifications:**

I have an energy bridge that is feeding live usage from my smart meter. This integration works and displays in the built-in energy tab fine on my phone and on my other devices. 

However, I am trying to create a custom dashboard using the energy cards (As mentioned here https://www.home-assistant.io/dashboards/energy/). 

The problem I'm running into is that the custom dashboard displays fine on my computer and on the browser on the phone. However, when viewed from the companion app, the cards fail to display any data. 

A snippet of my dashboard YAML for the energy page is shown below

```
  - title: Energy
    path: home-energy
    icon: mdi:home-lightning-bolt
    subview: true
    badges: []
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: back
      - type: custom:energy-period-selector-plus
        card_background: false
        today_button: true
        prev_next_buttons: true
        compare_button_type: text
        today_button_type: text
        period_buttons:
          - day
          - week
          - month
          - year
          - custom
        compare_button_label: Compare
      - type: energy-usage-graph
      - type: custom:apexcharts-card
        header:
          show: true
          title: Outside Temperature
          show_states: true
          colorize_states: true
        graph_span: 24h
        span:
          start: day
        series:
          - entity: sensor.openweathermap_temperature
            color: orange
            stroke_width: 3
            type: line
            extend_to: now
      - type: energy-distribution
        link_dashboard: true
      - type: energy-sources-table
      - type: energy-carbon-consumed-gauge
      - type: gauge
        entity: sensor.house_power_demand_per_minute
        name: Current Power Draw
        min: 0
        max: 7500
        needle: false

```

**Companion App Logs:**

[homeassistant_companion_log_9-4-2023_16-22-49.txt](https://github.com/home-assistant/android/files/12810821/homeassistant_companion_log_9-4-2023_16-22-49.txt)

**Screenshot or video of problem:**

View of the dashboard from the browser: 

![browser_1_signal-2023-10-04-162430_003](https://github.com/home-assistant/android/assets/5003747/a70c06fa-8e52-428e-ad73-18ee1cc5b61a)

![browser_2_signal-2023-10-04-162430_002](https://github.com/home-assistant/android/assets/5003747/b9c694c7-37eb-47ac-a1a7-c6d5daaf8d35)

View from the same phone in the companion app: 

![compansion_app_1_signal-2023-10-04-162430_005](https://github.com/home-assistant/android/assets/5003747/febe388c-9958-4112-b7f3-71e7b77e09e8)

![compansion_app_2_signal-2023-10-04-162430_004](https://github.com/home-assistant/android/assets/5003747/43609362-c5a1-424d-9d73-6eb20f0714d8)

**Additional information:**

I have encountered this on the IOS companion app as well, but will submit a separate issue for that.
