### ISSUE TITLE
Phone Notification Local Image fails to download

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/android#3926]
Hi i have Samsuing and Android 13, last few months idk why but Local image notifcations not work i dont see in phone, logs are clear in phone everytinhg is good, but when i will replace it with a url everything is works good, where is the problem?, thx,

```
service: notify.mobile_app_milan_phone
data:
  message: test
  data:
    image: /media/local/Camera Snapshots/Doorbell Camera.jpg
```

![image](https://github.com/home-assistant/android/assets/42905545/ea7a8f32-cf93-4409-9a0e-a4246784bcbb)
