### ISSUE TITLE
Device screen timeout blocked when dashboard is streaming live camera

### ISSUE THREAD

**Issue by raldred** [home-assistant/android#3953]
**Home Assistant Android app version(s):**
2023.10.2-full
**Android version(s):**
11, 13, 14
**Device model(s):**
Galaxy Tab A, Pixel 6
**Home Assistant version:**
2023.10.3
**Last working Home Assistant release (if known):**
unknown
**Description of problem, include YAML if issue is related to notifications:**

_Context:_
Tried two separate Android devices, both exhibit the problem described below.
Both have their OS screen timeout set to 15 seconds.
Both have their companion app with "Keep on screen" setting "off"
Issue presents whether charging or not.

_Issue:_
When a the dashboard has a live camera stream, the device's screen timeout has no effect, the dashboard remains on and active.
When the dashboard has NO live camera stream, the device's screen timeout works as expected.

**Companion App Logs:**
_Too long to share here, over github comment limit of 65536 characters_
Google drive link:
https://drive.google.com/file/d/1UaXKwMCnvQV3ZC6XuHDeeht4AmLf5v1S/view?usp=sharing

**Screenshot or video of problem:**
*Note, my Nest camera's "auto" view shows a weird blank image since I transferred it to the Google Home app.*

<img src="https://github.com/home-assistant/android/assets/37096/1165d1e6-a7fa-4c86-9450-3fa3a9a01e15" width="500" />
<img src="https://github.com/home-assistant/android/assets/37096/42f60780-de98-435d-ac96-b3709709460f" width="500" /><br>
<img src="https://github.com/home-assistant/android/assets/37096/14008a59-1778-4023-a88b-1886050b9b0b" height="500" />
<img src="https://github.com/home-assistant/android/assets/37096/4ffa8e42-4a25-4de5-980c-fd6306d0d56e" height="500" />

_Videos:_
*Too big for github's 10MB limit*
Google photos link: 
https://photos.app.goo.gl/XUoTM3B7mAkuKL6x6

**Additional information:**
This issue has been reported before but has been closed, I was asked to create a new issue.
https://github.com/home-assistant/android/issues/2881

**Comment by dshokouhi** [comment]
Not quite sure this is something in teh apps control, might be specific to WebView here.

**Comment by spawn-guy** [comment]
That is an interesting issue.

I would, actually, like my screen Not to timeout. 
my Samsung tab a6 (android 5.1.1) does not have a Screen option to never timeout (max 30 mins).

And it was not timing out with hass app open.. Until I cleared all app data (wanted to fix a neerslag-app addon issue, alas).
But I did have a live view card. it is now not visible on screen, when neerslag chart fails.


So, that is what I need to fix - make live view visible for screen not to timeout 🤔

**Comment by raldred** [comment]
I think as @dshokouhi alluded to, this is related to the underlying webview which prevents screen timeout when a video stream is playing.
`android.webkit.WebView` maintains a visibility property which applies or removes the `FLAG_KEEP_SCREEN_ON` flag.

I think we'd need introduce something to manipulate the visibility with `webView.setVisibility(View.GONE);` based on the devices configured screen timeout (if available)

**Comment by almirus** [comment]
https://github.com/home-assistant/core/issues/130517#issuecomment-2818180591

**Comment by grigi** [comment]
I'm also running into this issue. I have a camera feed on the dashboard and the tablet display will never timeout.
It will timeout when viewing a page that doesn't show the camera feed.

If this isn't doable, maybe a Notification Command to turn the screen off remotely might work for cases like mine where we know if someone is in the room or not?

**Comment by cysieks** [comment]
I have a rather ugly workaround for this, but works. The flaw is, that when motion is detected, it takes 2-3s to show up.

So I have created empty section called 'blank':

```
- type: sections
    max_columns: 4
    title: blank
    path: blank
    sections:
      - type: grid
        cards: []
    icon: mdi:checkbox-blank
    cards: []
    header:
      card:
        type: markdown
        text_only: true
        content: |
          # The screen is turning off...
```


Then in automation I change the visible section to that blank:

```
alias: Turn off tablet screen
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.pir_hol_parter_zajetosc
    for:
      hours: 0
      minutes: 2
      seconds: 0
    from: "on"
conditions: []
actions:
  - action: notify.mobile_app_mipad6
    data:
      message: command_screen_off_timeout
      data:
        command: 1
  - action: notify.mobile_app_mipad6
    data:
      message: command_screen_on
      data:
        command: keep_screen_off
  - action: notify.mobile_app_mipad6
    enabled: false
    data:
      message: command_webview
      data: {}
  - action: notify.mobile_app_mipad6
    data:
      message: command_webview
      data:
        command: /dashboard-tablet/blank
    enabled: true
mode: single
```

This allows Home Assistant to turn off, because there is no visible camera feed.
