### ISSUE TITLE
Support `action_data` for notification actions

### ISSUE THREAD

**Issue by dragosprotung** [home-assistant/android#396]
This is something already supported by the iOS app and it would be to have this on Android.
It would simplify automations a lot

``` yaml
service: notify.mobile_app_pixel_4
   data:
      message: "The light has been left on"
      data:
         actions:
            - action: "turn_off_light"
              title: "Turn off light"
              action_data:
                 entity_id: light.test
                 my_custom_data: foo_bar
```
