### ISSUE TITLE
Persistent notifications can be swiped away in Android 14

### ISSUE THREAD

**Issue by charlie969** [home-assistant/android#3965]
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):**
14

**Device model(s):**
Pixel 7

**Home Assistant version:**
2023.10.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
"Persistent" notifications are no longer persistent when using Android 14, meaning the notifications can be swiped away to dismiss them.

Sending the following using Developer Tools -> Services results in a notification which can be dismissed by swiping:

```
service: notify.mobile_app_pixel_7
data:
  title: Is it sticky at Android 14
  message: Can you remove this sticky message in Android 14?
  data:
    notification_icon: mdi:note
    tag: test
    persistent: true
    color: "#ff0000"
``` 

**Screenshot or video of problem:**

**Additional information:**
See also https://community.home-assistant.io/t/notify-mobile-companion-app-devices/512487/76?u=chezzo
