### ISSUE TITLE
Action uri not going to todo entity

### ISSUE THREAD

**Issue by seanmccabe** [home-assistant/android#4134]
**Home Assistant Android app version(s):**
2023.12.5-full

**Android version(s):**
13

**Device model(s):**
Samsung Galaxy Note 20 Ultra

**Home Assistant version:**
2023.12.4

**Last working Home Assistant release (if known):**
N/a

**Description of problem, include YAML if issue is related to notifications:**
Notification uri action goes to the default `/lovelace` if using a template instead of going to the todo entity as it is listed.
The code is exactly the same and `clickAction` is unaffected.

```
- alias: Show shopping list at The Warehouse
  mode: single
  max_exceeded: silent
  condition:
    - condition: template
      value_template: "{{ states('todo.the_warehouse')|int(0) > 0 }}"
  trigger:
    platform: state
    entity_id:
      - person.kelly
      - person.sean    
    to:
      - Countdown Queensgate
      - The Warehouse Petone
      - K'Mart Petone
    for:
      # minutes: 1
      seconds: 5
  action:
    - service: script.shopping_notification
      data:
        person: "{{ trigger.entity_id }}"
        # title: "You're near The Warehouse, check shopping list?"
        title: >-
          You're near 
          {% if states(trigger.entity_id) == "K'Mart Petone" -%} 
            K'Mart
          {%- else -%} 
          The Warehouse
          {%- endif %}
          , check shopping list?
        list: "the_warehouse"
        message: "There are {{ states('todo.the_warehouse') }} items on your shopping list."
        tag: warehouse
```

```
shopping_notification:
  mode: queued
  max: 10
  max_exceeded: silent
  alias: Send Shopping Notification
  sequence:
    - service: notify.mobile_app_sm_n985f
      data:
        title: "{{ title }}"
        message: "{{ message }}"
        data:
          sticky: "true"
          tag: "{{ tag }}"
          notification_icon: "{{ state_attr('todo.' ~ list, 'icon') }}"
          clickAction: "/todo?entity_id=todo.{{ list|string }}"
          actions:
            - action: "URI"
              title: "View"
              uri: ="/todo?entity_id=todo.{{ list|string }}"
```

**Companion App Logs:**
[homeassistant_companion_log_0-14-2024_17-12-5.txt](https://github.com/home-assistant/android/files/13930305/homeassistant_companion_log_0-14-2024_17-12-5.txt)

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Your mistake is

`              uri: ="/todo?entity_id=todo.{{ list|string }}"`

should be

`              uri: "/todo?entity_id=todo.{{ list|string }}"`

Spotted because the logs show it strange too.

`01-14 17:05:35.715  3909  3909 D MessagingService: Creating notification with following data: {notification_icon=mdi:warehouse, sticky=true, tag=warehouse, title=You're near  The Warehouse , check shopping list?, webhook_id=a7ea40aec40028414b2279879ee21f60efca74aa8545d18436ca4ec556c54c09, clickAction=/todo?entity_id=todo.the_warehouse, message=There are 1 items on your shopping list., action_1_title=View, action_1_key=URI, action_1_uri=="/todo?entity_id=todo.the_warehouse", server_id=1}`

The last part `action_1_uri=="/todo?entity_id=todo.the_warehouse"`

I imagine notification history would also show this?

**Comment by seanmccabe** [comment]
Correct, that was another test and got it wrong, even correcting to 

```
actions:
    - action: "URI"
      title: "View"
      uri: "/todo?entity_id=todo.{{ list|string }}"
```

still does the same thing
