### ISSUE TITLE
Allow for Android app to change OS background

### ISSUE THREAD

**Issue by pbulteel** [home-assistant/android#4140]
**Is your feature request related to a problem? Please describe.**

I am trying to replace the background of the OS using the Home Assistant companion. IFTTT can change the background (for example: Space image of the day) - but I would like to be able to provide the image which can be loaded by a HA automation. You could use this feature to change the background in case of an event/alert.

**Describe the solution you'd like**

Changing the background of the OS (what you see in the launcher) by calling the notify service to the device.
eg.

Remote image. This caches the image locally.
```
service: notify.mobile_app_samsung
data:
  message: 'modify_background'
  data: 
    uri: 'https://location.server.local/images/something.jpg'
```

Local image
```
service: notify.mobile_app_samsung
data:
  message: 'modify_background'
  data: 
    uri: 'internal storage/DCIM/family_photo.jpg'
```

**Describe alternatives you've considered, if any**

None. If this functionality is already available through the current notify service, there aren't any examples documented.

**Additional context**

The "remote image" could potentially be done via two automation: one that downloads the image storing it locally,  and the other which modifies the background with the now local image.
