### ISSUE TITLE
Unified critical notification configuration (sync Android and iOS)

### ISSUE THREAD

**Issue by masi** [home-assistant/android#4147]
**Is your feature request related to a problem? Please describe.**
I want to configure notification for apps on Android and iOS without having to remember obscure settings ("ttl" isn't even explained in the documentation).

**Describe the solution you'd like**
```
action:
  - service: notify.mobile_app_<your_device_id_here>
  data:
    data:
      critical: true
```

shall be treated as
```
action:
  - service: notify.mobile_app_<your_device_id_here>
  data:
    data:
      ttl: 0
      priority: high
      channel: alarm_stream
```

Sidenote: It's a pity that TTS notifications don't use channel but media_stream.

**Describe alternatives you've considered, if any**
The service of the notify integration of HA gets a new data attribute "critical" or "priority".

**Additional context**
On iOS we get
```
action:
  - service: notify.mobile_app_<your_device_id_here>
  data:
    data:
      push:
        sound:
          critical: 1
          volume: 1.0
```
