### ISSUE TITLE
Lock open

### ISSUE THREAD

**Issue by Isengo1989** [home-assistant/android#4179]
**Describe the solution you'd like**
Currently the lock type is supported but only gives the option of

- **lock**
- **unlock**

There is a third one **open** - which would be quiete convinient when coming from the car, press the open one and you can enter without a key. In any other case you still need to grab your key or app.

https://www.home-assistant.io/integrations/lock/

**Comment by dshokouhi** [comment]
so theres an issue with this request. Adding this means the `lock` domain will no longer be toggleable so it will not be working as designed in quick setting tiles, device controls or even the  widget. I think maybe for this a script would be a better fit to not impede on existing functionality

**Comment by Mikescotland** [comment]
Depending on the lock (nuki for instance does it) you can execute open lock by sending a mqtt command (and create a button to do so). Works perfectly.

**Comment by Isengo1989** [comment]
I did add a script for it, for some reason those were not shown at some point, but now work good with the companion app, here is the snippet:

```
alias: Open front door
sequence:
  - service: lock.open
    metadata: {}
    data: {}
    target:
      device_id: XXXXXXXXXXXXXXXXXXXXX
mode: single
icon: mdi:door-open
```
