### ISSUE TITLE
Allow changing Wifi State using notification commands

### ISSUE THREAD

**Issue by robert-alfaro** [home-assistant/android#4258]
**Is your feature request related to a problem? Please describe.**

The [notification commands](https://companion.home-assistant.io/docs/notifications/notification-commands) supports turning on/off bluetooth, for example, however it does not support controlling the wifi radio state.

**Describe the solution you'd like**

Be able to turn on/off WiFi radio on mobile device, service example:
```yaml
service: notify.mobile_app_<device>
data:
  message: command_wifi
  data:
    command: turn_off
```

**Describe alternatives you've considered, if any**

**Additional context**

Previous attempts at this were successful (HassPhoneControl) and seems Android API has the permission to allow application to [CHANGE_WIFI_STATE](https://developer.android.com/reference/android/Manifest.permission#CHANGE_WIFI_STATE).
