### ISSUE TITLE
Allow YAML mode for entering widget service data

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/android#427]
The current auto complete fields and the "Add Field" button when adding a widget work well for services with simple options. However, they don't work for services which have nested properties. For example, it isn't possible to create a widget which will make the equivalents of this service call:

```
service: notify.mobile_app_other_phone
data:
  message: "I have arrived."
  data:
    sticky: true
    actions:
      - action: confirm
         title: "OK"
```
Other, simpler, examples also don't work, such as:

```
service: light.turn_on
data:
  entity_id: light.test_light
  rgb_color: [255,0,0]
```

To allow this sort of thing it would be useful to be able to switch to YAML mode and enter the service data as YAML rather than via the fields.
