### ISSUE TITLE
Image no longer shows on expanded notification

### ISSUE THREAD

**Issue by Hootie81** [home-assistant/android#4300]
**Home Assistant Android app version(s):**
2024.3.4-full
**Android version(s):**
14
**Device model(s):**
Pixel 7 Pro
**Home Assistant version:**
2024.3.3
**Last working Home Assistant release (if known):**
worked last week
**Description of problem, include YAML if issue is related to notifications:**
notification shows small image when minimized, but when the notification is expanded the image doesn't show at all.
suspect its to do with changes for GIF images in the latest release. 

previously working code
```
service: notify.mobile_app_chris
data:
  message: >-
    {{trigger.to_state.name[:-7]}} Camera triggered by a {{ states('sensor.'
    ~trigger.to_state.name[:-7]~'detections')}} at {{ as_timestamp(now()) |
    timestamp_custom('%H:%M') }}
  title: Motion Alarm
  data:
    color: red
    notification_icon: mdi:motion-sensor
    channel: MotionDetect
    ttl: 0
    importance: high
    priority: high
    vibrationPattern: "100, 1000, 100, 1000, 100, 250, 1000, 250 "
    clickAction: /lovelace/motion-sensors
    actions:
      - action: alarm
        title: Alarm!
      - action: URI
        title: Snooze all cameras
        uri: entityId:input_number.motion_global_snooze_time
      - action: URI
        title: Snooze this camera
        uri: >-
          {{ 'entityId:input_number.' ~trigger.to_state.object_id~'_snooze_time'
          }}
    image: /api/camera_proxy/camera.{{trigger.to_state.object_id}}_snap
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
