### ISSUE TITLE
chronometer when_relative not working

### ISSUE THREAD

**Issue by janrg** [home-assistant/android#4443]
**Home Assistant Android app version(s):**
2024.4.1-full
**Android version(s):**
14
**Device model(s):**
Pixel 6 Pro
**Home Assistant version:**
2024.6.1
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I've followed the example code for chronometer notifications from the docs.
```
action:
    - service: notify.mobile_app_xyz
      data:
        title: "Next Alarm"
        message: >-
          Next Alarm At
        data:
          timeout: 120
          chronometer: true
          when: 120
          when_relative: true
```

Based on the logs (see below), it looks like the property may not be passed to the app.
I end up with a timer that counts up from 120 seconds after the epoch.

**Companion App Logs:**

```
06-08 12:25:47.124 14227 14227 D MessagingService: Creating notification with following data: {timeout=120, when=120, title=Next Alarm, webhook_id=bfb262a22758bd0cef211a28007d067d157cd82fb5255a0b5b193ecbc309ac77, message=Next Alarm At, chronometer=true, server_id=1}
```

**Screenshot or video of problem:**
![Screenshot_20240608-122154](https://github.com/home-assistant/android/assets/18070351/7cfee838-6c1d-4782-b834-145f02a68b01)

**Additional information:**
