### ISSUE TITLE
Incorrect notification group handling

### ISSUE THREAD

**Issue by miguelangel-nubla** [home-assistant/android#4453]
### The problem

Notifications to Android phone using a `group` in service `notify.mobile_app_*` gives unexpected behavior.
Running these two services sequentially:
```yaml
service: notify.mobile_app_phone
data:
  message: Test message
  data:
    tag: tag1
    group: group1
```
```yaml
service: notify.mobile_app_phone
data:
  message: Test message
  data:
    tag: tag1
    group: group2
```

results in:
![Screenshot 2024-06-10 012136](https://github.com/home-assistant/core/assets/866596/7a4e89ee-01f7-44db-a736-95edcfa363dd)

Since they are using the same tag, I expected either the tag to be unique globally (so only last message is displayed) or two complete notifications, one per group, instead of one missing the message.

Also note the "last" notification at the top does not display group.

### What version of Home Assistant Core has the issue?

core-2024.6.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

mobile_app

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/mobile_app
