### ISSUE TITLE
Make the navigation bar and status bar transparent (edge-to-edge)

### ISSUE THREAD

**Issue by MathisP75** [home-assistant/android#4547]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by jpelgrom** [comment]
Unfortunately this isn't as easy as you might think because of the WebView. Last time I tried the problem was that information about insets wasn't set correctly on the WebView, making it impossible for the frontend to adapt. That means content will end up behind the system navigation, which is especially problematic when using button navigation or when you have a tall status bar due to a camera/cutout. It looks like the bug is still unresolved: https://issuetracker.google.com/issues/40699457.

(I thought we already had an issue for this, but can't find it.)

**Comment by MathisP75** [comment]
Ah well that sucks, it would have been neat. Let's hope Google does something about it.

**Comment by Gregman-js** [comment]
What do you think about passing this inset values from android activity to webview on page load?
I created a quick demo in Android Compose:
```kotlin
Scaffold (modifier = Modifier.fillMaxSize()) { padding ->
                AndroidView(
                    factory = { context ->
                        WebView(context).apply {
                            settings.javaScriptEnabled = true
                            webViewClient = object : WebViewClient() {
                                override fun onPageFinished(view: WebView?, url: String?) {
                                    super.onPageFinished(view, url)
                                    val safeInsetTop = (padding.calculateTopPadding().value)
                                    val safeInsetBottom = (padding.calculateBottomPadding().value)
                                    val safeAreaJs = """
                                    document.documentElement.style.setProperty('--android-safe-area-inset-top', '${safeInsetTop}px');
                                    document.documentElement.style.setProperty('--android-safe-area-inset-bottom', '${safeInsetBottom}px');
                                """.trimIndent()
                                    evaluateJavascript(safeAreaJs, null)
                                }
                            }
                        }
                    },
                    update = { webView ->
                        webView.loadUrl("http://10.0.2.2:8000")
                    },
                )
            }
```
In above snippet we can see that Scaffold component (edge-to-edge) give us `padding` property (our insets) and we are executing JS after page load that sets css properties.
Then HA page instead of relying on `env()` can have custom property that works on both android and ios.
```css
:root {
  --insets-top: var(--android-safe-area-inset-top, env(safe-area-inset-top));
  --insets-bottom: var(--android-safe-area-inset-bottom, env(safe-area-inset-bottom));
}
.main {
      padding-top: var(--insets-top);
}
.bottom {
   position: fixed;
   bottom: 0;
   padding-bottom: var(--insets-bottom);
   background-color: white;
   display: block;
   width: 100%;
  }
```

Below we can see that text have proper padding on top and bottom of screen

<img width="447" alt="Image" src="https://github.com/user-attachments/assets/82c7face-7907-4c98-951e-9542707c7ad7" />

<img width="449" alt="Image" src="https://github.com/user-attachments/assets/47cf2236-83f4-4034-9e45-3fae0c12adde" />
