### ISSUE TITLE
Alarm panel on android auto? Doesn't work? Code required=false

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/android#4906]
**Android version(s):** Android 15

**Device model(s):** pixel 7

**Home Assistant version:** 2024.12.3

**Home Assistant Companion:** 2024.12.1

Hi, I'm testing android auto, I have an alarm panel, where I don't need to enter a code to disarm/home/away, the attribute "code alarm required" is set to false... I enabled it as favorite on my android auto... But I can't click on the entity? According to the docs it should be possible? What am I missing?

Reference:

https://github.com/home-assistant/android/pull/3765
https://github.com/home-assistant/android/issues/3710

**Comment by dshokouhi** [comment]
please share your alarm configuration.

mine is 

```
alarm_control_panel:
  platform: manual
  name: "Home"
  arming_time: 30
  delay_time: 30
  code_arm_required: false
  disarmed:
    trigger_time: 0
```

we also may need to check the supported features flag too
