### ISSUE TITLE
Hold action not working for image element in picture-elements card

### ISSUE THREAD

**Issue by queimadus** [home-assistant/android#4908]
**Home Assistant Android app version(s):** 
2024.12.1-full

**Android version(s):** 
14 (One UI 6.1)

**Device model(s):** 
Samsung s22

**Home Assistant version:**: 
2024.12.3

**Last working Home Assistant release (if known):** 
2024.11.X

**Description of problem, include YAML if issue is related to notifications:**
When using a image element inside a picture-elements card, the hold_action (long press) is not working. After the long press, we see some visual response in the bottom left of the screen but the action does not trigger (see video). 

I've tested that this doesn't happen using the browser version of lovelace so I think it should be a android app related issue. 

I include a reproducible snippet (might have to change the entity to something that exists) 

```
type: picture-elements
image: https://demo.home-assistant.io/stub_config/floorplan.png
elements:
  - type: image
    image: >-
      https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTAxL2Rlc2lnbndpdGhtZTA5X2FfbGlnaHRfYnVsYl9pbl90aGVfc3R5bGVfb2ZfaHlwZXItcmVhbGlzdGljX2lsbF9iMTE2ZmI3Zi1kYzc4LTQ1MDEtYWQwNC05NDY4YjVlNzU2ZjAucG5n.png
    style:
      top: 50%
      left: 50%
      width: 15%
    tap_action:
      action: toggle
    entity: light.bathroom_office

```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

take notice of the flashing on the bottom left corner

https://github.com/user-attachments/assets/43d7a3fd-e617-4bbe-847f-c73162cb7ce1

Same flow but on the browser works:

https://github.com/user-attachments/assets/5e8e6189-a9e7-4f68-93a4-c3a33c730537

**Additional information:**
