### ISSUE TITLE
Chronometer fails if parameter 'when' is given a float

### ISSUE THREAD

**Issue by harmpter** [home-assistant/android#5024]
**Home Assistant Android app version(s):**
2025.1.2

**Android version(s):**
14

**Device model(s):**
Google Pixel 5

**Home Assistant version:**
2025.1.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Chronometer fails if parameter `when:` is given a float. The notification still posts, but without chronometer.
```yaml
action: notify.mobile_app_dd
data:
  message: test
  data:
    chronometer: true
    when: "{{ now()|as_timestamp }}"
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
Probably irrelevant, but a float ending in .0 like 1738267025.0 seems to pass as an integer and results in a working chronometer timeout.

I hope this issue can help fill a to-do list with many many checked items and make someone feel very productive 🚀😄
