### ISSUE TITLE
command_media not working for Pixel 7 Pro

### ISSUE THREAD

**Issue by program-the-brain-not-the-heartbeat** [home-assistant/android#5056]
**Home Assistant Android app version(s):** 2025.1.2-full

**Android version(s):** 15

**Device model(s):** Google Pixel 7 Pro

**Home Assistant version:** 2025.2.5

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
```yaml
action: notify.mobile_app_pixel_7_pro
data:
  message: "command_media"
  data:
    command: "stop"
    media_command: "stop"
    media_package_name: "com.spotify.music"
```

I've tried with and without the 'command: "stop"' line. The package does match what is installed. It just shows the "command_media" as a notification.

**Companion App Logs:**

[homeassistant_companion_log_1-23-2025_11-19-34.txt](https://github.com/user-attachments/files/18931418/homeassistant_companion_log_1-23-2025_11-19-34.txt)

**Screenshot or video of problem:**

![Image](https://github.com/user-attachments/assets/8c3df79a-5c0b-4290-a42d-fd691b57406f)

**Additional information:**
