### ISSUE TITLE
Add support for Android 16 Live Updates notifications

### ISSUE THREAD

**Issue by dnestico** [home-assistant/android#5116]
**Is your feature request related to a problem? Please describe.**
No, technically not a problem, but it would be a useful feature to add. Android 16 Beta 2.1 officially activated the new Live Notifications feature and I think it could be useful for Home Assistant in a few ways such as tracking tasks like Washing/Dryer Machines or Input Booleans, Navigation, and even climate tracking.

**Describe the solution you'd like**
Add support for Android 16 Live Notifications.

**Describe alternatives you've considered, if any**
None.

**Additional context**
Here's info about Android 16 Live Notifications.

https://www.androidauthority.com/android-16-live-notifications-3518375/
https://9to5google.com/2025/03/06/google-maps-android-16-live-updates-feature/

**Comment by dshokouhi** [comment]
you can actually achieve this today using the [replace](https://companion.home-assistant.io/docs/notifications/notifications-basic/#replacing) feature......for the app to add live support that may be battery intensive to keep a websocket connection active.

**Comment by dnestico** [comment]
That's cool will have to check that out, tbh I thought with Android 16 officially supporting Live Updates that this would make these notifications easier and maybe optimized battery drain wise since the whole point is for the notification to be "Live Update". 

Well hopefully can still be considered to maybe let us make better notifications design wise as shown in the [official dev articles](https://developer.android.com/about/versions/16/features/progress-centric-notifications)...

![Image](https://github.com/user-attachments/assets/c05be2e6-72de-485a-8321-d5d07afa4540)

**Comment by dshokouhi** [comment]
So we do already support [progress notifications](https://companion.home-assistant.io/docs/notifications/notifications-basic/#progress-notifications) so this wouldnt be far off once the app targets the latest version. Will be interesting to see how this will be implemented :)

**Comment by Aasikki** [comment]
This would be really cool for timers and other progress bars!

**Comment by cdunn95** [comment]
Adding to this to say that having live notifications for things like 3D printing progress would be so handy. As of now, I have them marked as persistent, silent notifications; but with Android 15 that makes them hidden until you unlock. 

Having them as a live notification would allow for me to not only have them on the lock screen, but also be listed separately from my normal notifications.

**Comment by sumoneelse** [comment]
> you can actually achieve this today using the [replace](https://companion.home-assistant.io/docs/notifications/notifications-basic/#replacing) feature......for the app to add live support that may be battery intensive to keep a websocket connection active.

Live notifications provide an ability that can't be achieved using replace:  Adding text to the chip ("hello" below.)

<img width="400" height="140" alt="Image" src="https://github.com/user-attachments/assets/b3cd68c3-5997-45eb-9132-2a8daee99ed1" />

If this _can_ be done I'd appreciate knowing how.

Tasker for android just gained the ability to create live notifications, and you can specify the text when you create the notification as I did in my example above.  I'd sure love this as a home assistant feature and gain the ability to template the message text fields natively.

If you use the Join Home Assistant integration to send events to Tasker, here's a proof-of-concept script that will create a live notification. You'll need to adjust for your join service name and create the tasker profile and task.  In the Notify task step, be sure to select the "Live Update" box and fill in "Short Critical Text" with the variable name you give to the Chip text.

```
sequence:
  - action: joaoapps_join.joaoapps_join_service_send_tasker
    metadata: {}
    data:
      command: livenotify=:={{title}}=:={{message}}=:={{chip}}
    alias: Live notification
fields:
  title:
    selector:
      text: null
    name: Title
    required: true
  message:
    selector:
      text: null
    name: Message
    required: true
  chip:
    selector:
      text: null
    name: Chip
    required: true
alias: Sent Tasker Live Notification
description: ""
```
