### ISSUE TITLE
Location - High Accuracy Mode Issues

### ISSUE THREAD

**Issue by Morphy99** [home-assistant/android#5127]
**Home Assistant Android app version(s):**
2025.1.2-full
**Android version(s):**
15

**Device model(s):**
Google Pixel 9 Pro

**Home Assistant version:**
2025.3.3

**Last working Home Assistant release (if known):**
NA

**Description of problem, include YAML if issue is related to notifications:**
I've been trying to perfect the Leaving Home & Arriving Home automations and have really been struggling with the Pixel which I've had since January.

I have set several automations up to trigger high accuracy mode manually as entering zones doesn't seem to work reliably.

Today when I arrived home and high accuracy mode triggered for no apparent reason. I even have an automation to force this off in case it triggers accidentally whilst home:

```
- id: presence_high_accuracy off
  alias: Presence High Accuracy Off
  trigger:
  - platform: state
    entity_id: binary_sensor.pixel_pro_high_accuracy_mode
    to: "on"
  action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.pixel_pro_high_accuracy_mode
            state: "on"
          - condition: state
            entity_id: person.me
            state: "home"
        sequence:
          - service: notify.mobile_app_pixel_pro
            data:
              message: "command_high_accuracy_mode"
              data:
                command: "turn_off"
          - service: notify.mobile_app_pixel_pro
            data:
              message: High Accuracy Mode Forced Off
              title: Location problem
              data:
                ttl: 0
                car_ui: true
                channel: "Important"
                priority: high
```

This triggered and still didn't disable High Accuracy mode. Going into settings I can see this disabled yet it's still going:

![Image](https://github.com/user-attachments/assets/98567f8a-e239-422c-8c4e-9ada5bdb5e64)

![Image](https://github.com/user-attachments/assets/a3e443b1-9a6d-4fad-9f7d-1d3e7699b493)

It seems as though the app has stopped responding to notification commands for High Accuracy as this automation was triggered at 10:46:

```
- id: presence_update_location_arriving home
  alias: Presence Update Location Arriving Home
  trigger:
  - platform: state
    entity_id: binary_sensor.pixel_pro_android_auto
    to: "off"
  - platform: state
    entity_id: 
      - binary_sensor.front_drive_person_occupancy
      - binary_sensor.front_path_person_occupancy
      - binary_sensor.front_drive_car_occupancy
    to: "on"
  - platform: state
    entity_id: sensor.pixel_pro_wifi_connection
    to: "mywifi"
  condition:
  - condition: state
    entity_id: input_boolean.security_away
    state: 'on'
  action:
  - service: notify.mobile_app_pixel_pro
    data:
      message: "command_high_accuracy_mode"
      data:
        command: "turn_on"
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: device_tracker.pixel_pro
      attribute: gps_accuracy
      below: 20
    - platform: state
      entity_id: person.me
      to: "home"
    timeout: "00:01:00"
  - service: notify.mobile_app_pixel_pro
    data:
      message: "command_high_accuracy_mode"
      data:
        command: "turn_off"
```

Yet the High Accuracy Mode sensor doesn't report on till 10:50:

![Image](https://github.com/user-attachments/assets/55cd296c-6515-41c4-9efa-729468ecdcfe)

I can't see why or how this was triggered as none of my automations with `command_high_accuracy_mode` were triggered and I wasn't entering a zone. 

Furthermore, tapping disable in the notification switched it off, yet the binary sensor is still reporting it's on.

**Companion App Logs:**

No logs available for when this occurred unfortunately. The earliest time was 10:58 so maybe the app crashed.

**Screenshot or video of problem:**

**Additional information:**

Another question I have is regarding the behaviour of the notify command, `command_high_accuracy_mode` I initially thought this would just trigger the mode on and off but it seems to disable the option in the location sensor. In which case, using automations to turn on and off manually, disables the ability for zone entering to trigger it. Surely it would make more sense to have two different commands like:

`command_high_accuracy_mode_active` (manually activate the mode)
`command_high_accuracy_mode` (adjust the setting)
