### ISSUE TITLE
Ability to dimiss or snooze an active alarm

### ISSUE THREAD

**Issue by johanneshk** [home-assistant/android#5256]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to dismiss or snooze an active alarm on my phone. Use-case: My phone is outside my bedroom and I'd like to push a zigbee button to dismiss or snooze.

**Describe the solution you'd like**
The companion app has the permissions and functionality to dismiss or snooze an alarm which can be triggered via Home Assistant.

**Describe alternatives you've considered, if any**
This could be achieved via an external app (e.g. Tasker) but I'd prefer a native way if possible. 

**Additional context**
None.

**Comment by dshokouhi** [comment]
This is already doable using existing functionality. You need to use the following intent:

https://developer.android.com/reference/android/provider/AlarmClock#ACTION_DISMISS_ALARM

and use it alongside our `command_broadcast_intent` 

https://companion.home-assistant.io/docs/notifications/notification-commands#broadcast-intent

**Comment by gitty323** [comment]
In case anyone runs across this and can't get `command_broadcast_intent` working like me, I had to use `command_activity` instead to get it working. Example action:
```
actions:
  - action: notify.mobile_app_my_tablet
    data:
      message: command_activity
      data:
        # Package name only needed if multiple clock apps are installed
        # intent_package_name: com.android.deskclock
        intent_action: android.intent.action.DISMISS_ALARM
```
