### ISSUE TITLE
Automation Action missing menu when alias has insufficient whitespace

### ISSUE THREAD

**Issue by kerryland** [home-assistant/android#5309]
**Home Assistant Android app version(s):**
2025.4.3-full

**Android version(s):**
10 (EMUI12)

**Device model(s):**
Huawei p30

**Home Assistant version:**
2025.5.1

**Last working Home Assistant release (if known):**
n/a

**Description of problem, include YAML if issue is related to notifications:**
The action in this automation does not have an associated "3 dot" menu on the phone. It's caused by the long string of text without any whitespace (alexa_media_family_room_sonos_beam). In the real world this alias was generated automatically by HA, but setting the name explicitly via `alias:` illustrates the same problem.
```
alias: test test test
description: ""
triggers:
  - at: "19:30:00"
    trigger: time
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
    alias: 'No Menu: alexa_media_family_room_sonos_beam'
mode: single
```
**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![Image](https://github.com/user-attachments/assets/bd332604-47ab-40d6-8532-cc173dca7406)

**Additional information:**
