### ISSUE TITLE
android notification action malfunction

### ISSUE THREAD

**Issue by hitekrawkus** [home-assistant/android#5385]
**Home Assistant Android app version(s):2025.5.3-full

**Android version(s):15

**Device model(s):Galaxy Ultra S24

**Home Assistant version:2025.5.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications: The automation runs without errors but pressing the "close garage door" button in the notification does not trigger the action. I see the notification being created but no subsequent entries for the button tap or its failure in the app logs. Sharing YAML for the automation, then the script, and attaching the app logs from the android app. 

```
alias: Garage door left open notification
description: ""
triggers:
  - entity_id: person.jake_gusiew
    zone: zone.home
    event: leave
    trigger: zone
  - entity_id: person.rachael_gusiew
    zone: zone.home
    event: leave
    trigger: zone
conditions:
  - condition: device
    device_id: 0f64a8cea3e4402d418af669e7a38a35
    domain: cover
    entity_id: abd121b76fb9b11009ec7f265691c88b
    type: is_open
actions:
  - data:
      message: Garage door is left open!
      data:
        actions:
          - action: close_garage_door_jake
            title: Close Garage Door
            uri: /api/services/script/turn_on
    action: notify.mobile_app_jake_s_phone
  - data:
      message: The garage door is left open!
      data:
        actions:
          - action: close_garage_door_rachael
            title: Close Garage Door
            uri: /api/services/script/turn_on
    action: notify.mobile_app_pixel_9
mode: single


alias: Close Garage Door
sequence:
  - action: button.press
    data: {}
    target:
      entity_id: button.garage_door_toggle_door
mode: single
description: ""
```

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
