### ISSUE TITLE
Sticky and color not working - Android 15 / One UI7

### ISSUE THREAD

**Issue by conorlap** [home-assistant/android#5391]
**Home Assistant Android app version(s):**
2025.6.1-full
**Android version(s):**
Android 15 / One UI 7.0
**Device model(s):**
Samsung S24+
**Home Assistant version:**
2025.5.3
**Last working Home Assistant release (if known):**
Not sure

**Description of problem, include YAML if issue is related to notifications:**
I've noticed recently that sticky and color options on notifications are not working anymore. I *think* this has started happening since my phone was updated to One UI 7 / Android 15. I get no colour in the notification icon anymore and I can swipe the notification away without pressing the action button.

Example yaml:

```
data:
  title: Take out the bins!
  message: It's BROWN bin week
  data:
    actions:
      - action: BINS_OUT
        title: Bins have been put out
    ttl: 0
    priority: high
    persistent: true
    sticky: true
    notification_icon: mdi:trash-can-outline
    color: "#aa5501"
    tag: bins
action: notify.ourphone_group
```

**Companion App Logs:**

```
N/A
```

**Screenshot or video of problem:**

**Additional information:**
