### ISSUE TITLE
If a HA notification is present, subsequent notifications are all silent regardless of channel settings

### ISSUE THREAD

**Issue by attila123456** [home-assistant/android#5428]
**Home Assistant Android app version(s):** 2025.5.3-full

**Android version(s):** 16

**Device model(s):** Pixel 7 Pro 

**Home Assistant version:** 2025.6.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Seems to be a recent issue that started 1-2 weeks ago, I guess either with the Android 16 update or the HA 2025.6.1 update. I use a custom notification channel for various alarms, and the sound, vibration, do not disturb options etc are configured on the phone. Now, if the HA app already has an active notification (doesn't need to be an alarm, any other HA notification that I haven´t viewed or cleared yet) then any subsequent HA notification, including alarms, are _silent_ - the screen does not turn on, no sound, no vibration, which is quite problematic for alarms. A notification yaml sample from an automation:

```yaml
data:
  title: ALARM
  message: Alarm text...
  data:
    ttl: 0
    priority: high
    channel: alarm
action: notify.mobile_app_pixel_7_pro
```
I have not changed any automations or app notification settings recently.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
