### ISSUE TITLE
Native dashboard support on WearOS

### ISSUE THREAD

**Issue by andyearnshaw** [home-assistant/android#5470]
**Is your feature request related to a problem? Please describe.**
I'm frequently frustrated by the lack of support for WearOS from smart device manufacturers. I often think, "that would be great if I could have a tile on my watch."

Home Assistant's WearOS app goes a long way to solve this issue, but it's very limited and it could be so much more powerful. I'd love to have more control over the layout on my tiles so that I can create what are, essentially, mini device apps on my watch. Template tiles can only do so much.

Some things I would be looking to build:

* Home security overview with alarm status, door locks, windows, smoke/leak/CO detectors.
* Car remote control with battery level/charging state, buttons for lock/unlock and air conditioning and a warning display
* TV remove for my various Android TV
* Status display of my energy setup, e.g. solar panel current output, home battery level/charging state, current electricity cost
* Ongoing activity dashboards (see below)

**Describe the solution you'd like**
To begin with, I'd like to be able to at least define some custom dashboards in YAML. We don't need a WYSIWIG dashboard designer unless the feature becomes very popular. Designing it in YAML would be slower and more painful, but it would be worth it. The WYSIWIG part could even come from the watch, receiving an update and instantly refreshing when the YAML is saved on the server for quicker tweaking.

A limited set of components would be available to begin with: the ones provided by the jetpack compose libraries. In fact, the yaml structure could even match the jetpack compose hierarchy. Alternatively, a subset of components that are easy to recreate on both iOS and Android could mean both platforms can implement native dashboards in a way that allows users to share their configurations without having to worry about compatibility.

Sample yaml:

```yaml
version: 1

# used for linking between dashboards
key: android.dashboard_car

# similar structure to lovelace configurations
data:
  config:

    # Views could work like tiles that you can swipe between
    views:
      - path: status

        # components, not cards. Most values could be templates.
        components:
          - type: time_text
          - type: circular_progress
            start_angle: 295.5f
            end_angle: 245.5f
            progress: {{ states('sensor.renault_scenic_battery') }}
            stroke_width: 6.dp
            indicator_color:
            track_color:
            modifier:
              fill_max_size: true
             padding: 1.dp
          - type: text
            text: {{ states('sensor.renault_scenic_plug_status') }}
            modifier:
              # ... position text
          - type: button
            icon: mdi:air-conditioner
            tap_action:
              action: button.press
              target: button.renault_scenic_start_air_conditioner
            modifier:
              # ... position button
          - type: button
            icon: mdi:unlock
            tap_action:
              action: button.press
              target: button.renault_scenic_unlock
            modifier:
              # ... position button

# ... and so on
```

**Describe alternatives you've considered, if any**
The alternative is to just use your phone. But I don't always carry my phone with me. It's way more convenient to look at my watch most of the time.

**Additional context**
I think this would be an important pre-requisite for [Ongoing Activity][1] support. I'm thinking dashboards as notifications here. If anyone reading this is unsure of what an ongoing activity is, it's like a sticky notification but it takes over your watch main screen (or gives you an icon on the main screen to switch to the activity screen).

Some examples of potential ongoing activities:

* Printer/3D printer is printing: ink/material levels, printing progress, time remaining, cancel button
* Car is charging: progress, time remaining, stop charging button
* Washer/dryer/dishwasher/oven/other appliance statuses
* Home/car/smoke alarm in progress
* Energy saving session/ultra cheap rate in progress: battery charged, energy used, etc
* TV is on: remote dashboard appears

The possibilities are truly endless, to be honest.

[1]: https://developer.android.com/training/wearables/notifications/ongoing-activity
