### ISSUE TITLE
Replace Geocoded location when in a 'zone'

### ISSUE THREAD

**Issue by pinkywafer** [home-assistant/android#557]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that the geocoded location does not show the zone when in a zone.  I already know the location of zones I have defined, and do not need to see geocoded location of the device.

**Describe the solution you'd like**
I'd like the geocoded location to show the name of the zone if the device is in a zone

**Describe alternatives you've considered, if any**
Currently I have to use an additional template sensor to use the geocoded location only when the device tracker is "away" (ie. not in a zone)

**Additional context**

**Comment by dshokouhi** [comment]
@pinkywafer why not use the `device_tracker` entity that gets created for the zone? The state of that entity will show the `zone` that is the expected behavior.  Geocoded location is meant to only show the physical location of your location.  If your accuracy is not correct you can adjust that in the `zone` as well with the radius setting.

https://companion.home-assistant.io/docs/core/sensors#geocoded-location-sensor

**Comment by pinkywafer** [comment]
I am using the `device_tracker` for my zone based automations.
I like to display the location on the front-end also, and use both the current state and history-graph. 
 The geocoded location is very useful for this, but when in a zone, I do not find it useful, as the zone would be more useful in this case, so I am currently using a additional template sensor just for this:
```yaml
sensor:
  - platform: template
    sensors:
      jenny_location:
        value_template: >-
          {% if is_state("device_tracker.my_mobile", "away") -%}
            {{ states("sensor.my_mobile_geocoded_location") }}
          {%- else -%}
            {{ states("device_tracker.my_mobile") }}
          {%- endif %}
```
