### ISSUE TITLE
Battery charging state not updating when app is closed

### ISSUE THREAD

**Issue by mfedderly** [home-assistant/android#560]
**Home Assistant Android version:** 1.8.0-144

**Android version:** 10

**Phone model:** Pixel 2

**Home Assistant version:** 0.108.6

**Last working Home Assistant release (if known):**

**Description of problem:**

I'm trying to use the battery charging state changing to trigger an event and it seems like the trigger isn't firing until I open the Home Assistant app on my phone. When I open the app it seems to fire the event immediately. It has been a while since I've done Android development, but shouldn't the app be listening for the charge events in the manifest instead of or in addition to the code?

Here's the listener in the application, and the manifest that doesn't listen for the same thing.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt#L29-L37

https://github.com/home-assistant/android/blob/master/app/src/main/AndroidManifest.xml

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by mfedderly** [comment]
Doing some more testing on this: the events seem to trigger within a few minutes of plugging/unplugging the phone. I think that's pretty close to acceptable, but I'd be open to making a PR if its possible that using the manifest instead could make this faster.

**Comment by dshokouhi** [comment]
@mfedderly which state or attribute are you expecting to update immediately? I know that the attribute `charger_type` updates immediately but attribute `is_charging` does not update immediately.  Some devices show `not_charging` for the state immediately while others update to `charging` after a few minutes.  My wifes Pixel 3 XL goes to `not_charging` immediately while my Pixel 4 XL takes a few minutes to update to `charging` and usually skips the initial `not_charging` state that my wifes phone goes to.

**Comment by mfedderly** [comment]
Very interesting. I was using `is_charging`. I'll give `charger_type` a look and see if that makes the updates happen faster. Thanks for the tip!

**Comment by mfedderly** [comment]
I just tested this and `charger_type` and `is_charging` seemed to change at the same time for me, after a longer delay of several minutes (5-10). Do you think its worth investigating the manifest change?

**Comment by dshokouhi** [comment]
`charger_type` should update immediately.  Maybe before investigating the manifest change try to start fresh with the app: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by mfedderly** [comment]
I finally got a chance to work on this and things seem to be working after starting fresh. For anyone winding up here later, here's a copy of the automation that seems to be working:

```
- id: '12345'
  alias: Set Alarm at night
  description: ''
  trigger:
  - entity_id: sensor.pixel2_charger
    from: N/A
    platform: state
    to: AC
  condition:
  - condition: state
    entity_id: device_tracker.unifi_macaddress_default
    state: home
  - condition: state
    entity_id: alarm_control_panel.ring_alarm
    state: disarmed
  - after: '20:00:00'
    before: '23:59:59'
    condition: time
  action:
  - data: {}
    entity_id: alarm_control_panel.ring_alarm
    service: alarm_control_panel.alarm_arm_home
```


Sorry for the false alarm!
