### ISSUE TITLE
App Notification will not come through while phone is locked and screen off

### ISSUE THREAD

**Issue by WedHumpDay** [home-assistant/android#594]
**Home Assistant Android version:**
1.9.0-167

**Android version:**
Note 8  on  Android  9
S10  on  Android 10

**Phone model:**
Samsung Note 8 & Galaxy S10

**Home Assistant version:**
0.109.6

**Last working Home Assistant release (if known):**
Unknown - Been this way for couple releases

**Description of problem:**
Notifications will not come through unless the phone is awake.

I've check all settings:
- Battery optimization - Not optimized
- Device care battery
-- Adaptive battery - Disabled
-- Put unused apps to sleep - Disabled
-- Sleeping apps - Not in the list
-- Put app to sleep - disabled

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
@WedHumpDay please paste an example of the notification you are sending.  I think you may have missed: https://companion.home-assistant.io/docs/notifications/critical-notifications/

Which goes over how to bypass doze for notifications.

**Comment by WedHumpDay** [comment]
Is the following required ?
```
        data:
          ttl: 0
          priority: high
```

Config below.
Have far more complex but this one is simple.

```
- id: '###########'
  alias: Garage Door Left Opened (Leaving House)
  description: ''
  trigger:
  - entity_id: group.track_all_persons
    from: home
    platform: state
    to: not_home
  - event_data: {}
    event_type: timer.finished
    platform: event
  condition:
  - condition: state
    entity_id: binary_sensor.visonic_mct_340_e_0b1b6981_1_1280
    state: 'on'
  action:
  - data:
      message: Garage door still opened. Turn around and close.
    service: notify.mobile_app_sm_n950u
  - data:
      message: Garage door still opened. Turn around and close.
    service: notify.mobile_app_sm_g973u
  - data: {}
    entity_id: timer.garage_door
    service: timer.start
```
