### ISSUE TITLE
no image attachments in notifications

### ISSUE THREAD

**Issue by murtoz** [home-assistant/android#602]
**Home Assistant Android version:**
1.9.0-167
**Android version:**
android 10 / kernel 4.14.62-18098116 / one ui 2.0
**Phone model:**
samsung galaxy a50
**Home Assistant version:**
0.110.2
**Last working Home Assistant release (if known):**
I think I started playing with this in version 106 or something along those lines but it has never worked
**Description of problem:**
I am not able to get my phone to display an image in a notification from the home assistant app
**Traceback (if applicable):**
n/a
**Screenshot of problem:**
![Screenshot_20200525-193418_One UI Home](https://user-images.githubusercontent.com/58794298/82837087-00a5d980-9ec0-11ea-8caf-758f39c91422.jpg)
![Screenshot_20200525-193426_One UI Home](https://user-images.githubusercontent.com/58794298/82837088-01d70680-9ec0-11ea-96a9-219d9033fa7c.jpg)
![Screenshot_20200525-193437_Settings](https://user-images.githubusercontent.com/58794298/82837090-01d70680-9ec0-11ea-98c8-65b5130a117b.jpg)
**Additional information:**
notification done via automation as follows:
```
- id: '1588841135118'
  alias: Front Door Notifier - Android
  description: ''
  trigger:
  - entity_id: binary_sensor.amcrest_camera_motion_detected
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data:
        file: https://my_unique_nabu_case_address.ui.nabu.casa/local/frontdoor.jpg
      message: Someone's at the front door
      title: Front Door Motion!
    service: notify.mobile_app_galaxya50
```
If i paste the link to the image in a browser on my phone I can see the picture. I have tried other images on public websites but none of these show in the notification either.
