### ISSUE TITLE
ClickAction with relative Lovelace Link only working once after fresh App install

### ISSUE THREAD

**Issue by dickesW** [home-assistant/android#605]
**Home Assistant Android version:**
1.9.0-167
**Android version:**
9 / 10
**Phone model:**
Honor View 10 / Huawei P30 Pro
**Home Assistant version:**
0.110.3
**Last working Home Assistant release (if known):**
Never
**Description of problem:**
When clicking on the notification for the first time after a fresh install:
- the requested Lovelace tab defined in `clickAction` is opened (e.g. `'/lovelace/test'`)

When clicking on the notification every other time with a different `clickAction` Lovelace URI:
- always the `clickAction` Lovelace URI sent with the first notification after a fresh install is opened.
- this does not change until a fresh install of the app (not helping: stopping / starting / closing the app, reboot of phone)
- web URIs (e.g. `'https://www.google.com'`) are opened correctly
- sending no `clickAction` also opens the first sent `clickAction` Lovelace URI

Clicking on the same URI in the "Actionable Notification" (see example below) always opens the desired Lovelace tab.

Used notification:
```yaml
title: 'Motion Detected in Backyard'
message: 'Someone might be in the backyard.'
data:
  clickAction: '/lovelace/outside'
  actions:
  - action: 'URI'
    title: 'Open Url'
    uri: '/lovelace/outside'
```

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
Might relate to https://github.com/home-assistant/android/issues/486
