### ISSUE TITLE
Received invalid webhook type: scan_tag + cosmetic issue

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/android#736]
**Home Assistant Android version:** 2.1.1-4-g7b0e28f-253-full
**Android version:** 11
**Phone model:** Oneplus 7T
**Home Assistant version:** 113.3
**Description of problem:** when i scan a tag, i receive error below , do i need also a new HA version? 114.0 ?
**Traceback (if applicable):**

```
[homeassistant.components.mobile_app.webhook] Received invalid webhook type: scan_tag
```

also second, prolmen, maybe cosmetic, not sure:
When i open HA client on my oneplus, i goto NFC options, i click on ‘write nfc tag’ , when i am in that submenu, when i then click the back button of my oneplus, it just generates a new identifier, instead of going to the previous menu
while i click on the back button itself in the topbar, then it goes back to the previous menu…

**Additional information:**
this is my test automation : 

```
- id: nfc_alarm_off
  initial_state: 'on'
  alias: NFC Alarm Off"
  trigger:
    platform: event 
    event_type: tag_scanned 
    event_data:
      device_id: !secret ha_client_fabio
      tag_id: !secret nfc_alarm_uit
  action:
    - service: !secret notify_ha_fabio
      data:
        title: "Risco Alarm"
        message: "Alarm uitgezet!"
        data:

          image: !secret snapshot_buiten_alarm_uit
          priority: high
          ttl: 0     
          channel: Alarm
```

**Comment by dshokouhi** [comment]
This might be fixed in HA 0.114 as the core changes were introduced then

**Comment by pergolafabio** [comment]
ok, done, no error anymore, allthouh my automation doesnt start / run 👍

**Comment by pergolafabio** [comment]
hmm, it seems i dont get notifications at all anymore now :s

**Comment by dshokouhi** [comment]
Hmm there were no app changes done to notifications.  Do you get any HA core errors?  If not try to enable debug logging for `homeassistant.components.mobile_app: debug`  and send the notification again to see what it says.  I just tested a notification against the latest beta and it worked however I have not checked NFC yet.

**Comment by pergolafabio** [comment]
yeah, i tested other notifications too, doesnt come through... gonna debug now

**Comment by pergolafabio** [comment]
hmm 👍 
2020-08-12 16:43:14 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for fabio_ha_client: 13 sent, 300 allowed, 0 errors, resets in 9:16:45

**Comment by dshokouhi** [comment]
Hmm did your app crash in the background while you tested NFC? Looks like its sending it but app did not receive.

**Comment by pergolafabio** [comment]
no, app didnt crash... , the above error is not from the NFC, it was just another notification test, seems all my notifications are not working anymore

the NFC tag is coming in:
2020-08-12 16:53:08 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload for type scan_tag: {'tag_id': '09c6cddc-xxx'}

but my test autoamtion doesnt run at all it seems, while my secrets are fine, its the client name + token id

```
- id: nfc_test
  initial_state: 'on'
  alias: 'NFC Test
  trigger:
    platform: event 
    event_type: tag_scanned 
    event_data:
      device_id: !secret ha_client_fabio
      tag_id: !secret nfc_alarm_uit
  action:

    - service: light.turn_on
      entity_id: light.bureau
```

in secrets : 

ha_client_fabio: fabio_ha_client
nfc_alarm_uit: 09c6cddc-xxx

**Comment by pergolafabio** [comment]
every normal PUSH notifications gives me : 

mobile_app push notification rate limits for fabio_ha_client: 14 sent, 300 allowed, 0 errors, resets in 9:02:06

not sure why , never saw that before on 113.3 or earlier

**Comment by pergolafabio** [comment]
ok, seems push notifications are working again... ok, thats was maybe stupid , i enabled that debug mode , maybe i never noticed those rate limits in my logbook :)

anyway, only issue left is that automation and NFC

**Comment by dshokouhi** [comment]
After you update to HA core 0.114 I would recheck the NFC tag and maybe try a new one to see if it works better now.

**Comment by pergolafabio** [comment]
ok, gonna test that later

**Comment by pergolafabio** [comment]
Ok, rewrote the tag, but still the same... Seems my automation doesn't trigger at all, maybe it's wrong?

**Comment by dshokouhi** [comment]
The only docs I know of are: https://companion.home-assistant.io/docs/integrations/universal-links

Later on today I was going to check out NFC.  Maybe someone else with more experience can jump in and help out :)

Are you sure your automation is correct? Your example under `alias` has a missing opening quotation mark

**Comment by pergolafabio** [comment]
Yeah I saw , but I fixed that ;)
But still the same

**Comment by gadgetchnnel** [comment]
The example trigger the app gives when you scan a tag appears to be wrong. It has something like this:

```
- platform: event
  event_type: tag_scanned
  event_data:
    device_id: Phone Name
    tag_id: 521***c75
```

With the **device_id** property as the device name of the device. However, subscribing in the developer tools to all tag_scanned events I see:

![image](https://user-images.githubusercontent.com/2099542/90043455-0abbc500-dcc4-11ea-8caf-224070658d33.png)

That looks like the unique id of the device or integration - I couldn't find it anywhere in the UI, but it is in the /config/.storage/core.device_registry for that device.
