### ISSUE TITLE
Picture-entity: picture not loaded in the Android App

### ISSUE THREAD

**Issue by LorenzoVasi** [home-assistant/android#838]
**Home Assistant Android version:**
2.3.0-306-full
**Android version:**
Android 10
**Phone model:**
Google Pixel 3A
**Home Assistant version:**
HassOS 4.12 - Home Assistant 0.114.4
**Last working Home Assistant release (if known):**
//
**Description of problem:**

Hi, 
in my Home Assistant i add a picture-entity, where i take an image from this link
http://www.prolocobogliasco.it/webcam/current_hd.jpg
In all browsers (PC and Phone) this image loads but only in the app it doesnt load

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/48059088/91611331-52587700-e97b-11ea-801c-0ea674bbc7e8.png)
![image](https://user-images.githubusercontent.com/48059088/91611350-5daba280-e97b-11ea-9d12-131bfc08c2ac.png)

**Additional information:**

Sorry, im italian and my english is very bad. :)

**Comment by dshokouhi** [comment]
I was able to reproduce this with the following card setup

```
 - type: picture-entity
   entity: weather.dark_sky
   image: http://www.prolocobogliasco.it/webcam/current_hd.jpg
```

Not really sure why it doesn't load in the app but does in chrome 🤔

**Comment by dshokouhi** [comment]
@LorenzoVasi do you have SSL setup? I wonder if this is an issue where we are using mixed content because I just realized the link is non-secure and in my setup I am using SSL so the image probably did not load due to the mixup there. We may need to test this when using `http` to connect to home assistant instead of a secure setup.  We also can't convert the link to `https` as its not a valid certificate.  What happens if you try this url `https://i.imgur.com/o2Fdv35.jpeg` does it load as expected?

**Comment by LorenzoVasi** [comment]
https://i.imgur.com/o2Fdv35.jpeg <-- This image loads withouts problem, i think u are right... 
Anyway, i don't want to disable https for only an image because it's open on web my HA... 
What can i do without disable https for this image? 
http://www.prolocobogliasco.it/webcam/current_hd.jpg
I cant download it because this image changes every 5 minutes

**Comment by JBassett** [comment]
@LorenzoVasi if you turn the image into a camera in home assistant then it will be served by your home assistant instance.  I do something similar for a weather radar image:
```
camera:
  - platform: generic
    name: Radar
    still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BUF&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25396520
```

**Comment by LorenzoVasi** [comment]
Ok, now it works :))))) I love u <3 
In this code 
```
camera:
  - platform: generic
    name: Radar
    still_image_url: 
```
I add this:

```
verify_ssl: false
```

Thank u for all!!! :)
