### ISSUE TITLE
High precision mode for location updates

### ISSUE THREAD

**Issue by Tho85** [home-assistant/android#973]
**Is your feature request related to a problem? Please describe.**
I would like to obtain more accurate location updates for a short period of time, in order to trigger time- and location-critical events. For example, I would like to open my garage as soon I approach by bike.

**Describe the solution you'd like**
I would like to have a high-precision location update mode that I could enable or disable through a special message from HA. In this mode, the app would send GPS-only location updates every 15 seconds. So, I would expect the following:

1. Send a notification to the app to start high precision mode

    ```yaml
    automations:
      - ...
        action:
          - service: notify.mobile_app
            data:
              message: start_location_tracking
    ```

2. The app would show a persistent notification "Home Assistant is tracking your location". A background service (?) continuously acquires GPS fixes every 15 seconds, and the existing location tracking mechanism sends these fixes to HA. Similar to fitness trackers.

3. Send a notification to the app to stop high precision mode

    ```yaml
    automations:
      - ...
        action:
          - service: notify.mobile_app
            data:
              message: stop_location_tracking
    ```
   Alternatively, it times out after e.g. 15 minutes.

**Describe alternatives you've considered, if any**

* *Background location*: Location provided by background location is not exact enough, as it is mostly based on Wifi or cell towers in my case. Additionally, it updates at most once a minute, so it triggers too late for my use case, if at all.
* *Zone background / location*: Same as above, it does not update fast enough for my case.
* *`request_location_update`*: Is not exact enough, as it uses the same location mechanism as background location (i.e. Wifi or cell tower).
* *Other triggers like Wifi*: Triggering too late. And it also works for locations where there is Wifi reception. This would not work for locations outside home.

**Additional context**
In my use case, I would add a broader zone around my garage (e.g. 300m in diameter) that would start high precision tracking. When I enter a narrower zone (e.g. 50m in diameter), it would open my garage and stop high precision tracking.

When I have a fitness tracker running in parallel, HA also receives the location update intents. So in order to implement this, we would only need a background service and a notification, and the location update mechanism could stay as it is. This would also benefit other use cases like triggering geofence zones.
